### ISSUE TITLE
Pulp smash is attempting to ssh to dev (127.0.0.1) in the Pulp dev environment

### ISSUE THREAD

**Issue by rbarlow** [PulpQE/pulp-smash#100]
Pulp smash seems to be trying to ssh to the local machine inside the Pulp dev environment. I would expect that it would just run the commands locally when it's running on the same host:

```
$ workon pulp-smash
$ time python -m unittest2 discover ~/devel/pulp-smash/pulp_smash;                
....The authenticity of host 'dev (127.0.0.1)' can't be established.
ECDSA key fingerprint is SHA256:d/F7DUf+uYgyMEFxb1qvZcWzUPAM+mi1aTACu3B9Uuw.
ECDSA key fingerprint is MD5:f3:51:d5:d4:ab:6e:9a:7e:a6:8a:e7:e6:b3:69:64:99.
Are you sure you want to continue connecting (yes/no)? yes
vagrant@dev's password: vagrant@dev's password: 
vagrant@dev's password: 
Evagrant@dev's password: 
vagrant@dev's password:
```

**Comment by dkliban** [comment]
Does your ~/.config/pulp_smash/settings.json contain 

`"cli_transport": "local"`

?

**Comment by Ichimonji10** [comment]
From the documentation for [`pulp_smash.cli.Client`](http://pulp-smash.readthedocs.org/en/latest/api/pulp_smash.cli.html#pulp_smash.cli.Client):

> If `server_config.cli_transport` is `'local'` or `'ssh`, set `machine` so that commands run locally or over SSH, respectively. If `server_config.cli_transport` is `None`, guess how to set `machine` by comparing the hostname embedded in `server_config.base_url` against the current system's hostname. If they match, set `machine` to execute commands locally; and vice versa.

And here's the code:

```python
        # How do we make requests?
        hostname = _get_hostname(server_config.base_url)
        if server_config.cli_transport is None:
            transport = 'local' if hostname == socket.getfqdn() else 'ssh'
        else:
            transport = server_config.cli_transport
```

You can fix this by either:

* setting `"cli_transport": "local"` as suggested by @dkliban,
* setting `"base_url": "my_hostname"`, or
* setting the system's hostname.

**Comment by rbarlow** [comment]
Thanks @dkliban and @Ichimonji10! I went with the "local" flag and that seems to work.

I'm going to try to make a pull request to add that here:

https://github.com/pulp/pulp/blob/f0430cf7bc0ff77319cdff9842e300b1786acc60/playpen/vagrant-setup.sh#L62-L64

**Comment by rbarlow** [comment]
https://github.com/pulp/pulp/pull/2413

**Comment by Ichimonji10** [comment]
:+1:
