### ISSUE TITLE
Register a consumer tests

### ISSUE THREAD

**Issue by dkliban** [PulpQE/pulp-smash#1007]
1. Use the consumer API[0] to register a consumer.
2. Save the certificate returned in step 1.
3. Use the certificate when authenticating to perform an update of the consumer. 

[0] https://docs.pulpproject.org/dev-guide/integration/rest-api/consumer/cud.html#register-a-consumer

**Comment by Ichimonji10** [comment]
@ragabala Is this fixed by https://github.com/PulpQE/Pulp-2-Tests/pull/28 ?

**Comment by ragabala** [comment]
Hi Team,

This issue has been verified and is merged in Pulp-2-tests.
Please refer the [test doc](https://pulp-2-tests.readthedocs.io/en/latest/tests/pulp_2_tests.tests.platform.api_v2.test_consumer.html?highlight=RegisterAndUpdateConsumerTestCase).

Thus closing this one out.
