### ISSUE TITLE
Test downloading content from protected repository

### ISSUE THREAD

**Issue by dkliban** [PulpQE/pulp-smash#1008]
1. Configure Pulp with Global Repository Protection[0].
2. Create a repository.
3. Sync repository.
4. Publish repository.
5. Try to download content from published repository without a certificate and verify that content is not downloaded.
6. Try to download content from published repository WITH a certificate and verify that content is downloaded.

[0] https://docs.pulpproject.org/plugins/pulp_rpm/user-guide/configuration.html#global-repo-authentication

**Comment by ragabala** [comment]
Hi Team,

The issue was tested manually as a part of testing #1009. Refer #1009 for the steps carried out in testing this one out.

Thanks!
