### ISSUE TITLE
 Delete docker repo 

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#101]
1. Create a docker repo

   Assert: Docker repo is created

2.  Sync a docker repo  

   Assert: Sync successful 

3. Delete the docker repo

   Assert: Delete successful

**Comment by Ichimonji10** [comment]
Happy day! This is already done. See:

* [`pulp_smash.tests.docker.api_v2.test_crud`](http://pulp-smash.readthedocs.org/en/latest/api/pulp_smash.tests.docker.api_v2.test_crud.html)
* [`pulp_smash.tests.docker.cli.test_crud`](http://pulp-smash.readthedocs.org/en/latest/api/pulp_smash.tests.docker.cli.test_crud.html)
* [`pulp_smash.tests.docker.cli.test_sync`](http://pulp-smash.readthedocs.org/en/latest/api/pulp_smash.tests.docker.cli.test_sync.html)

**Comment by preethit** [comment]
Awesome. I should have looked.
