### ISSUE TITLE
Pull Pulp 2 tests into separate repo

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-smash#1034]
Let's make a separate repository, and move all of the Pulp 2 tests into that repository. That repository can be a full-fledged package which lists Pulp Smash as a dependency. This will serve as an excellent santiy check. It will help us verify that Pulp Smash has been updated enough to support the use cases described in #949.

This should be done after all of the other issues listed in https://github.com/PulpQE/pulp-smash/milestone/26.

**Comment by omaciel** [comment]
fyi, when this task is handled, please also make sure to update the docs.
