### ISSUE TITLE
Add `try_sudo` to Pulp Smash CLI client

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-smash#1037]
If one wants to run a command as root, the current idiom for doing so is this:

```python
sudo = () if is_root(...) else ('sudo',)
cli_client.run(sudo + ('my', 'cli', 'command'))
```

It'd be far more convenient if the CLI client could encapsulate this idiom. One possible route would be to:

1. Fix https://github.com/PulpQE/pulp-smash/issues/1036
2. Update the CLI client so that it could be used like `cli_client.run(('my', 'cli', 'command'), maybe_sudo=True)`.

If `maybe_sudo` is passed, then the `sudo = ...; cmd = sudo + cmd` idiom could be performed within the CLI client. This idiom won't work in all cases. Sometimes, sudo shouldn't be the first word in a command. For these cases, a user should still be able to use `is_root`, so we should make the `maybe_sudo` argument default to false and leave the `is_root` function in place.

**Comment by rochacbruno** [comment]
Addressed by #1132
