### ISSUE TITLE
Decide how to host content for pulp-smash to test syncs

### ISSUE THREAD

**Issue by asmacdo** [PulpQE/pulp-smash#104]
Currently, the feed is pulp's fedorapeople for RPM, puppet forge, and dockerhub. It would be ideal for pulp-smash to have its own demo content, even if it is just a mirror of the content we currently use.

This will speed up the tests and will enable pulp-smash to test syncing with repositories that have the traits necessary to replicate certain bugs. For example:  https://github.com/PulpQE/pulp-smash/issues/93

**Comment by Ichimonji10** [comment]
Being able to customize where Pulp Smash tests get content from would have several benefits:

* If some content source becomes unavailable, we could simply point Pulp Smash at some other content source. This would lower our reliance on outside systems that are outside our control.
* Tests can be *much* faster and more robust if the content is being pulled from a nearby source.
* If the content source is the local system, the test suite could be run completely offline.

**Comment by Ichimonji10** [comment]
My main worry is getting the implementation details right. One proposal is to make demo content available and then asking users to download that content locally and then setting up a content server. This could be cool - but how hard would that be to do? Setting up server for RPM files is easy: it requires just executing `python -m http.server 80` at the root of some directory tree. But what about docker and puppet, where the content server has to implement an API?

One option is to use Pulp itself as a content source. The big advantages here are that:

* We'd be dog-fooding.
* Pulp does support serving all these content types.

Bug there's some caveats:

* Pulp can be slow and buggy at times. (I'm not attacking anyone here! But let's be realistic.)
* Pulp can be hard to install.
* Pulp *can't* be installed on many platforms.
* Forcing the test suite user to set up a content server before testing Pulp raises the barrier to entry!

These cons can be mitigated if we have a Pulp server publicly (?) available to anyone who wants to use it.

**Comment by rbarlow** [comment]
The Python sync can't be done from a Pulp server (or a static content server) - it requires PyPI because of an interactive API.

**Comment by Ichimonji10** [comment]
So that's at least docker, puppet and python that must be served from something that implements an API.

**Comment by asmacdo** [comment]
https://botbot.me/freenode/docker-distribution/2016-02-22/?msg=60658740&page=1

This comment from a docker dev suggests that syncing a lot of content from docker hub could possibly result in being throttled.

**Comment by omaciel** [comment]
@asmacdo should we create/maintain our own registry and perhaps have our tests pointing at it? This may solve one issue, but then, how can we make our own registry 'relevant' with what Docker Hub offers so that we're always up to date?

**Comment by asmacdo** [comment]
@omaciel, I think that would be a good solution. I don't think we need to keep a testing registry up to date as a Dockerhub mirror. It only needs a small number of repos for pulp to sync down for testing. We can even create this content, no need to sync it from Dockerhub at all. 

I know of at least one thing that is special about Dockerhub, which is the un-namespaced repository issue, but I think that this should be considered an acceptable hole in testing if it means faster, more reliable, and more polite tests.

**Comment by Ichimonji10** [comment]
:+1:

How about using our own content server for nearly all docker-related tests, and then letting [`SyncUnnamespacedV2TestCase`](http://pulp-smash.readthedocs.org/en/latest/api/pulp_smash.tests.docker.cli.test_sync.html#pulp_smash.tests.docker.cli.test_sync.SyncUnnamespacedV2TestCase) continue hitting docker hub?

**Comment by asmacdo** [comment]
That seems fine

**Comment by rbarlow** [comment]
@asmacdo @omaciel I do think we at least want two tests that actually sync with Dockerhub - one for v1 and one for v2. Syncing with Dockerhub does not work exactly the same as syncing with Pulp or even the same as syncing with a Docker Distribution container.

**Comment by omaciel** [comment]
@rbarlow agreed. So I wonder if we should have something like this:

* Run a test (or a few) to make sure that we can sync against Dockerhub using both v1 and v2
* All other tests that don't necessarily require Dockerhub could go against our internal registry

Thoughts?

**Comment by rbarlow** [comment]
@omaciel yeah that sounds like a great plan!

**Comment by omaciel** [comment]
@rbarlow @Ichimonji10 @preethit @asmacdo so to do what I [proposed](https://github.com/PulpQE/pulp-smash/issues/104#issuecomment-188423741), we need a couple of things to happen:
1. Someone would have to create a registry, preferably somewhere open to the community
1. Someone would have to determine which existing test cases should be pointed at Dockerhub and which ones should use the 'community' registry

Any volunteers?

**Comment by preethit** [comment]
@omaciel I can help with #2. I am not exactly sure how to do it. But may be able to work with @asmacdo or @rbarlow

**Comment by asmacdo** [comment]
@preethit, https://docs.docker.com/registry/ should get you started.

**Comment by Ichimonji10** [comment]
We've solved the bulk of concerns raised in this thread by creating pulp fixtures, using Jenkins to generate fixtures and upload them to https://repos.fedorapeople.org/pulp/pulp/fixtures/, and then referencing them via https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/constants.py.
