### ISSUE TITLE
Fully support doctest test runner

### ISSUE THREAD

**Issue by kersommoura** [PulpQE/pulp-smash#1049]
Let's update our documentation so that the code samples embedded within it can be executed with the [doctest test runner](https://docs.python.org/3.6/library/doctest.html). This requires doing at least the following:

* [ ] Add a make target which, when executed, will run doctests. As a suggestion, call this make target `test-doctest`.
* [ ] Ensure the `all` make target depends on this new make target.
* [ ] Ensure Travis executes these tests. Making the `all` target depend on the `test-doctest` target should make this happen.
* [ ] Update the existing sample code so that it correctly executes, and so that it doesn't make real calls to external resources. [`unittest.mock`](https://docs.python.org/3.6/library/unittest.mock.html) might help.
* [ ] Maybe update the prose documentation to mention the doctests.

**Comment by Ichimonji10** [comment]
I'm pulling this task off the milestone for several reasons:

* We're short on time. I want to have Pulp Smash tests migrated to Pulp developer repos by the end of this week.
* Implementing [high quality doctests](https://docs.python.org/3.7/library/doctest.html#soapbox) takes time.
* I've seen no progress on this task in the past six weeks or so.

If bandwidth is available, please review PRs that other milestone goals. There are currently three such PRs.

**Comment by rochacbruno** [comment]
I think we can close this issue, I dont believe we are putting any effort on doctests.

**Comment by kersommoura** [comment]
@rochacbruno, I think so.
