### ISSUE TITLE
Test sync with dockerhub with unnamespaced repositories

### ISSUE THREAD

**Issue by asmacdo** [PulpQE/pulp-smash#105]
https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/tests/docker/cli/test_sync.py#L16

The repository's real location is `library/busybox`, but when pulling from Dockerhub, the Docker client automatically prepends `library/` to any unnamespaced repos. Syncing from `upstream-name=busybox` should have exactly the same result.

**Comment by Ichimonji10** [comment]
Should we have tests that do both? That is, should we use both `--upstream-name=busybox` and `--upstream-name=library/busybox`?

**Comment by rbarlow** [comment]
@Ichimonji10 I don't seem to be able to self-assign this issue - can you assign it to me? I'm gonna hack on it this afternoon.

**Comment by rbarlow** [comment]
And yeah, I'll just make a test for each style.

**Comment by rbarlow** [comment]
Haha, I think @asmacdo is actually working on this, but hadn't assigned it when I asked. Sorry for the confusion!
