### ISSUE TITLE
Switch from date-based versioning to semantic versioning

### ISSUE THREAD

**Issue by kersommoura** [PulpQE/pulp-smash#1050]
Pulp Smash currently uses a date-based versioning scheme. A new version is released every Thursday, with version numbers like `2018.06.07`. Let's switch to semantic versioning. Let's do this after all Pulp tests have been moved out of Pulp Smash and into other repositories.

This will require bumping the version epoch. That is, a `1!` will need to be prepended to the current version.

**Comment by rochacbruno** [comment]
I recommend we take a look at the OpenStack pbr package, which helps managing semantic versioning based on git tags, and generates the changelog and all the stuff.

https://docs.openstack.org/pbr/latest/user/features.html

**Comment by Ichimonji10** [comment]
I recommend against the use of pbr for version management, for a couple reasons.

First, it's a new dependency. Each additional dependency makes Pulp Smash harder to learn, buggier, and harder to package.

Second, it significantly complicates the packaging machinery. It adds a layer on top of the well understood setuptools packaging machinery, while still requiring that the user understand how the underlying packaging machinery would work without pbr.

Third, it implements several misfeatures. For example: it [requires `requirements.txt`](https://docs.openstack.org/pbr/latest/user/features.html#requirements) and optionally `requirements-py3.txt` to specify dependencies. This is a **bad idea**. We should **not** be shipping a `requirements.txt` file with Pulp Smash. See: [setup.py vs requirements.txt](https://caremad.io/posts/2013/07/setup-vs-requirement/). It also auto-generates an [overly-generous MANIFEST.in](https://docs.openstack.org/pbr/latest/user/features.html#manifest) file. It also auto-generates a changelog from git, which is easy to do with a simple script if desired, and not something that's desirable if one is writing good quality release notes.

Fourth, it significantly complicates things. Have I mentioned this yet? I should mention this again. It overrides the `build_sphinx` command. It requires the use of git and, uh, `Sem-Ver` pseudo-headers, whatever those are. It adds a `setup.cfg` file that's less flexible than `setup.py`, and just... contains the same information.

If we're going to put effort into complicating the packaging machinery, I'd suggest looking into something like [pipenv](https://docs.pipenv.org/) instead. It has a clear value proposition and is made by the well-respected Kenneth Reitz.

**Comment by Ichimonji10** [comment]
This is done. See:

* [Pulp Smash on PyPI](https://pypi.org/project/pulp-smash/)
* https://github.com/PulpQE/Pulp-2-Tests/pull/3
