### ISSUE TITLE
Create Jenkins Job for FIPS Test Suite

### ISSUE THREAD

**Issue by omaciel** [PulpQE/pulp-smash#1051]
Using Jenkins Job Builder, create the job definition for all required jobs that will enable FIPS testing for Pulp Smash.

**Comment by Ichimonji10** [comment]
The job definitions should live in https://github.com/pulp/pulp-ci/.

**Comment by ragabala** [comment]
Hi @omaciel @kersommoura @Ichimonji10 @rochacbruno 

This job was finished as a part of the node pool migration. 
This job is accomplished in a two-step process.
1. Disk Image Builder Job - That creates RHEL images with fips enabled. This job creates a new image thereby replacing the existing ones for the latest environment.
2. Project pulp-2-master-dev-rhel7-fips Job - That runs pulp installer and then tests with pulp smash tests on this environment created in the previous step.

The job now resides in [Jenkins](https://pulp-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/pulp-2-master-dev-rhel7-fips/).

Thus closing this milestone.
