### ISSUE TITLE
Test dependency solving resolution on RPM repo copy

### ISSUE THREAD

**Issue by seandst** [PulpQE/pulp-smash#107]
When recursively copying rpm units from one repo to another, only the latest units should be copied. The zoo repo provides packages with dependencies that can be used to verify this functionality. Specifically, it provides two version of 'walrus', and 'chimpanzee' depends on walrus; only one version of walrus should be copied when recursively copying chimpanzee.

Here are the relevant pulp-admin commands:
```
pulp-admin rpm repo create --repo-id zoo --feed https://repos.fedorapeople.org/repos/pulp/pulp/demo_repos/zoo/
pulp-admin rpm repo sync run --repo-id zoo
pulp-admin rpm repo create --repo-id new
pulp-admin rpm repo copy rpm --from-repo-id zoo --to-repo-id new --str-eq="name=chimpanzee --recursive"
```

If this is working correctly, only walrus 5.21 is associated with the 'new' repository. If this is broken, both walrus 0.71 and walrus 5.21 will be associated with the 'new' repository.

This test could potentially be used to test dependency solving generally (or perhaps this could be a separate issue). If it's working correctly, the only latest versions of  camel, chimpanzee, fox, squirrel, and walrus will be in the 'new' repo. If the number of packages associated with the 'new' repo after copy is not exactly 5, and the names aren't the 5 aforementioned names, dependency solving is generally broken.

More information can be found in https://pulp.plan.io/issues/1432#note-9.

**Comment by omaciel** [comment]
Thank you @seandst for the issue. I have set a `high priority` label to it and assigned it to @Ichimonji10 for automation.

**Comment by Ichimonji10** [comment]
:+1:
