### ISSUE TITLE
Split tests into sections

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-smash#11]
All tests currently reside in `pulp_smash/tests/`. This works, but it doesn't scale well. How can a user find the kind of test they're looking for?

I'd recommend changing the layout from this:

```
pulp_smash
├── config
│   └── …
└── tests
    ├── test_content_applicability
    └── test_login
```

To this:

```
pulp_smash
├── config
│   └── …
└── tests
    ├── api_v1
    │   └── …
    ├── api_v2
    │   ├── test_content_applicability
    │   └── test_login
    └── cli
        └── …
```

**Comment by elyezer** [comment]
:+1:

**Comment by peterlacko** [comment]
I would suggest one more directory level indicating functionality which we test to: 
* general_tests/ (would contain tests not related to content, like create/update/delete user, change permissions)
* rpm_tests/
* iso_tests/
* puppet_tests/
* docker_tests/

**Comment by Ichimonji10** [comment]
@peterlacko That makes sense to me. Your approach would probably work better than what I've suggested, for two reasons:

* A user may not have a full battery of test systems available. Tests that make use of only certain systems (e.g. just a pulp system, or just a pulp system and a node) will probably be group together into a feature group.
* Your proposed layout mirrors what's currently in place in Pulp Automation. If that approach is tried and true, I see little reason to change it, especially if it'll make porting tests easier.

So how about a layout like this?

```
pulp_smash
├── config
│   └── …
└── tests
    ├── general_tests
    │   ├── test_content_applicability
    │   └── test_login
    ├── rpm_tests
    │   └── …
    └── iso_tests
    ⋮   └── …
```

**Comment by peterlacko** [comment]
I would say it makes sense, however we still need to be able to easily distinguish between api and cli tests, would be this structure too deep?

    pulp_smash
    ├── config
    │   └── …
    └── tests
        ├── general_tests
        │   ├─ api_v1
        │   │  └  some_test
        │   ├─ api_v2
        │   │  ├── test_content_applicability
        │   │  └── test_login
        │   └─ cli_tests  
        │        └── some_test
        ├── rpm_tests
        │   └ api_v1
        │      └ some_test
        │   ├ api_v2
        │   ⋮  
        └── iso_tests
        ⋮   └── …

**Comment by Ichimonji10** [comment]
@peterlacko Do any tests overlap in their functionality? I can imagine a test which touches on both RPMs and Puppet, for example.

**Comment by peterlacko** [comment]
Can you provide an example of such a test? I think most of tests will be under v2 api, so having them all under one directory could be mess when there will be hundreds of tests. What about putting tests with overlapping functionality into another, separate directory? I don't consider it as a best solution, just don't see better now.

**Comment by Ichimonji10** [comment]
@peterlacko No, I can't provide an example of such a test. I'm just thinking ahead and theorizing that tests will be written that target multiple features. Let's say a Pulp user discovers some weird bug that's caused by an interaction between two of Pulp's plug-ins. The test for that weird bug will end up in a functional tests suite - this application.

**Comment by Ichimonji10** [comment]
@peterlacko I think the test structure outlined [here](https://github.com/PulpQE/pulp-smash/issues/11#issuecomment-148437813) is our best option right now. Yes, it's a little deep. But it's not outrageous, it lets us easily distinguish between CLI and API tests, and it retains the advantages mentioned [here](https://github.com/PulpQE/pulp-smash/issues/11#issuecomment-148427023):

> * A user may not have a full battery of test systems available. Tests that make use of only certain systems (e.g. just a pulp system, or just a pulp system and a node) will probably be group together into a feature group.
> * Your proposed layout mirrors what's currently in place in Pulp Automation. If that approach is tried and true, I see little reason to change it, especially if it'll make porting tests easier.

Let's go for it. If this level of test granularity proves insufficient, we can try out a more powerful tool, such as [`nose2.plugins.attrib`](http://nose2.readthedocs.org/en/latest/plugins/attrib.html). (By the way, the [Test Discovery and Loading](http://nose2.readthedocs.org/en/latest/differences.html#test-discovery-and-loading) caveat indicates that nose2 may not be an appropriate test runner.)

**Comment by Ichimonji10** [comment]
> What about putting tests with overlapping functionality into another, separate directory? I don't consider it as a best solution, just don't see better now.

That seems like the best solution if the only tool in hand is test structure. When that situation arises, we can also investiate an option such as nose2's attributes.
