### ISSUE TITLE
Move API & CLI functions out of `pulp_smash.utils`

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-smash#110]
Module `pulp_smash.utils` includes the following functions that make use of the API:

* `poll_spawned_tasks`
* `poll_task`
* `reset_pulp`

It also includes a `get_broker` function that makes use of the CLI.

Let's move these functions out of `pulp_smash.utils`. Having these functions all dumped together into this single module is problematic. Most pressingly, it is impossible to move the `_get_plugin_types_ids` function into `pulp_smash.utils` due to a circular import issue!

One option is to move these functions straight to `pulp_smash.api` and `pulp_smash.cli`, respectively. This is an OK thing to do. However, it does bring up the issue of confused responsibilities: as it stands, `pulp_smash.api` and `pulp_smash.cli` are purely concerned with providing clients for talking to a server, and are not concerned with our specific needs for those clients. This is cool, b/c we could theoretically move the clients into a separate package! Here's some other options that would better promote a separation of concerns:

* We could make `pulp_smash.api` a package. We could then move the client code into `pulp_smash.api.client`, and put API utility code into `pulp_smash.api.utils`. Similar comments apply to the CLI code.
* We could add a `pulp_smash.api_utils` module. This is a lower impact option, as fewer references would need to be edited. Also, `pulp_smash.api.client.Client` is redundant, where as `pulp_smash.api.Client` is direct.

**Comment by omaciel** [comment]
Thank you @Ichimonji10 for the write up. I prefer the first option and 'bundle' all API-related code into its own package/namespace.

**Comment by Ichimonji10** [comment]
Cool. Thanks for the input. :smile:

**Comment by Ichimonji10** [comment]
Having this issue solved will allow me to write a mixin for use in #81. Assigning to self.
