### ISSUE TITLE
The weak Recommends dependency is processed during recursive copies

### ISSUE THREAD

**Issue by dparalen** [PulpQE/pulp-smash#1107]
### Description
Pulp should consider the [`recommends` weak forward dependency](http://rpm.org/user_doc/dependencies.html#weak-dependencies) when calculating recursive RPM copy dependencies. To give a real-world workflow use case with both positive and negative check:

- [x] create an `F28` repository and sync it from the [Fedora28 Server](http://mirrors.nic.cz/fedora/linux/releases/28/Server/x86_64/os/) (fewer RPMs) feed
- [x] apply the `pulp_rpm` PR https://github.com/pulp/pulp_rpm/pull/1135
- [x] create an `F27` repository and sync it from the [Fedora27 Server](http://mirrors.nic.cz/fedora/linux/releases/27/Server/x86_64/os/) feed
- [x] create an empty repo e.g `foo`
- [x] copy the `dnf...-f27` rpm recursively to the `foo` repo
- [ ] check that `sqlite` rpm _was_ pulled in :pear:
- [ ] create an empty repo e.g `bar`
- [ ] copy the `dnf...-f28` rpm recursively to the `bar` repo
- [ ] check that the `sqlite` rpm _wasn't_ pulled in 
- [ ] check that the `dnf` unit doesn't have the `recommends` attribute populated in Mongo
- [ ] check that there are 2 `dnf` rpm content units in Mongo
- [ ] check that the `dnf` rpm with `f27 release` has the `recommends` attribute populated and that it contains the `sqlite` record :pear:

The test can be reduced to the positive branch only for the automation.

### Notes
:beetle: https://pulp.plan.io/issues/3847

Mind using your local Fedora mirror; the links above use a CZ one

**Comment by Ichimonji10** [comment]
Is this a Pulp 2 or Pulp 3 test case?

**Comment by dparalen** [comment]
My bad; targeted to 2.17; how do I best mark that?

**Comment by Ichimonji10** [comment]
I just created a label for the purpose. :smile:

**Comment by dparalen** [comment]
just an FYI: the negative branch of the test case might not be possible to check if the related migration https://github.com/pulp/pulp_rpm/pull/1135/commits/fd9dac3ad1418b9532aa95f0a4fc58ce18399a15 lands.

**Comment by kersommoura** [comment]
We have tests for recursive and simple copy of rich/weak dependencies. Test uses the fixtures from here: [rich/weak](https://repos.fedorapeople.org/pulp/pulp/fixtures/rpm-richnweak-deps/)

I will close this issue. Feel free to re-open in case of need.
