### ISSUE TITLE
Test 'docker pull' from Crane

### ISSUE THREAD

**Issue by dkliban** [PulpQE/pulp-smash#1111]
1. Create a docker repository with a docker_importer that has the following values: feed=https://registry-1.docker.io, upstream-name=busybox

2. Sync repository 

3. Publish repository

4. Perform calls needed to simulate docker pull.

**Comment by ragabala** [comment]
Hi ,

These are requests that were done to download the docker content from pulp
`curl -L -k -X GET <pulp-host-name>:5000/v2/mydocker2/manifests/latest`
response output example : 
```
'fsLayers': [{'blobSum': 'sha256: ...'},
  {'blobSum': 'sha256:...'},
  {'blobSum': 'sha256:...'},
  ...
'}],
```
This lists a json with information about all the blobs that are to be downloaded as a part of the image.
 
to download each of these blobs to build the image,  the following URL is hit recursively with the blob shasum that were returned as a part of the first request.
`curl -L -X GET <pulp-host-name>:5000/v2/mydocker2/blobs/sha256:<shasum> >> docker.image`

response : The response for the above url contains **binary object**

**Comment by Ichimonji10** [comment]
Is this fixed by https://github.com/PulpQE/Pulp-2-Tests/pull/4 ?

**Comment by rochacbruno** [comment]
@ragabala can we close this?

**Comment by ragabala** [comment]
Thanks @rochacbruno 

Closing this one as we have automated and tested this.
