### ISSUE TITLE
Test Sync Schedule

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#112]
https://pulp.plan.io/issues/1116
https://pulp.plan.io/issues/1381

1. create a repo
    pulp-admin -u admin -p admin rpm repo create --repo-id zoo --relative-url zoo --feed http://repos.fedorapeople.org/repos/pulp/pulp/demo_repos/zoo

2. create a scheduled sync to run every minute:
pulp-admin -u admin -p admin rpm repo sync schedules create --repo-id zoo --schedule 2015-06-06T14:29:00Z/PT1M
Assert: 
  1. Sync schedule can be created
  2. Sync runs at the scheduled time.

**Comment by goosemania** [comment]
@Ichimonji10 , please assign this one to me.

**Comment by Ichimonji10** [comment]
Done. I've also given you permissions to edit issues. Use it wisely! (The same permission gives repo write access.)

**Comment by asmacdo** [comment]
I think it would be helpful to do a full set of crud tests, not just create and run. These should include listing all schedules and listing an individual schedule, and update and delete.

**Comment by asmacdo** [comment]
To reclose this issue either:
* Confirm that all cases in the following module are covered:
https://github.com/RedHatQE/pulp-automation/blob/master/tests/general_tests/test_19_scheduled_sync.py

or

* Create issues for the gaps

**Comment by elyezer** [comment]
@asmacdo I have reviewed everything added by referenced commit as well as other test modules and Pulp Smash have equivalent tests for what is listed on the link you shared.

Most of the tests are covered by https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/tests/rpm/api_v2/test_schedule_sync.py and test for getting the history is available at  https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/tests/rpm/api_v2/test_sync_publish.py.

We are safe to close this issue.
