### ISSUE TITLE
Test migration for transition from basic to advanced modular support

### ISSUE THREAD

**Issue by ipanova** [PulpQE/pulp-smash#1123]
https://pulp.plan.io/issues/3659

1. with pulp 2.16 create and sync modular repo
2. upgrade to 2.17, run migration
3. ensure yum_repo_metadata_file which contained modules.yaml was removed from the repo
4. instead modulemd and modulemd_defaults content were identified and associated to the repo
5. list of repositories to re-publish was provided (by migration)

**Comment by kersommoura** [comment]
This issues should be manual tested. Right now, we do not have any test that update Pulp version. 

We do have a Jenkins job to update Pulp version, but not a test per se.

**Comment by ragabala** [comment]
Hi Team,

Have verified this manually. Was able to see the `yum_repo_metadata_file` field in p2.16 got removed and replaced with `modulemd` and `modulemd_defaults` fields after upgrade to p2.17.

Thus closing this one out.

Thanks!
