### ISSUE TITLE
Test Pulp Consumer Repo bind

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#113]
Test pulp consumer bind.
https://pulp.plan.io/issues/1399

1. Register a consumer

pulp-consumer -u admin -p admin register --consumer-id foo

Assert:
 Consumer registration successful

2. Bind a repository to the consumer
pulp-consumer rpm bind --repo-id=zoo
Assert:
   Repository bind is successful.

**Comment by jortel** [comment]
Can an admin assign this issue to me?

**Comment by Ichimonji10** [comment]
Done. I've also given you permissions to edit issues. Use it wisely! (The same permission gives repo write access.)

**Comment by elyezer** [comment]
The related PR is merged, we are safe to close this.
