### ISSUE TITLE
Test Publish Schedule

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#114]
Create a repo:

```sh
pulp-admin -u admin -p admin rpm repo create \
    --feed http://repos.fedorapeople.org/repos/pulp/pulp/demo_repos/zoo \
    --relative-url zoo \
    --repo-id zoo
```

Create a scheduled sync to run every 60 minute:

```sh
pulp-admin -u admin -p admin rpm repo sync schedules create \
    --repo-id zoo \
    --schedule 2015-06-06T14:29:00Z/PT60M
```

Assert:

* Sync schedule can be created
* Sync runs at the scheduled time.

Create a scheduled publish every 90 minutes:

```sh
pulp-admin -u admin -p admin rpm repo publish schedules create \
    --repo-id zoo \
    --schedule 2015-06-06T14:29:00Z/PT90M
```

**Comment by preethit** [comment]
Create a repo
pulp-admin -u admin -p admin rpm repo create --repo-id zoo --relative-url zoo --feed http://repos.fedorapeople.org/repos/pulp/pulp/demo_repos/zoo

Create a scheduled sync to run every 60 minute:
pulp-admin -u admin -p admin rpm repo sync schedules create --repo-id zoo --schedule 2015-06-06T14:29:00Z/PT60M
Assert:

Sync schedule can be created
Sync runs at the scheduled time.

Create a scheduled publish every 90 minutes
pulp-admin -u admin -p admin rpm repo publish schedules create --repo-id zoo --schedule 2015-06-06T14:29:00Z/PT90M

**Comment by pcreech** [comment]
I can take this one on, can someone assign it to me?

**Comment by Ichimonji10** [comment]
Done. I've also given you permissions to edit issues. Use it wisely! (The same permission gives repo write access.)

**Comment by pcreech** [comment]
Assigned to @goosemania as she is working on 112, which is similar

**Comment by asmacdo** [comment]
Need full CRUD tests as I mention here:
https://github.com/PulpQE/pulp-smash/issues/112#issuecomment-188909229

**Comment by goosemania** [comment]
@preethit, was this issue initially created to test two consecutive schedules, sync-publish? or it is ok to test just publish case here because we have separate tests for scheduling a sync?

**Comment by preethit** [comment]
@goosemania Looking at this issue, I realized that publish cannot be scheduled. Yes please change it to test publish if it makes sense. Or we can close it as well.

**Comment by goosemania** [comment]
@preethit, I think [it can be scheduled](https://pulp.readthedocs.org/en/latest/dev-guide/integration/rest-api/repo/publish.html#scheduling-a-publish), i did it recently.
