### ISSUE TITLE
Evaluate make few methods of PackageManager public

### ISSUE THREAD

**Issue by kersommoura** [PulpQE/pulp-smash#1140]
https://github.com/PulpQE/pulp-smash/blob/1fab4b6560be61bf4f3a0740873674a134da2c19/pulp_smash/cli.py#L652

Sometimes, we need to peek under the hood, and this is a good example of that. Maybe `_get_package_manager()` could be made into a public function.

**Comment by rochacbruno** [comment]
If you try to instantiate the `PackageManager(cfg)` it will raise the `NoKnownPackagemanager` without the need to call the `_get_package_manager` static method.

**Comment by rochacbruno** [comment]
I agree that if there are multiple parts of the code that uses the same method then we should make it public, or create a `@property` to access it.

https://github.com/pulp/pulp_rpm/pull/1188/files#r218533553

**Comment by rochacbruno** [comment]
@kersommoura  In terms of **O.O** the better would be

```
# Instantiate the package manager
pkg_mgr = cli.PackageManager()  # does nothing only configure stuff the lazier the better

#  Access commands and properties of `pkg_mgr`, 
# if invalid it will lazily raise the NoKnownPackageManagerException

# which package manager is this?
pkg_mgr.name == "dnf"    # .name is a @property

# install something
pkg_mgr.install('package')   # internally calls `self.name`
```

**Comment by rochacbruno** [comment]
`.name` propery added to fix this issue!
