### ISSUE TITLE
Test Remove/Unassociate  feature

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#115]
Rest API
http://pulp.readthedocs.org/en/latest/dev-guide/integration/rest-api/content/associate.html#unassociating-content-units-from-a-repository
- [x]  category     - remove package categories from a repository
- [ ]   distribution - remove distributions from a repository
- [x]   drpm         - remove DRPMs from a repository
- [ ]   environment  - remove package environments from a repository
- [x]   errata       - remove errata from a repository
- [x]   group        - remove package groups from a repository
- [ ]   metafile     - remove yum metadata files from a repository
- [x]   rpm          - remove RPMs from a repository
- [x]   srpm         - remove SRPMs from a repository

Example for removing an errata.

https://pulp.plan.io/issues/1535

Create a repository

pulp-admin rpm repo create --repo-id=foo  --feed=https://repos.fedorapeople.org/repos/pulp/pulp/demo_repos/zoo/

Synchronize the repository
pulp-admin rpm repo sync run --repo-id=foo

List the errata
pulp-admin rpm repo content errata --repo-id foo

Remove an errata
pulp-admin -vv rpm repo remove errata --repo-id=foo --in='id=RHEA-2010:0002'

**Comment by Ichimonji10** [comment]
@preethit Where will the errata in this test case come from?

**Comment by preethit** [comment]
The zoo repo has the errata. I have updated the step to list the errata first.

**Comment by Ichimonji10** [comment]
Awesome! Thank you.

**Comment by asmacdo** [comment]
@preethit I saw that your docs link is our old docs page. The correct link is this:
http://pulp.readthedocs.org/en/latest/dev-guide/integration/rest-api/content/associate.html#unassociating-content-units-from-a-repository

**Comment by preethit** [comment]
@asmacdo Thanks fixed now.

**Comment by asmacdo** [comment]
This will test the removal of some units, but we are restricted by the units provided by the demo repository. I have updated a ticket in pulp to improve this demo repo:
https://pulp.plan.io/issues/1668

**Comment by asmacdo** [comment]
Under the hood, the remaining unit types should work similarly to the ones being tested. They should still be done, but I suspect that most errors should be caught by the tests I added in #137. Therefore, I will leave this issue open, but recommend a low priority.

**Comment by asmacdo** [comment]
Reopening because referenced commit does not include all types.

**Comment by kersommoura** [comment]
For distribution see [distribution](http://docs.pulpproject.org/plugins/pulp_rpm/tech-reference/yum-plugins.html#distribution)
