### ISSUE TITLE
Constants should be imutable

### ISSUE THREAD

**Issue by rochacbruno** [PulpQE/pulp-smash#1157]
Here and on plugin repositories we see some mutable variables defined in constant files.

like this:

https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/pulp3/constants.py#L23

```py
DOWNLOAD_POLICIES = ['immediate', 'on_demand', 'streamed']
```

It is problematic as on test cases those data can be easily changed and because of that we see sometimes the use of the `copy()` method.

Ideally on `constants.py` across any repo we must define sequences as `tuple` and key/pairs as `MappingProxyType` so we never allow that data to be modified.

When needed the tester should create a new list based on the tuple or copy the Mapping as a new dictionary

**Comment by kersommoura** [comment]
This issue was already addressed. See: https://github.com/PulpQE/pulp-smash/pull/1158
