### ISSUE TITLE
Pulp-smash polling timeout is too high for Travis

### ISSUE THREAD

**Issue by daviddavis** [PulpQE/pulp-smash#1173]
We're running pulp-smash tests in Travis. It looks like when pulp-smash polls, it will wait up to 30 min:

https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/api.py#L526

The problem is that Travis times out after 10 min. We should have pulp-smash timeout after about 5-8 min. This would provide us with better information as we would know a task is taking too long vs simply having an error appear in Travis.

Perhaps this poll number could be a config variable?

**Comment by kersommoura** [comment]
@daviddavis, this time was chosen to solve a Pulp 2 issue. Let`s evaluate to have different time out for Pulp 3.

**Comment by daviddavis** [comment]
@kersom, would it be possible to have a configuration setting? You could even default it to the current value.

**Comment by daviddavis** [comment]
Also, I want to point out [that the issue of having a hard-coded timeout has been problematic for us before](https://github.com/PulpQE/Pulp-2-Tests/issues/6).

**Comment by kersommoura** [comment]
@daviddavis, I think so. We will evaluate this, and we are currently evaluating our whole process to define the settings file.
