### ISSUE TITLE
Create new create_distribution method

### ISSUE THREAD

**Issue by CodeHeeler** [PulpQE/pulp-smash#1178]
This PR for pulp3 changed distribution creation, updates, and deletion to be asynchronous: https://github.com/pulp/pulpcore/pull/6

The result is that these actions return a task now instead of a distribution object.  Anywhere tests performed these actions needed additional code added that was largely the same as you see here:
https://github.com/pulp/pulpcore/pull/6/files#diff-5400f9161b5ae065143722f44303c5e1R97

This work could be deduplicated by writing a new create_distribution method in pulp-smash that handles the returned task object and then yields the actual distribution for consumption by the tests.

**Comment by rochacbruno** [comment]
I would give it an async'ish name

 ```python3
def await_distribution(task: TaskObject) -> dict:
```

**Comment by rochacbruno** [comment]
https://github.com/pulp/pulpcore/pull/6#discussion_r263019901

**Comment by rochacbruno** [comment]
This are the existing functions we can use to create that generic function 

https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/api.py#L485-L551
