### ISSUE TITLE
Drop static attributes from ServerConfig class

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-smash#12]
The `pulp_smash.config.ServerConfig` class currently has static attributes named `_xdg_config_dir` and `_xdg_config_file`. These attributes are used by other methods when those methods need to choose a configuration file to manipulate. For example, `read()` consults these attributes when deciding which file to read.

This works well if there's only one configuration file that is in use. But what if there's multiple configuration files in use? As things stand, one needs to write something like this:

```python
cfg1 = ServerConfig.read(path='~/.config/pulp_smash/pulp_servers.json')
cfg2 = ServerConfig.read(path='~/.config/pulp_smash/pulp_nodes.json')
```

This works well if you know exactly where on the filesystem these files exist. But that assumption is too invasive! One of the aims of the XDG Base Directory Specification is to avoid this level of deep integration with the system. Using hard-coded paths is a Bad Thing. What if the `XDG_CONFIG_DIRS` environment variable has been set? What if system-wide configuration files are being read? And so on?

This issue can be solved by changing `_xdg_config_file` and `_xdg_config_dir` from class to instance attributes. It'll allow us to write code like this:

```python
cfg = ServerConfig()
cfg._xdg_config_file = 'pulp_servers.json'
cfg1 = cfg.read()
cfg._xdg_config_file = 'pulp_nodes.json'
cfg1 = cfg.read()
```

This is, frankly, still pretty ugly. I don't like it. But dropping global state is a move in the right direction. We can move forward from there.

**Comment by elyezer** [comment]
What if the ServerConfig receives the `xdg_config_file` as a parameter (on `__init__`)? IMO this looks better because one don't have to access a private variable (also autocomplete editors and ipython will not show that attr).

**Comment by Ichimonji10** [comment]
@elyezer I think that's a great suggestion. I'll try to get this done ASAP. Usage of the config object will only grow.
