### ISSUE TITLE
Assert that two publishes do not modify the RPM repodata

### ISSUE THREAD

**Issue by bmbouter** [PulpQE/pulp-smash#127]
Test setup:
- Create a repo and sync+publish it (ie: zoo)

The test:
- Get the contents of repodata from the published repo
- publish zoo a second time
- Get the contents of repodata from the published repo now

Assert that all the metadata files and their filenames are identical.

If Pulp is publishing a second time, when there is nothing to do, it should do nothing. In the past a republish caused metadata to get republished in all cases which changes the checksum included in the filename. That was undesirable since the repodata itself didn't change the checksums shouldn't change.

This was believed to already be fixed so there isn't an open issue. For now this guarantee is only expected to be on RPM content, but I think it makes sense for all content types.

**Comment by pcreech** [comment]
Looks like we do not currently guarantee this for pulp 2.8.0

[repomd.txt](https://github.com/PulpQE/pulp-smash/files/148384/repomd.txt)

**Comment by mhrivnak** [comment]
I agree that we aren't making that guarantee yet, although it's a reasonable behavior to consider for the future.

**Comment by bmbouter** [comment]
I was told that we already had a behavior which performed a no-op if no units were modified since the `last_published` time. It seems we don't do that. Given that I need to file an issue on it.

**Comment by mhrivnak** [comment]
Sync is mostly a no-op if the remote repomd.xml's ``revision`` hasn't changed. Maybe that's what you're thinking of?

Publish will do very little if no content has changed, but it does still re-generate repomd.xml at a minimum.

**Comment by midnightercz** [comment]
@pcreech can you find out why was open-size of files changed?

**Comment by bmbouter** [comment]
Here is the story I wrote to go with this pulp-smash issue.

https://pulp.plan.io/issues/1724

**Comment by pcreech** [comment]
@midnightercz https://pulp.plan.io/issues/1725
