### ISSUE TITLE
Repository create and sync with --retain-old-content

### ISSUE THREAD

**Issue by ipanova** [PulpQE/pulp-smash#128]
Test to verify that repositories can be created and synced when using --retain-old-content. Assert that the --retain-old-content is functioning as expected.
https://pulp.plan.io/issues/1624

**Comment by preethit** [comment]
This issue is written here
https://github.com/PulpQE/pulp-smash/issues/95

**Comment by ipanova** [comment]
ahh sorry @preethit i did not notice, thanks!
