### ISSUE TITLE
Allow user to select configuration file

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-smash#13]
Pulp Smash's configuration file does not live with the source code itself. This has the advantage that Pulp Smash can be installed in one of many ways, yet the test suite can still be called in an indentical manner. It doesn't matter whether you:

* Install system-wide by executing `sudo pip install pulp_smash` or `sudo python setup.py install`
* Install on a per-user basis with `python setup.py install --user`
* Install into a virtualenv
* Run directly from source code

In all of these cases, you can execute the exact same command to run the test suite: `python -m unittest discover pulp_smash.tests`. And in all of these cases, the same config file can be used. There's no need to do something crazy like `sudo vim /usr/lib/python3.5/site-packages/pulp_smash/settings.json`!

There's one down-side to the current approach, though: it's hard to work with multiple configuration files. Imagine that a user creates two virtualenvs, installs Pulp Smash into each, and then wants to run Pulp Smash from both locations. How can the user make the two Pulp Smash installations use a different configuration file? Right now, it's impossible to do without resorting to something like this:

```sh
vim ~/tmp/settings.json
XDG_CONFIG_DIRS='~/tmp/' python -m unittest2 discover pulp_smash.tests
```

And that *works*, but gosh darn it's kinda terrible.

Let's add proper support for multiple configuration files. The end goal is the ability to execute commands like this:

```sh
python -m pulp_smash run --config ~/tmp/settings.json
python -m pulp_smash run --config pulp_servers.json
python -m pulp_smash run --config pulp_nodes.json
```

The first command would make Pulp Smash use `~/tmp/settings.json`. The second and third commands would make Pulp Smash search through the `$XDG_CONFIG_DIRS` for files named `pulp_servers.json` and `pulp_nodes.json`, respectively. If this procedure sound confusing, just think of how the shell executes commands. If you type `/usr/bin/df`, the shell executes `/usr/bin/df`. If you type `df`, the shell searches through each path in `$PATH` and uses the first executable named `df` it finds.

All this assumes that the test suite can be run by executing `python -m pulp_smash run`. That's a whole 'nuther issue.

**Comment by Ichimonji10** [comment]
@peterlacko

**Comment by elyezer** [comment]
Will the config file be searched on the current working directory? What is the default set of paths that it will walk in order to find the config file?

**Comment by Ichimonji10** [comment]
@elyezer The following set of locations is searcheddirectories is walked in order to find the config file:

1. `$XDG_CONFIG_HOME/pulp_smash/settings.json` (`$XDG_CONFIG_HOME` defaults to `$HOME/.config`.)
2. For each directory in `$XDG_CONFIG_DIRS`, `…/pulp_smash/settings.json` (`$XDG_CONFIG_DIRS` defaults to `/etc/xdg`.)

See: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by Ichimonji10** [comment]
One solution is to respect environment variables. For example:

```sh
PULP_SMASH_CONFIG='settings2.json' python -m unittest2 discover pulp_smash.tests
```

**Comment by peterlacko** [comment]
@Ichimonji10 What about joining it all together, ie. looking for config file in following order:
1. check if `--config` was set, as in [your first comment](https://github.com/PulpQE/pulp-smash/issues/13#issue-111223811), if not
2. check env for `PULP_SMASH_CONFIG`, like you [proposed above](https://github.com/PulpQE/pulp-smash/issues/13#issuecomment-149548533), if also not set
3. look for default config file in `XDG_CONFIG_HOME` and `XDG_CONFIG_DIRS`

**Comment by Ichimonji10** [comment]
@peterlacko That would work. But all of the solutions proposed so far (including my own propositions!) have bothered me. What I'm aiming for is an orthogonal solution. As things stand now, you can place configuration files in a system-wide location (`/etc/xdg`), a per-user location (`~/.config`) and in a custom location, and these three options serve three different use cases. In addition, users can use a variety of test runners, including unittest2, nose, nose2 and py.test. I'd like to be able to serve all of these use cases with a single common solution.

If I allow the user to specify an absolute path to a configuration file, I'm making life harder to folks who are taking advantage of the XDG standard. And if I use the `--config` approach as in my first comment, then I'm shutting out users who'd like to use an alternate test runner.

I think a good solution is to let the user specify a file name via an environment variable, like so:

```sh
$ vi ~/.config/pulp_smash/settings2.json
$ PULP_SMASH_CONFIG_FILE=settings2.json \
> python -m unittest2 discover pulp_smash.tests
```

This is technically simple to accomplish, reasonably simple in practice, respects users who take advantage of the XDG standard to place their configuration files in unexpected and weird places, and works no matter which test runner is used.

**Comment by elyezer** [comment]
Completely agree on the last @Ichimonji10's comment.
