### ISSUE TITLE
Test orphan remove

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#134]
- [x] Remove all the orphaned contents
- [ ] Remove orphaned content by type

1. Create a repository
2. Sync a repository
3. Delete  the repository
4. List the orphaned content
5. Remove orphaned content
     a.Remove the orphaned content by type
     b. Remove all the orphaned content

**Comment by asmacdo** [comment]
When confirming that orphans were removed, listing orphans is not enough. We should also check that the content was removed. https://pulp.plan.io/issues/1238

**Comment by asmacdo** [comment]
I vote this is high priority because I feel like we have seen bugs here more than once.

**Comment by asmacdo** [comment]
Needs to be updated to include all the cases here:
https://github.com/RedHatQE/pulp-automation/blob/master/tests/general_tests/test_10_orphans.py
