### ISSUE TITLE
Improve priority system for issues

### ISSUE THREAD

**Issue by asmacdo** [PulpQE/pulp-smash#135]
Right now, we have the `High Priority` label. The issue is that whenever a regression is found, an issue is created and given high priority, which could slow down our progress towards increasing coverage. 

Some possibilities would be to create multiple tracks like `regressions` and `coverage` labels, or if it would be better to create `medium priority` and `low priority labels`.

**Comment by omaciel** [comment]
@asmacdo I went ahead and created two new labels: 
* `medium priority`
* `low priority labels`

We can continue this discussion if you feel that these labels don't quite provide the level of information you want to convey.

**Comment by asmacdo** [comment]
@omaciel thats probably fine, lets keep an eye on it, and if we notice a problem we can reopen.
