### ISSUE TITLE
Test the full end-to-end operation of syncing a Docker container and running it in Docker

### ISSUE THREAD

**Issue by bowlofeggs** [PulpQE/pulp-smash#136]
We should write a test that tests the full end-to-end story of syncing down a Docker container, publishing it, Crane picking up the publish, the Docker client pulling it from Crane, and then running something in it to prove that it works. Here's a possible example:

0) Sync busybox.
1) Publish busybox.
2) Wait for Crane to notice busybox (it polls its data folder on some period.)
3) Use the docker client to run some command from the busybox image and assert that the command works correctly. Something simple like `echo "hello world"` would probably do, and we could assert that hello world was printed. This will make sure that nothing in the pipeline corrupted the image.

**Comment by preethit** [comment]
@Ichimonji10 Since you have recently did a docker tests refactor, can we close this one?

**Comment by Ichimonji10** [comment]
No. The docker client isn't currently being installed on any of our test systems, and it's not being used for any tests.
