### ISSUE TITLE
Create and document installable pulp-smash script

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-smash#14]
Pulp Smash does not and never will install executable scripts into system-wide locations. That's something for either a package manager or a system administrator to do. That said, there's nothing wrong with providing shell scripts for their use!

Let's create a shell script. It can look like this:

``` sh
#!/usr/bin/env sh
python -m pulp_smash "$@"
```

Let's call this script `pulp-smash`, make it executable, place it somewhere in the `docs` directory and include the script in the documentation. The documentation should note that this script can be copied to `/usr/local/bin/pulp-smash`.

By way of example, consider [this directory](https://github.com/SatelliteQE/nailgun/tree/master/docs). Some shell scripts are placed directly in that file. The scripts are included into the documentation using the `.. literalinclude::` reST directive. See an examle [here](https://raw.githubusercontent.com/SatelliteQE/nailgun/master/docs/examples.rst).

**Comment by elyezer** [comment]
Python setup utilities offers a way to provide a executable script and also some entry points. I can't remember from the top of my head if that will help in some way here, but have it been analyzed?

**Comment by Ichimonji10** [comment]
I've not done that. It's definitely worth looking in to. Thanks for the reminder.

**Comment by Ichimonji10** [comment]
@elyezer has basically done this by creating the `pulp-smash` script. See: #653. Thank you!
