### ISSUE TITLE
Test pulp-admin content source

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#141]
http://docs.pulpproject.org/user-guide/content-sources.html

$ pulp-admin content sources
Usage: pulp-admin [SUB_SECTION, ..] COMMAND
Description: manage content sources

Available Commands:
  list    - list sources
  refresh - refresh sources

https://pulp.plan.io/issues/1692

**Comment by elyezer** [comment]
PR #305 is merged. This can be closed.
