### ISSUE TITLE
Test Tasks

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#142]
http://pulp.readthedocs.org/en/latest/user-guide/admin-client/tasks.html
- [ ] cancel
- [ ] details
- [ ] list
- [ ] purge - https://github.com/PulpQE/pulp-smash/issues/108

Related redmine
https://pulp.plan.io/issues/1483
https://pulp.plan.io/issues/1664

pulp-admin tasks
Usage: pulp-admin [SUB_SECTION, ..] COMMAND
Description: list and cancel server-side tasks

Available Commands:
  cancel  - cancel one or more tasks
  details - displays more detailed information about a specific task
  list    - lists tasks queued (waiting) or running on the server
  purge   - purge tasks in one or more completed states

**Comment by shubham90** [comment]
I can work on this one. Can you assign this to me please?

**Comment by preethit** [comment]
@shubham90 done

**Comment by shubham90** [comment]
@preethit Thanks!

**Comment by shubham90** [comment]
I am removing my assignment from this test as I am going to spend more of my time in RHUI.

**Comment by preethit** [comment]
@shubham90 I have unassigned you from this issue. Thanks

**Comment by kersommoura** [comment]
See also : [Closes 108](https://github.com/PulpQE/pulp-smash/commit/e2da2d3c02b31686bd21527daed476208a2fae53)

**Comment by kersommoura** [comment]
This issue was closed: [Closes 108](https://github.com/PulpQE/pulp-smash/commit/e2da2d3c02b31686bd21527daed476208a2fae53)
