### ISSUE TITLE
pulp_smash.selectors is conflicting with Python 3's selectors module with unittest2

### ISSUE THREAD

**Issue by rbarlow** [PulpQE/pulp-smash#146]
I've been attempting to run pulp-smash with Python 3.4 in the Pulp development environment, with this pull request:

https://github.com/pulp/pulp/pull/2460

Unfortunately, this happens:

```
$ time psmash
~ ~
flake8 . --ignore D203
pylint -j 4 --reports=n --ignore-imports=y --disable=I \
        docs/conf.py \
        setup.py \
        tests \
        pulp_smash/__init__.py \
        pulp_smash/__main__.py \
        pulp_smash/api.py \
        pulp_smash/cli.py \
        pulp_smash/config.py \
        pulp_smash/constants.py \
        pulp_smash/exceptions.py \
        pulp_smash/selectors.py \
        pulp_smash/utils.py
No config file found, using default configuration
pylint -j 4 --reports=n --disable=I,duplicate-code pulp_smash/tests/
No config file found, using default configuration
python -m unittest discover --start-directory tests --top-level-directory .
.........................................................
----------------------------------------------------------------------
Ran 57 tests in 0.115s

OK
E
======================================================================
ERROR: tests (unittest2.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
ImportError: Failed to import test module: tests
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/pulp-smash/lib/python3.4/site-packages/unittest2/loader.py", line 490, in _find_test_path
    package = self._get_module_from_name(name)
  File "/home/vagrant/.virtualenvs/pulp-smash/lib/python3.4/site-packages/unittest2/loader.py", line 395, in _get_module_from_name
    __import__(name)
  File "/home/vagrant/devel/pulp-smash/pulp_smash/tests/__init__.py", line 41, in <module>
    import requests
  File "/home/vagrant/.virtualenvs/pulp-smash/lib/python3.4/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/vagrant/.virtualenvs/pulp-smash/lib/python3.4/site-packages/requests/utils.py", line 17, in <module>
    import platform
  File "/usr/lib64/python3.4/platform.py", line 115, in <module>
    import sys, os, re, subprocess
  File "/usr/lib64/python3.4/subprocess.py", line 424, in <module>
    _PopenSelector = selectors.SelectSelector
AttributeError: 'module' object has no attribute 'SelectSelector'


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
~

real    0m29.780s
user    0m52.626s
sys     0m1.533s
```

This is because Python 3 has a module called called selectors in the standard library, and pulp_smash.selectors is getting imported instead. This may happen due to the test runner altering the PYTHONPATH, but I have not confirmed that hypothesis.

Thanks to @seandst for assisting in finding the problem!

**Comment by rbarlow** [comment]
For the record, this error happens when the test suite is run with unittest2, but does not happen when run with py.test.

**Comment by Ichimonji10** [comment]
I use both py.test and unittest2 on Python 3.5. The bug described here may be specific to unittest2 on Python 3.4 and older.

**Comment by Ichimonji10** [comment]
I attempted to reproduce this issue on a Fedora 23 system with Python 3.4 with the following procedure:

```sh
python3 -m venv env
source env/bin/activate
pip install --upgrade pip
pip install pulp-smash
python -m unittest2 pulp_smash.tests.platform.api_v2.test_login
python -m unittest2 discover pulp_smash.tests
```

I did not encounter the error described by this bug.

@rbarlow, you mention that:

> this error happens when the test suite is run with unittest2, but does not happen when run with py.test.

Are you sure that unittest2 is used as the test runner? I notice that the `psmash` command executes `python -m unittest`, not `python -m unittest2`.

**Comment by Ichimonji10** [comment]
Interestingly, I just ran the entire test suite with `python -m unittest` with no problems either.

**Comment by rbarlow** [comment]
psmash uses py.test:

https://github.com/pulp/pulp/blob/38adb192add8cd0b66940a09a8183921cace61da/playpen/ansible/roles/dev/files/bashrc#L143

**Comment by Ichimonji10** [comment]
OK. I'm looking at the copy-paste output in the original comment in this thread.

**Comment by Ichimonji10** [comment]
I can run the full Pulp Smash test suite on Fedora 22 (Python 3.4.2), Fedora 23 (Python 3.4.3) and my personal system (Python 3.5.1), and am unable to reproduce this issue. Pending further information to the contrary, I will assume that the issue lies with the Pulp development environment mentioned in the opening comment. Please re-open if there's some evidence that this issue lies with Pulp Smash.
