### ISSUE TITLE
Create Issues for Porting Tests

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-smash#15]
<p><ins>This issue was originally entitled "Port Tests from Pulp Automation," and what follows is the original issue description. See https://github.com/PulpQE/pulp-smash/issues/15#issuecomment-189412295 for updated thoughts.</ins></p>

Let's port tests from Pulp Automation to Pulp Smash.

Not all tests can be ported right away. Right now, only tests that target a single Pulp server can be easily ported over. This is because all tests are lumped together (see #11) and the configuration handling is ham-fisted. That said, let's start porting over what we can! This is a brand new framework, and we'll iron out these issues as we go.

What tests need to be ported over? I'm a little unclear on that. This is my best guess, though:
- [ ] `tests/consumer_agent_tests/test_02_distributor_with_bindings.py`
- [ ] `tests/consumer_agent_tests/test_02_repo_with_bindings.py`
- [ ] `tests/consumer_agent_tests/test_09_consumer_auth.py`
- [ ] `tests/consumer_agent_tests/test_09_consumer_bz1080462.py`
- [ ] `tests/consumer_agent_tests/test_09_consumer_content_management.py`
- [ ] `tests/consumer_agent_tests/test_09_consumer_heavy_load_bz1121102.py`
- [ ] `tests/consumer_agent_tests/test_09_consumer.py`
- [ ] `tests/consumer_agent_tests/test_09_consumer_scheduled_content_install.py`
- [ ] `tests/consumer_agent_tests/test_09_consumer_scheduled_content_uninstall.py`
- [ ] `tests/consumer_agent_tests/test_09_consumer_scheduled_content_update.py`
- [ ] `tests/consumer_agent_tests/test_14_consumer_group_binding.py`
- [ ] `tests/consumer_agent_tests/test_14_consumer_group_content.py`
- [ ] `tests/consumer_agent_tests/test_14_consumer_group.py`
- [x] `tests/general_tests/test_01_log_in.py`
- [x] `tests/general_tests/test_02_repo_applicability.py`
- [x] `tests/general_tests/test_02_repo_cud.py`
- [x] `tests/general_tests/test_02_repo_importer_distributor.py`
- [x] `tests/general_tests/test_02_rpm_repo.py` (This one is a **priority**.)
- [ ] `tests/general_tests/test_03_race.py`
- [x] `tests/general_tests/test_04_repo_group_distributors.py`
- [x] `tests/general_tests/test_04_repo_group_publish.py`
- [x] `tests/general_tests/test_04_repo_group.py`
- [x] `tests/general_tests/test_05_user.py`
- [ ] `tests/general_tests/test_06_roles.py`
- [ ] `tests/general_tests/test_07_user_permissions.py`
- [ ] `tests/general_tests/test_08_role_permissions.py`
- [x] `tests/general_tests/test_10_orphans.py`
- [ ] `tests/general_tests/test_11_puppet_modules_repo.py`
- [ ] `tests/general_tests/test_12_puppet_repo_and_modules_search.py`
- [ ] `tests/general_tests/test_12_puppet_repo_orphans_and_copy.py`
- [ ] `tests/general_tests/test_12_yum_repo_copy.py`
- [ ] `tests/general_tests/test_13_cli_consumer.py`
- [x] `tests/general_tests/test_15_iso_repo.py`
- [x] `tests/general_tests/test_16_unit_search.py`
- [ ] `tests/general_tests/test_17_iso_repo_orphans_and_copy.py`
- [ ] `tests/general_tests/test_18_status.py`
- [x] `tests/general_tests/test_19_scheduled_publish.py`
- [x] `tests/general_tests/test_19_scheduled_sync.py`
- [x] `tests/general_tests/test_20_docker_repo_cud.py`
- [x] `tests/general_tests/test_21_upload_cud.py`
- [ ] `tests/general_tests/test_22_download_content_with_dnf.py`
- [ ] `tests/general_tests/test_23_event_listener.py`
- [ ] `tests/nodes/test_01_cud.py`
- [ ] `tests/regression_tests/test_01_rpm_repo_copy.py`
- [ ] `tests/regression_tests/test_01_rpm_repo_with_feed.py`
- [ ] `tests/regression_tests/test_01_rpm_repo_without_feed.py`
- [ ] `tests/regression_tests/test_02_iso_repo.py`
- [ ] `tests/regression_tests/test_03_package_group.py`
- [ ] `tests/regression_tests/test_04_package_category.py`

Here's how I generated the list:

``` sh
find tests -type f -name 'test*' | sort | awk '{print "* [ ] `" $0 "`"}' | xclip -sel clip
```

**Comment by Ichimonji10** [comment]
I've just finished porting over a third set of tests: [`pulp_smash.tests.platform.api_v2.test_user`](https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/tests/platform/api_v2/test_user.py). This test module is significantly more complex than the two test modules previously ported over. If you're thinking of porting over some tests yourself, or if you're thinking of writing some new tests, consider examining that test module first. It may be of use when deciding how to lay out your own tests.

**Comment by preethit** [comment]
For the repo tests can we make the feed configurable? There are have been many cases where  repo sync from one passes while another fails.

**Comment by Ichimonji10** [comment]
@preethit If there's something that's a known trigger for a bug, then we should definitely make sure Pulp Smash can test it. Can you explain what you mean by a "feed"? Do you mean that you'd like to make the content source for a repository configurable?

**Comment by preethit** [comment]
yes.  content source for the repo is what I meant.

**Comment by asmacdo** [comment]
@Ichimonji10, @omaciel, how would you feel about changing this issue to "Create issues for tests to be Ported"? 

Creating an issue for each test case to be ported would be a substantial amount of work, but it will set us up to be much better organized. This will allow an individual case to be prioritized separately, and assigned to someone to prevent duplicate work. It will also prevent duplicate issues from being filed.

**Comment by preethit** [comment]
@asmacdo This issue was created as a starting place for pulp-smash. So I think changing the issue to what you mentioned should work just fine.

**Comment by Ichimonji10** [comment]
:+1:

**Comment by rochacbruno** [comment]
@kersommoura is this one done? shoudl we create individual cards on plan io?
