### ISSUE TITLE
Port repository CUD cases

### ISSUE THREAD

**Issue by asmacdo** [PulpQE/pulp-smash#155]
Some of these tests already exist. At the time of creating this issue, the existing smash tests  are located here: https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/tests/platform/api_v2/test_repository.py

The tests to be ported are here: https://github.com/RedHatQE/pulp-automation/blob/master/tests/general_tests/test_02_repo_cud.py

Primarily, this module includes tests for correctly handling failure scenarios.

**Comment by preethit** [comment]
Pulp smash has tests to cover this. So closing.
