### ISSUE TITLE
Port repo group crud tests

### ISSUE THREAD

**Issue by asmacdo** [PulpQE/pulp-smash#159]
Old tests:
https://github.com/RedHatQE/pulp-automation/blob/master/tests/general_tests/test_04_repo_group.py

Completion of this story will also require either porting the repo group distributors tests or creating a separate issue to track them:
https://github.com/RedHatQE/pulp-automation/blob/master/tests/general_tests/test_04_repo_group_distributors.py

As of now, there are not any repo group tests. Recommend medium priority because repository groups are not used very much. This means that though a break in this code is less of a big deal, it is more likely to go unnoticed.

**Comment by kersommoura** [comment]
There is another test related to this issue. See: [RepoGroupExportChecksumTypeTestCase](https://github.com/PulpQE/pulp-smash/blob/d463d7ac8b9c6bca2753c3e059a22529ac9828df/pulp_smash/tests/pulp2/rpm/api_v2/test_export.py#L347).
This test does the following: `Publish a repository group choosing the distributor checksum type.`

**Comment by kersommoura** [comment]
Based on the coverage already in place for this issue, I will close it. In case of need, feel free to re-open it.
