### ISSUE TITLE
Test pulp can sync drpm, srpm

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#161]
- Test Repository Sync success with 
    - [ ] drpm
    - [ ] srpm

Pulp-admin rpm repo create --repo-id drpm --feed https://repos.fedorapeople.org/repos/pulp/pulp/demo_repos/test_drpm_repo/
pulp-admin rpm repo sync run --repo-id drpm

Pulp-admin rpm repo create --repo-id srpm --feed  https://repos.fedorapeople.org/repos/pulp/pulp/demo_repos/test_srpm_repo/

pulp-admin rpm repo sync run --repo-id srpm

**Comment by elyezer** [comment]
:tada:
