### ISSUE TITLE
Test packages in errata exist in repo

### ISSUE THREAD

**Issue by seandst** [PulpQE/pulp-smash#163]
When syncing repos with errata, pulp merges the errata found in that repo with an existing errata unit if errata with the same ID is already known to pulp. When a repo containing errata is published, pulp should then only include packages contained in that repo in the published updateinfo XML file. This makes for complex integration, including multiple repositories with multiple errata and multiple packages.

The method I've used to manually test this scenario is to sync two repos that contain errata: the RHEL 6 and RHEL 7 main repositories from the CDN. Then, publish the RHEL 7 repo.

If pulp is broken, both el6 and el7 packages will be seen in the updateinfo XML because pulp did not filter out packages unrelated to the RHEL 7 repo.
If pulp is working properly, only el7 packages will be seen in the updateinfo XML, because pulp _did_ filter out packages unrelated to the RHEL 7 repo.

This scenario can be reproduced with far less data using testing repos that meet the following criteria:
- There must be at least two repositories to sync from.
- Each repository must contain at least one errata in its updateinfo XML metadata.
- The ID(s) of the errata in each repo must be the same, so that Pulp will combine them into a single errata unit.
- The packages listed in the errata in each repo must _not_ be the same, making it possible to verify the updateinfo XML contents after publishing.
- The packages listed in the errata in each repo must exist in that repo, so that Pulp has the correct unit/repository associations which will be inspected when writing the updateinfo XML.

**Comment by goosemania** [comment]
I suggest to add one more criteria to the testing repos:
-  name of the collections in the same erratum in different repositories should be the same.

This is needed to test [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1302663) which was mentioned [here](https://pulp.plan.io/issues/1783).
