### ISSUE TITLE
Printing all requests in extended verbosity mode

### ISSUE THREAD

**Issue by peterlacko** [PulpQE/pulp-smash#17]
When test fails, sometimes it can be useful to make requests to server manually. What about printing all requests that test makes to pulp server(s) (also in setup and teardown methods), in extended verbosity mode, possibly also formatted in way to easily make copy-paste for curl (or some similar tool)?

**Comment by Ichimonji10** [comment]
Makes sense. We could do some logging set-up in `pulp_smash.tests.__init__`.

**Comment by elyezer** [comment]
Test runners like nose offers a way to capture logging, in Robottelo we select just robottelo and nailgun logs to be captured. I think this can may be done by using nose with an entry on the Makefile. It is not flexible like being able to use unittest, nose, nose2 or py.test but could be a make target to be used by the jenkins jobs to make easy to debug what happened.
