### ISSUE TITLE
Improvements to test skipping logic

### ISSUE THREAD

**Issue by asmacdo** [PulpQE/pulp-smash#173]
Redmine contains a "target platform release" field. Smash's `bug_is_untestable` logic should be aware of this field so bugs that have been moved to `ON_QA` or `VERFIED` are not run on older versions of Pulp.

An additional improvement in this area would be to get a dump of all bugs that are now testable and their target platform release to avoid making another http request to redmine for each bug.

There are some potential issues with this method. First are bugs that are fixed in an older Z release. For example, a bug that is fixed in 2.7.3 and 2.8.1. For the example lets say that 2.7.3 is released before 2.8.1. We then know that bugfixes in 2.7.3 are also available in 2.8.1. We should be able to accurately determine whether a bugfix is present by knowing the target release and the order of the releases. 

A second option would be to use `--contains` on the commit. I think that this would require less logic and could potentially be more accurate (and would work for backports), but would require very strict book keeping in redmine, specifically making sure that every bug has a commit. We would need to explore what is necessary when there are more than 1 commit with this model.

**Comment by bmbouter** [comment]
Given that every bug fix is merged forward the order releases are created shouldn't matter. Even if a bug was fixed in 2.7.2 and 2.7.2 was not released I expect the test to run in 2.8.0. This is also true if 2.7.2 is released after 2.8.0 is released. We shouldn't ever have two active Z stream releases otherwise we'll have to do "diamond" merges which we don't want to do.

Let's not use --contains since rpm based installs aren't git-aware already. The method that uses the `Target Platform Release` I think will work just fine.

On IRC it was discussed that bugs should check-and-maybe-skip as described ^ using both a decorator and also a function that can tell you to skip or not. Skipping a whole test is great from a decorator, but to skip just a few assertions you would want a function you can use to tell you if you should skip or not.

**Comment by Ichimonji10** [comment]
See https://github.com/PulpQE/pulp-smash/compare/master...Ichimonji10:173 for a possible solution. Here's a copy of the commit message.

-----

Respect the target_platform_release bug field

Usage:

    >>> from packaging.version import Version
    >>> from pulp_smash.selectors import bug_is_testable
    >>> bug_is_testable(1743, Version('2.7.0'))
    False
    >>> bug_is_testable(1743, Version('2.7.99999'))
    False
    >>> bug_is_testable(1743, Version('2.8'))
    True
    >>> bug_is_testable(1743, Version('2.8.0'))
    True
    >>> bug_is_testable(1743, Version('2.8.0.0'))
    True
    >>> bug_is_testable(1743, Version('2.8.1'))
    True
    >>> bug_is_testable(1743, Version('3'))
    True

In a test method, usage would look like this:

    def test_some_bug(self):
        if bug_is_untestable(1743, self.cfg.version):
            self.skipTest('https://pulp.plan.io/issues/1743')
        …

The modified `bug_is_testable` method requires the "Target Platform Release" field to be a valid version number. If the version number is not present (it is an empty string for many bugs), an exception is raised. (The exception is awful. We should define a new custom exception and re-raise the bug with that exception.) For example:

    >>> from packaging.version import Version
    >>> from pulp_smash.selectors import bug_is_testable
    >>> bug_is_testable(1744, Version('3'))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "pulp_smash/selectors.py", line 112, in bug_is_testable
        bug = _get_bug(bug_id)
      File "pulp_smash/selectors.py", line 95, in _get_bug
        _get_target_platform_release(body),
      File "pulp_smash/selectors.py", line 57, in _get_target_platform_release
        return Version(custom_field['value'])
      File "/home/ichimonji10/.virtualenvs/pulp-smash2/lib/python2.7/site-packages/packaging/version.py", line 202, in __init__
        raise InvalidVersion("Invalid version: '{0}'".format(version))
    packaging.version.InvalidVersion: Invalid version: ''

This behaviour is questionable. We may want to have the function return `False` in cases where no target platform release is listed. This will have an unfortunate side-effect, though: should a bug be marked as fixed and no target platform release is listed, the test for that bug will just continue to skip.
