### ISSUE TITLE
Autogenerate API documentation stubs

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-smash#18]
The `docs/api` directory contains files such as `pulp_smash.config.rst` and `pulp_smash.tests.platform.api_v2.test_login.rst`. There's one `.rst` file for each documented Python module. This is a burden to maintain and error-prone, especially when you consider that each page of the API documentation has an identical layout. Let's use something like Sphinx's `sphinx-autogen` script to generate these files automatically. See: [`sphinx.ext.autosummary` – Generate autodoc summaries](sphinx-doc.org/ext/autosummary.html).

**Comment by elyezer** [comment]
:+1:
