### ISSUE TITLE
[RPM] Test the --checksum-type repository feature

### ISSUE THREAD

**Issue by bowlofeggs** [PulpQE/pulp-smash#183]
RPM repositories have a feature that allows the user to request a particular checksum type to be used during repository publish. Unfortunately, this feature has never worked consistently from release to release, which is why Pulp issue 1618 was filed:

https://pulp.plan.io/issues/1618

pulp-smash could perform the following tests:
1. Create a repository with the checksum type set to type A and a feed URL that uses checksum type B (for example, you could configure a Pulp repository to use sha1 but connect it to a feed that uses sha256). Sync and publish the repository. The resulting published primary.xml.gz file should contain a list of all the RPMs in the repository. Assert that all of these RPMs are listed with checksum type A and not checksum type B.
2. Create a repository with the checksum type set to type A, and another repository with a checksum type of B. Put units in repo A that have checksum type A. Copy some or all of those units to repo B and publish repo B. Ensure that the primary.xml.gz file contains checksum type B and not checksum type A.
3. Create a repository with the checksum type set to some value. Upload an RPM to that repository and publish. Ensure that the published data is correct.
4. Perform the above, and then create a second repository with a different checksum type. Upload that same RPM to the second repository and publish. Ensure that the second repository's published data uses the correct checksum type.

**Comment by Ichimonji10** [comment]
Implementing this test would let us cover https://pulp.plan.io/issues/1822

**Comment by Ichimonji10** [comment]
Tagging as "high priority" because this issue relates to Pulp 2.9.

**Comment by Ichimonji10** [comment]
Following some feedback from the Pulp developers, I'm dropping the priority of this issue.

**Comment by kersommoura** [comment]
There are several tests covering the aforementioned requirements.

See [test_unavailable_checksum](https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/tests/rpm/api_v2/test_unavailable_checksum.py)

See also [287](https://github.com/PulpQE/pulp-smash/issues/287)

See also [286](https://github.com/PulpQE/pulp-smash/issues/286)

See also [PR 708](https://github.com/PulpQE/pulp-smash/pull/708/files)

See also [PR 747](https://github.com/PulpQE/pulp-smash/pull/747/files)
