### ISSUE TITLE
ConnectionError was caused by "[Errno 2] No such file or directory- On-demand policy

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#189]
https://pulp.plan.io/issues/1771
1. Start or restart the pulp_streamer
2. Make a request directly to the streamer for a file that requires a client certificate: something like `http://127.0.0.1:8751/var/lib/pulp/content/units/rpm/hex[:2]/hex[2:]/filename.rpm`
   (`curl -O http://127.0.0.1:8751/var/lib/pulp/content/units/rpm/66/0e7bf17e1bd386dcd61759fd2822cb01ab396b13d69f33a3e6b5d67ce29ff6/389-ds-base-libs-1.2.10.2-15.el6.i686.rpm`)
3. Wait. The TCP socket needs to die. Give it 5-10 minutes.
4. Make a second request to the streamer (it can be for the exact same file). This will fail with "No such file or directory".

**Comment by Ichimonji10** [comment]
Tagging as "high priority" because this issue relates to Pulp 2.9.

**Comment by Ichimonji10** [comment]
Following some feedback from the Pulp developers, I'm dropping the priority of this issue.
