### ISSUE TITLE
Expand GET/POST search tests

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-smash#19]
Pulp supports searching via both GET and POST requests. When searching with a GET request, parameters should be passed in via the URL, and when searching with a POST request, parameters should be passed in the body of the request. (This is appropriate behaviour, by the way. Network intermediaries are at liberty to discard the body of any GET request.) Unfortunately, this makes Pulp's search facilities more complicated and, therefore, more prone to bugs.

Tests should be written that execute identical GET and POST searches and verify that the results are identical. Much of the searching code is very generic and applies no matter what kind of entity is being searched for. As a result, even adding a few tests should help immensely with preventing regressions.

Further documentation on the GET and POST search queries is available [here](https://pulp.readthedocs.org/en/latest/dev-guide/conventions/criteria.html#search-api).

**Comment by Ichimonji10** [comment]
I'd suggest adding tests in `pulp_smash.tests.platform.api_v2.test_search`.

**Comment by asmacdo** [comment]
While working in this area, I created this list of queries, (including the GET and POST equivalents) which should serve as a good base for these tests.

https://public.etherpad-mozilla.org/p/Pulp_Search_API_testing

**Comment by omaciel** [comment]
This is awesome @asmacdo , thank you! Will this etherpad be around for a while? Should we move that content here as a comment?

**Comment by asmacdo** [comment]
@omaciel sure, that might be simpler.

**Comment by asmacdo** [comment]
### Basic "it works":

GET:
`http --json -a admin:admin --verify=no GET 'https://localhost/pulp/api/v2/repositories/search/?filters={}`
POST:
`http --json -a admin:admin --verify=no POST 'https://localhost/pulp/api/v2/repositories/search/' criteria:='{"filters": {}}'`


###  Basic search by id:

GET:
`http --json -a admin:admin --verify=no GET 'https://localhost/pulp/api/v2/repositories/search/?filters={"id":"zoo"}'`

POST:
`http --json -a admin:admin --verify=no POST 'https://localhost/pulp/api/v2/repositories/search/' criteria:='{"filters": {"id": "zoo"}}'`


### Test that "options" arguments work:

GET:
`http --json -a admin:admin --verify=no GET 'https://localhost/pulp/api/v2/repositories/search/?filters={"id": "zoo"}&details=true'`

POST:
`http --json -a admin:admin --verify=no POST 'https://localhost/pulp/api/v2/repositories/search/' criteria:='{"filters": {"id": "zoo"}}' details=true`


### Test that field/fields work:

GET:
`http --json -a admin:admin --verify=no POST 'https://localhost/pulp/api/v2/repositories/search/' criteria:='{"filters": {"id": "zoo"}}' details=true`

POST:
`http --json -a admin:admin --verify=no GET 'https://localhost/pulp/api/v2/repositories/search/?filters={"id": "zoo"}&field=id'`


### Test limit:

GET:
`http --json -a admin:admin --verify=no GET 'https://localhost/pulp/api/v2/repositories/search/?filters={}&limit=1'`

POST:
`http --json -a admin:admin --verify=no POST 'https://localhost/pulp/api/v2/repositories/search/' criteria:='{"filters": {}, "limit": 1}'`


### Test Sort:

GET:
`http --json -a admin:admin --verify=no GET 'https://localhost/pulp/api/v2/repositories/search/?filters={}&sort=[["id", "ascending"]]'`

POST:
`http --json -a admin:admin --verify=no POST 'https://localhost/pulp/api/v2/repositories/search/' criteria:='{"filters": {}, "sort": [["id", "descending"]]}'`


### Skip:

GET:
`http --json -a admin:admin --verify=no GET 'https://localhost/pulp/api/v2/repositories/search/?filters={}&sort=[["id", "ascending"]]&skip=1'`

POST:
`http --json -a admin:admin --verify=no POST 'https://localhost/pulp/api/v2/repositories/search/' criteria:='{"filters": {}, "sort": [["id", "descending"]], "skip": "1"}'`

**Comment by Ichimonji10** [comment]
@asmacdo No repository tests are in place yet and I want to get search-related tests ASAP, so I propose writing up some tests for users. What do you think of the following proposal? Do I have the POST search syntax right?

```python
# All searches should be executed as both POST and GET requests. Search outputs
# should match. The tear down process for all tests is to destroy created
# users. This process is not set in stone. See:
# https://github.com/PulpQE/pulp-smash/issues/5
#
# Dependency tree::
#
# SearchTestCase
# |-- SearchDetailsTestCase
# |-- SearchSortTestCase
# |-- SearchFieldTestCase
# |-- SearchFieldsTestCase
# `-- SearchIdTestCase
#     `-- SearchIdsTestCase
#         |-- SearchSkipTestCase
#         `-- SearchLimitTestCase

# SearchTestCase: Ask for users.
# Set up: Create one user.
{'criteria': {}}
{'criteria': {'filters': {}}}

# SearchDetailsTestCase: Ask that search results contain details.
# Set up: Create one user.
{'criteria': {}, 'details': true}

# SearchSortTestCase: Ask that search results be sorted.
# Set up: Create two users.
{'criteria': {}, 'sort': [['id', 'descending']]}

# SearchFieldTestCase: Ask that search results only contain a specified field.
# Set up: Create one user.
{'criteria': {}, 'field': 'id'}

# SearchFieldsTestCase: Ask that search results only contain specified fields.
# Set up: Create one user with login, roles and name attributes.
{'criteria': {}, 'fields': ['login', 'roles']}

# SearchIdTestCase: Ask for a user with a specific ID.
# Set up: Create two users.
{'criteria': {'filters': {'id': '…'}}}

# SearchIdsTestCase: Ask for users with one of several IDs.
# Set up: Create three users.
{'criteria': {'filters': {'id': {'$in': [id1, id2]}}}}

# SearchSkipTestCase: Ask for search results to be skipped.
# Set up: Create two users.
{'criteria': {'filters': {'id': {'$in': [id1, id2]}}}, 'skip': 1}

# SearchLimitTestCase: Ask for a limited number of results to be returned.
# Set up: Create two users.
{'criteria': {'filters': {'id': {'$in': [id1, id2]}}}, 'limit': 1}
```

**Comment by asmacdo** [comment]
@Ichimonji10, this looks good, I did notice a couple things. `details` is the only field that should not be a part of the criteria, there are a couple of examples that have `fields` outside of criteria. Additionally, the `field` field is only available on GET searches, `fields` is correct for POST.

Another thing you should be aware of is that `fields` does not work quite as expected at the moment. https://pulp.plan.io/issues/1332

**Comment by Ichimonji10** [comment]
@asmacdo It the updated proposal correct?

**Comment by asmacdo** [comment]
`s/{'criteria': {'field': 'id'}}/{'criteria': {'fields': 'id'}}/`

**Comment by asmacdo** [comment]
@Ichimonji10 other than that, it looks good to me

**Comment by Ichimonji10** [comment]
See: https://github.com/PulpQE/pulp-smash/compare/master...Ichimonji10:test-search

**Comment by asmacdo** [comment]
For `FieldsTestCase` the GET search can pass multiple values to `field` and that should be equivalent to the POST `fields`.  

Example:
`.../users/search/?field=login&field=roles`

**Comment by Ichimonji10** [comment]
@asmacdo Ahhh, gotcha. Thank you.

**Comment by elyezer** [comment]
:+1:
