### ISSUE TITLE
Retain old repodata on re-publish

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#190]
Test to make sure that old repodata is retained until the time specified
1. Create a repository and set its `metadata_retention_days` to a non-zero value. (The default is zero.)
2. Sync the repository.
3. Sync the repository again. Ensure repository metadata hasn't changed.

https://pulp.plan.io/issues/1684

**Comment by danuzclaudes** [comment]
According to @preethit, this story is still not been added to a sprint.

**Comment by Ichimonji10** [comment]
@preethit Do you think this should be removed from @danuzclaudes list of tasks? If so, feel free to take it off.

**Comment by preethit** [comment]
@danuzclaudes @Ichimonji10 Yes that can be removed as that has not been implemented yet. Will do that now.

**Comment by Ichimonji10** [comment]
I've dropped this issue from the [Chongrui - Summer Internship](https://github.com/PulpQE/pulp-smash/milestones/Chongrui%20-%20Summer%20Internship) milestone.
