### ISSUE TITLE
Add support for testing a Pulp agent

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-smash#224]
An "agent" can be installed on a system. This agent allows Pulp to send commands to that system. See: http://pulp.readthedocs.io/en/latest/dev-guide/architecture.html We should be able to test interactions between a consumer (a system with an agent) and a Pulp server.

Let's build out support for this scenario. One option is to change how we use the `settings.json` file. (The file is badly named. It should be named `server_configs.json`, or something like that.) Currently, that file may have a single "default" section. We can change the semantics assigned to that file and expect at least a "server" section, corresponding to a Pulp server, and optionally allow for the presence of a "consumer" section, corresponding to a system with the Pulp agent installed. Modules could then choose whether or not to run based on the presence or absence of this config file section. Here's a verbose example of what could be in a test module:

```python
def setUpModule():  # pylint:disable=invalid-name
    """Skip tests if there is no system running the Pulp agent."""
    set_up_module()
    if 'agent' not in config.ServerConfig().sections():
        raise unittest2.SkipTest(
            'This module requires a system running the Pulp agent.'
        )
```

Also see: https://github.com/PulpQE/pulp-smash/compare/master...Ichimonji10:test-agent

**Comment by elyezer** [comment]
Should we care about having more than one agent? If yes then we should consider expecting a list of agents or maybe make the settings smart and expect either a list or a dict for multiple and single scenario respectively.

**Comment by Ichimonji10** [comment]
Yes, I did consider that possibility. It may be useful to be able to work with more than one agent, and that possibility is left open. That said, making `pulp_smash.settings` smart enough to deal with lists of configurations is a change in semantics that, I think, will introduce some complications.

Code that currently interacts with the `settings.json` file assumes that the file uses a simple labeling system. Want the system running Pulp? Call `ServerConfig().read('pulp')`. Want a system running the Pulp agent? Call `ServerConfig().read('pulp agent')`. What if the requested system isn't available? A `ConfigFileSectionNotFoundError` is raised. Easy enough.

Imagine we want to conditionally run some tests based on how many Pulp agents are available. If we require that a section named `pulp_agents` be present in the config file:

```python
# Require at least one agent
try:
    pulp_agents = ServerConfig().read('pulp agents')
except exceptions.ConfigFileSectionNotFoundError:
    raise unittest2.SkipTest()
if len(pulp_agents) == 0:
    raise unittest2.SkipTest()
```

A bit verbose, but doable. But what happens when we go to save a config?

```python
cfg.save('pulp')  # adds a new entry called "pulp"
cfg.save('my backup')  # adds a new entry called "my backup"
cfg.save('pulp agents')  # overwrites list of pulp agents?
```

Uh oh. We have an issue with semantics here. Do we need to add new methods?

```python
# Append to the list of configs named "pulp agents". Create a new list if no list
# is present, or overwrite the existing server config if one is present.
cfg.append('pulp agents')
# Remove item from a list of configs. Raise an exception if "pulp agents"
# is not present, or is present but not a list, or if no items are left.
cfg.pop('pulp agents')
```

We're greatly expanding how complicated `ServerConfig` is, and the semantics a user needs to be aware of are correspondingly becoming more complicated.

Another solution to this issue is to just state that Pulp Smash expects certain labels to be present, and widely advertise its expectations. For example, here's what I'm proposing right now:

* A section named "pulp" must be present.
* A section named "pulp agent" may be present. If present, tests that require a single agent are run.

If we want multiple Pulp agents in the future, we could state that Pulp Smash expects something else:

* A section named "pulp" must be present.
* Sections named "pulp agent NNN" may be present, where NNN is a decimal number. Tests that require multiple Pulp agents will run if an appropriate number of agents are listed.

Using a labeling system is dumb in some ways. But it has the compelling advantage of letting us avoid complications, both in semantics and implementation.

**Comment by elyezer** [comment]
@Ichimonji10 it makes completely sense. Thanks for explaining how the server config works.

**Comment by Ichimonji10** [comment]
@elyezer I'm glad it makes sense. I hope it's also a good direction for development. :smile:

**Comment by elyezer** [comment]
We still have the option to rethink this when more than one agent is needed, until then we are good with the current approach.

**Comment by Ichimonji10** [comment]
**Soft**ware. It's in the name. :wink:
