### ISSUE TITLE
Use random data generation library

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-smash#23]
Let's use a proper library for generating random data. The intent is two-fold. First, I'd like to get rid of functions like this (from `pulp_smash.tests.platform.api_v2.test_user`):

```python
def _rand_str():
    """Return a randomized string."""
    return type('')(randint(-100000, 100000))
```

Second, having a good random data generation library lowers the friction for writing new tests. It's one less worry for a developer.

**Comment by Ichimonji10** [comment]
One option is fauxfactory. We use it extensively in Robottelo and NailGun.

A second option is Faker. I discovered it while maintaining some Python packages for Arch. It's popular (346 forks!), has a significant collection of data providers (`gen_bs()`), has a nice plug-in architecture and has a low start-up time.

**Comment by elyezer** [comment]
Faker seems very interesting.

**Comment by Ichimonji10** [comment]
In the months since this issue was opened, I haven't seen any need to add a random data generation library to Pulp. We may need one in the future, but I see no reason to keep this issue open if there's no use case to point to.
