### ISSUE TITLE
Test Switching a repository to immediate from on_demand can download its packages

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#230]
1. Create a repository with on_download policy
2. Run repo sync
3. Check the file system to make sure that the content is not downloaded
4. Update the repository to change the the download policy to immediate
5. Run repo sync
6. Assert that the content in downloaded

**Comment by kersommoura** [comment]
There are several tests covering the aforementioned requirements.

See: [Test Download Policies](https://github.com/PulpQE/pulp-smash/blob/de034aef1e7037c564f0d6aec11df875ecda4318/pulp_smash/tests/rpm/api_v2/test_download_policies.py)
