### ISSUE TITLE
Publish should be a no-op if no units and no settings have changed since the last publish

### ISSUE THREAD

**Issue by ipanova** [PulpQE/pulp-smash#232]
Test that Publish should be a no-op if all of the following are true:
- no units have been added since the last successful publish.
- no units have been removed since the last successful publish.
- no distributor has been modified since the last successful publish.

For more info check https://pulp.plan.io/issues/1724
There is already implemented one test that is related #127 but i think that testing these 3 corner cases will be also good.

**Comment by ipanova** [comment]
One more corner case would be good to test when some values where specified in the override_config of the current publish - at this point publish should be operational.

**Comment by ipanova** [comment]
scenario1
1. create repo with feed, sync, publish
2 assert publish is operational
3 remove unit/add unit/ update distributor's config( like disable publish over http)
4 publish
5 assert publish is operational

scenario2
1 create sync repo, publish
2 assert publish is operational
3 publish repo and set override config
4 assert publish is operational

**Comment by midnightercz** [comment]
Tests in #290 
scenario3 covered with NOOPTestCase1
scenario1 coverred with NOOPTestCase2
scenario2 seems to be subset of scenario3
