### ISSUE TITLE
Langpacks sync and Publish verification

### ISSUE THREAD

**Issue by bmbouter** [PulpQE/pulp-smash#233]
The zoo repo on fedorapeople contains a `repodata/comps.xml` file in which contains a specification for [langpacks which got added with Pulp 2.9.0](http://www.pulpproject.org/2016/05/05/langpacks-support-added-to-pulp-2-9-0/).

To accomplish this test:
1. Sync a zoo repo with the feed: `https://repos.fedorapeople.org/repos/pulp/pulp/fixtures/rpm/`
2. Verify that the published comps.xml contains the expected langpacks definition from the fixture data. I think hardcoding it into the expected test would be simple and currently it is:

```
<langpacks>
  <match install="gorilla-%s" name="gorilla-en"/>
  <match install="zebra-%s" name="zebra-docs"/>
</langpacks>
```

The feature story:  https://pulp.plan.io/issues/1367
Pulp's pulp-admin [langpacks documentation](https://github.com/pulp/pulp_rpm/blob/c7a14c0129a241337ea182db6730955422705364/docs/user-guide/recipes.rst#package-langpacks)

**Comment by Ichimonji10** [comment]
Pulp Fixtures now lists langpacks in its `comps.xml` file. See: https://github.com/PulpQE/pulp-fixtures/blob/master/rpm/assets/comps.xml#L60-L63

Two tests have langpack-specific logic in their assertions, `pulp_smash.tests.rpm.api_v2.test_orphan_remove.OrphansTestCase` and `pulp_smash.tests.rpm.api-v2.test_download_policies.FixFileCorruptionTestCase`. Here's a (trimmed) sample of relevant code:

```python
# Support for package langpacks has been added in Pulp 2.9. In earlier
# versions, langpacks are ignored.
locally_stored_units = 39  # See repo['content_unit_counts']
if self.cfg.version >= Version('2.9'):
    locally_stored_units += 1
self.assertEqual(self.repo_post_download['locally_stored_units'], locally_stored_units)
```

Do we need to do more to show that langpacks are being treated correctly after a sync?

**Comment by bmbouter** [comment]
@Ichimonji10 It's so great that I can write a github issue and it gets implemented. Wow!

If I understand this, the unit count is being asserted to include the new one for langpacks. It would be good to also assert that the published comps.xml which is downloaded from the server contains the same [snippet of fixture data](https://github.com/PulpQE/pulp-fixtures/blob/master/rpm/assets/comps.xml#L60-L63). 

Note there were [three related pulp-smash issues](https://pulp.plan.io/issues/1367#note-18) for langpacks. Issue #234 would also be good to do in the near-term with a similar assertion on unit counts and published comps.xml files. The issue #235 is a test for pulp-admin which I don't think should be started any time soon.

Ask more questions if this isn't giving you the answers you need.

**Comment by Ichimonji10** [comment]
> If I understand this, the unit count is being asserted to include the new one for langpacks.

Yes, that's correct. I've improved tests for this in #271.

> It would be good to also assert that the published comps.xml which is downloaded from the server contains the same snippet of fixture data.

Let's say I create a repository with a feed of https://repos.fedorapeople.org/repos/pulp/pulp/fixtures/rpm/, sync the repository, create a distributor, and publish the repository. At this point, I can get a `comps.xml` file from a URL such as `https://pulp.example.com/pulp/repos/d4b92791-8ea8-4abb-b25f-900cbff22ad1/repodata/abc123-comps.xml`. Is it correct to say that this file should include [this snippet of fixture data](https://github.com/PulpQE/pulp-fixtures/blob/master/rpm/assets/comps.xml#L60-L63)?

**Comment by bmbouter** [comment]
@Ichimonji10 Yes, you've stated it perfectly.
