### ISSUE TITLE
Fiddle with multi-line docstrings

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-smash#24]
From https://github.com/PulpQE/pulp-smash/pull/20#discussion_r43385240:

> the recommended way for multiline docstring is like example below ( see https://www.python.org/dev/peps/pep-0008/#documentation-strings for more information):
>
> ```python
> """Return a foobang
>
> Optional plotz says to frobnicate the bizbaz first.
> """
> ```
>
> In other words, the closing `"""` should stay on its own line and don't need a blank line before it.

This makes sense. Let's implement this new format throughout the application. Making this change has value because it'll make the code base more palatable to other developers who are familiar with PEP8 (and PEP257).

**Comment by elyezer** [comment]
:+1:
