### ISSUE TITLE
Orphan remove by type can remove langpacks

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#256]
To accomplish this test:

1. Sync a zoo repo with the feed: https://repos.fedorapeople.org/repos/pulp/pulp/fixtures/rpm/
2. Delete the zoo repo
3. List orphan
4. Orphan remove --type

**Comment by Ichimonji10** [comment]
See: https://github.com/PulpQE/pulp-smash/issues/257

**Comment by elyezer** [comment]
:+1:
