### ISSUE TITLE
 Test rsync distributor can be used to publish RPM

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#264]
https://pulp.plan.io/issues/1759
The rsync_distributor will afford users of RPM's yum_distributor to publish repositories published by the yum_distributor to any server that supports key based ssh communication. The rsync_distributor will limit the units published by only publishing units associated with the repository before the date of the last publish of the yum_distributor.

The order of publishes for Docker will be different. The rsync_distributor will first publish content to any server that supports key based ssh communication. Then the web_distributor will publish the metadata about the content to some other web servers.

The rsync_distributor [for docker] will have an optional configuration option to 'update_web_distributor'. When set to True, the publish will update the 'web_distributor' associated with the same repository. The update will set the web_distributor's 'end_date' to the start time of the rsync_distributor's publish. This will limit which units are published by the web_distributor as described in #1887. This will prevent Pulp from publishing docker metadata for units that have not yet been published by the rsync_distributor.

1) Rsync content needed for the publish
2) Rewrite symlinks to be relative symlinks
3) Deduplicate the remote filesystem (make sure that content is present once and only symlinks live in published directories)
4) Ensure paths to published content on remote system are in proper order

**Comment by Ichimonji10** [comment]
I'm assigning this to the July 29th milestone. I think this is issue is important in part because it's a brand new feature that's likely to land in Pulp 2.9 and in part because of RCM's involvement in testing this feature. (See #320.)

I'm not assigning this task to the current milestone of July 15th. This feature has an extensive description and conversation log on pulp.plan.io, and from my reading of the issue, it will take a fair amount of time to fully understand the feature and write a correct test. I could likely get this done by the 15th, but I want to get some other tasks done between now and then.

**Comment by Ichimonji10** [comment]
The developers have shared their test plan with us. See: https://pulp.plan.io/issues/1759#note-20

**Comment by Ichimonji10** [comment]
This is a little note to myself. I'm dumping it here for convenience.

        # TODO: Rename test case to FastForwardTestCase. Add these steps.
        #
        # 4. Remove all files from the target directory. Publish with the rpm
        #    rsync distributor, and verify that no files are in the target
        #    directory. (This tests Pulp's fast-forward logic.)
        # 5. Perform a full publish with the rpm rsync distributor. Verify that
        #    the correct files are in in the target directory.

**Comment by Ichimonji10** [comment]
This is a note to self, listing some additional steps to be added to `RemoteUnitsPathTestCase`:

4. Remove all files from the target system's ``root`` directory, i.e. the
   directory specified by the RPM rsync distributor's ``root`` option.
5. Publish with the RPM rsync distributor again, and pass a different
   ``remote_units_path`` as an override option. Verify that files are
   placed in this directory, and that the original ``remote_units_path`` is
   not recreated.

**Comment by Ichimonji10** [comment]
I wrote up another test case, named `RemoteUnitsPathTestCase`. You can see my work here: https://github.com/PulpQE/pulp-smash/compare/master...Ichimonji10:remote-units-path

Unfortunately, the test doesn't currently pass, and I don't have time to fix it this week. See:

* https://pulp.plan.io/issues/2209
* https://pulp.plan.io/issues/2210

**Comment by Ichimonji10** [comment]
Pull request updated and submitted as #375.

**Comment by Ichimonji10** [comment]
[Pulp story 1759](https://pulp.plan.io/issues/1759) was given the current title of "As a user, I can use rsync distributor to publish RPM repositores" in [note 15](https://pulp.plan.io/issues/1759#note-15). I've updated the title of this GitHub issue accordingly.

We have tests for this feature area, and they were used to verify that the pulp.plan.io issue is working reasonably well. See [note 37](https://pulp.plan.io/issues/1759#note-37).
