### ISSUE TITLE
Run pulp-smash on upgraded machines

### ISSUE THREAD

**Issue by elyezer** [PulpQE/pulp-smash#266]
The current upgrading automation just do some sanity check on the content that was available before the upgrade. As an improvement pulp-smash should be run against the upgraded system to make sure it is fully functional.

**Comment by Ichimonji10** [comment]
Can you expand on this issue a little bit? In my mind, I imagine that when upgrade tests run, the following occurs:

1. A Jenkins job creates a VM. If that succeeds,
2. The Jenkins job installs Pulp version X. If that succeeds,
3. The Jenkins job upgrades Pulp from version X to version X + 1. If that succeeds,
4. The Jenkins job performs some sanity checks. If those pass,
5. The Jenkins job runs the full Pulp Smash test suite.

What changes need to be made to Pulp Smash so this can happen?

**Comment by elyezer** [comment]
The steps are all correct, there is no change needed on Pulp Smash. I opened this issue here to track the progress since on pulp_packaging where the jobs lives right now.

Basically what is missing is the step 5, which is the goal of this issue.

If you think here is not a good place to this task live I can move somewhere.

**Comment by Ichimonji10** [comment]
This works fine. It's just good to know exactly what needs to be done to satisfy this issue. Thanks for the clarification.

**Comment by elyezer** [comment]
@Ichimonji10 thanks for the feedback, my description was open and you helped me making it clear what needs to be accomplished here.

**Comment by Ichimonji10** [comment]
Any update on this?

**Comment by elyezer** [comment]
I decreased the priority on my task list. I will increase it again probably on next week.

**Comment by Ichimonji10** [comment]
Bump.

**Comment by elyezer** [comment]
This is done, I forgot to close it. Closing it now.

Thanks for checking.
