### ISSUE TITLE
Test Repository create and sync through proxy CLI

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#284]
Create a repository with the proxy options

Feed Proxy
  --proxy-host - proxy server url to use
  --proxy-port - port on the proxy server to make requests
  --proxy-user - username used to authenticate with the proxy server
  --proxy-pass - password used to authenticate with the proxy server

$ pulp-admin rpm repo create --repo-id proxy-sync --feed https://repos.fedorapeople.org/repos/pulp/pulp/fixtures/rpm/  --proxy-host http://proxy.example.org --proxy-port 8080 --proxy-user user --proxy-pass pass

Run repository sync
$ pulp-admin rpm repo sync run --repo-id proxy-sync
- [ ] RPM Repo
- [ ] Puppet Repo
- [ ] Docker Repo
- [ ] Iso Repo
- [ ] Python Repo

**Comment by omaciel** [comment]
@preethit what are the assertions you're looking for? I can assume that you'd want:
* assert that repos are successfully created
* assert that repos are successfully synchronized

Anything else? Perhaps that one can consume them?

**Comment by preethit** [comment]
@omaciel the 2 assertions you have mentioned are definitely needed. I will think for a bit more about what else need to be added to the list.
