### ISSUE TITLE
Test Repository create and sync through proxy by placing the config file

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#285]
Use the proxy setting in the config file
For Docker example
/etc/pulp/server/plugins.conf.d] # cat docker_importer.json
{
        "proxy_host": "http://proxy.example.org",
        "proxy_port": 8080,
        "proxy_username": null,
        "proxy_password": null
}
For rpm
/etc/pulp/server/plugins.conf.d/yum_importer.json
1. Create the the a repository ( Do not use the proxy options in the CLI)
2. Synchronize the repository
   Assert
3. Synchronize is successful
4. The synchronize is directed through the proxy

**Comment by jeremycline** [comment]
Based on https://pulp.plan.io/issues/2038 I think it would be helpful to include lazy and non-lazy repositories in this test.

One easy way to assert traffic is going through the proxy is to drop all http/https traffic that doesn't have the proxy as a destination with iptables/firewalld. This will cause the connection to time out (in about 6 seconds, I expect) and the sync to fail.
