### ISSUE TITLE
Test publish yum repo with different checksums

### ISSUE THREAD

**Issue by mhrivnak** [PulpQE/pulp-smash#286]
1. create an "rpm" repo in pulp with one or more RPMs, SRPMs, and DRPMs.
2. publish it with the "sha256" checksum type
3. verify publish (see below)
4. publish it with the "sha1" checksum type
5. verify publish (see below)
### Verification

It depends on how fancy and robust you want to get when it comes to inspecting the published XML. You'll need to somehow look at primary, other, filelists, and prestodelta XML files and make sure all of the unit-related checksums are using the checksum type you asked for.

Smash could download the files and actually parse them as XML. That wouldn't be too difficult, but who likes parsing XML...

Smash could just ensure that the string "sha256" shows up in the case when it should, and doesn't when it shouldn't.

In the case of "other" and "filelists", the checksum type itself won't be included. Each package will have a `pkgid` attribute that is the checksum value of the specified type. You could just verify that it's the correct length. Or you could actually cross-reference it with the checksum for the corresponding package listed in primary.

Another general way to help with this verification is to just make sure yum and/or dnf can actually read the metadata and use it. In my manual testing, I published a rhel7 kickstart repo and kickstarted a VM from it, just to make sure it was generally sane.

**Comment by kersommoura** [comment]
@mhrivnak as we talk the step 4 - publish it with the "sha1" checksum type has to executed with the --force-full option to force a full re-publish to happen.

**Comment by Ichimonji10** [comment]
@kersommoura 

```python
with self.subTest(comment='filelists.xml'):
    self.verify_filelists_xml(cfg, repo['distributors'][0], 'sha256')
with self.subTest(comment='other.xml'):
    self.verify_other_xml(cfg, repo['distributors'][0], 'sha256')
if feed == DRPM_UNSIGNED_FEED:
    with self.subTest(comment='prestodata.xml'):
        self.verify_prestodata_xml(cfg, repo['distributors'][0], 'sha256')
```

**Comment by kersommoura** [comment]
@Ichimonji10 

I will work on it.

Thanks for the review.
