### ISSUE TITLE
Test that updateinfo.xml contains at least one pkglist with one collection for each erratum

### ISSUE THREAD

**Issue by goosemania** [PulpQE/pulp-smash#288]
See [the comment #2 to the errata issue](https://pulp.plan.io/issues/1783#note-2).

1. Create repo and sync it from https://repos.fedorapeople.org/pulp/pulp/fixtures/rpm/
2. Remove gorilla package from the repo to make packages from the Gorilla erratum inapplicable to the repo.
3. Publish the repo. Now in the updateinfo.xml the erratum RHEA-2012:0058 which initially refered to the gorilla package only, should contain no packages but pkglist with empty collection and its name should be there:
```
<pkglist>
  <collection short="">
    <name>1</name>
  </collection>
</pkglist>
```

**Comment by Ichimonji10** [comment]
When implementing this test, consider taking a look at https://repos.fedorapeople.org/pulp/pulp/fixtures/rpm/repodata/. If you open and decompress the `...-updateinfo.xml.gz` file, you'll see this:

```xml
<update from="errata@redhat.com" status="stable" type="enhancement" version="1">
<id>RHEA-2012:0058</id>
<title>Gorilla_Erratum</title>
<release>1</release>
<issued date="2013-01-27 16:08:09"/>
<updated date="2014-07-20 06:00:01 UTC"/>
<description>Gorilla_Erratum</description>
<pkglist>
<collection short="">
<name>1</name>
<package arch="noarch" name="gorilla" release="1" src="http://www.fedoraproject.org" version="0.62">
<filename>gorilla-0.62-1.noarch.rpm</filename>
</package>
</collection>
</pkglist>
</update>
```

In addition, make sure to hunt around through the existing `utils` modules for utility function. For example, the `get_repomd_xml` and `get_repomd_xml_href` functions also deal with munging paths and parsing XML, and they may serve as a useful starting point.
