### ISSUE TITLE
Export yum repo group with specified checksum

### ISSUE THREAD

**Issue by mhrivnak** [PulpQE/pulp-smash#292]
As of pulp 2.9, you will be able to configure the "checksum_type" on the yum repo group export distributor. A basic test:

1. create a yum repo and add some content
2. create a repo group and add the above repo
3. set the "checksum_type" on the yum group distributor to a checksum type that is not in the unit key for content in the repo
4. publish with the group export distributor
5. verify that the published data uses the checksum type you specified

**Comment by Ichimonji10** [comment]
Related to #286.

**Comment by ipanova** [comment]
Maybe will worth to also add a test with invalid checksum_type specified.
