### ISSUE TITLE
Test the `repoview` option for the yum_distributor 

### ISSUE THREAD

**Issue by goosemania** [PulpQE/pulp-smash#295]
`repoview` is an option which can be enabled in the config for the `yum_distributor`, it requires the `generate_sqlite` option to be enabled, because sqlite files are used by the repoview tool.
If `repoview` is enabled, there will be an additional step responsible for the generation of the HTML files during publish.
As for the browsing, the HTTP request will be redirected to show a repoview content if it is available.

If one will enable `repoview` via pulp-admin, the `generate_sqlite` option will be silently enabled as well. If one would like to use REST API to enable `repoview`, the `generate_sqlite` option should be specified explicitly, otherwise an error will occur.

Suggestion for the test:
- create RPM repo
- sync and publish it
- observe no redirect and the directory list of packages when accessing repo content via HTTP(S).
- update `yum_distributor` with `repoview` and `generate_sqlite` options set to `True`
- re-publish repo
- observe redirect (302) to repoview content: https://path_to_the_repo/repoview/index.html

Redmine story: https://pulp.plan.io/issues/189
Redmine issue: https://pulp.plan.io/issues/2001

**Comment by Ichimonji10** [comment]
> observe no redirect and the directory list of packages when accesing repo content via HTTP(S).

What's an example of a URL that should not trigger a redirect?

> observe redirect (302) to repoview content: https://path_to_the_repo/repoview/index.html

What's an example of a URL that should trigger a redirect?

**Comment by goosemania** [comment]
The same URL when you try to access your published repo, e.g.  https://localhost/pulp/repos/your_repo/
If repoview content is available you will observe redirect, if not - no redirect.
