### ISSUE TITLE
Manage content on consumer

### ISSUE THREAD

**Issue by dkliban** [PulpQE/pulp-smash#296]
Pulp is able to manage content installed on registered consumer. Tests are needed to make sure that
- A consumer can register with pulp-server using 'pulp-consumer' commands. 
- A repository can be bound to a consumer using 'pulp-consumer' command. 
- API can be used to install individual packages on consumer. 
- API can be used to uninstall package on consumer
- API can be used to install Errata on consumer

**Comment by kersommoura** [comment]
See also: [611](https://github.com/PulpQE/pulp-smash/issues/611)
