### ISSUE TITLE
List available tests at runtime

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-smash#3]
It's possible to run Pulp tests with the following commands:

``` sh
python -m unittest2 discover pulp_smash.tests
python -m unittest2 pulp_smash.tests.test_login
python -m unittest2 pulp_smash.tests.test_content_applicability
```

As the number of test modules grows, the list above will grow too. It would be nice if we could tell users about this list at run-time, rather than forcing them to examine the source code to see what modules are available. Imagine something like this:

```
$ python -m pulp_smash list_tests
pulp_smash.tests.test_login
pulp_smash.tests.test_content_applicability
```

I don't know exactly how, but I'm sure this is possible. Consider the following:

``` python
>>> import os
>>> from pulp_smash import tests
>>> from unittest import TestLoader
>>> loader = TestLoader()
>>> root_dir = os.path.dirname(tests.__file__)
>>> root_dir
'/home/ichimonji10/code/pulp-smash/pulp_smash/tests'
>>> test_suite = loader.discover(root_dir)
```

At this point, you can call `test_suite.run()`. That's great if we'd like to run tests directly from the command line (and we do!). But how can we extract module names from that and provide them to the user?

**Comment by elyezer** [comment]
One thing that should be took into consideration here is that if will not be created a new test runner (like nose and py.test).or provide most features that they already provide out of the box.

**Comment by Ichimonji10** [comment]
I don't understand your comment, @elyezer. Can you try to wordsmith that comment for me, or can you follow up with me on IRC?

**Comment by lpramuk** [comment]
@Ichimonji10 I'm used to run it like this:
```
unittest2.TextTestRunner(verbosity=3).run(unittest2.TestSuite().addTest(TestCase('test_method')))
```or 
```unittest2.TextTestRunner(verbosity=3).run(unittest2.TestLoader().loadTestsFromTestCase(TestCase))
```
May verbosity help you?

**Comment by Ichimonji10** [comment]
@lpramuk That does let me see which tests have been run. It produces output like this:

    >>> TextTestRunner(verbosity=3).run(test_suite)
    test_body (test_content_applicability.FailureTestCase)
    Assert that the responses are JSON and appear to be call reports. ... ok
    test_status_code (test_content_applicability.FailureTestCase)
    Assert that each response has an HTTP 400 status code. ... ok
    …

But I'm trying to do something a little bit different. I'm trying to list out the available tests without running them.

**Comment by lpramuk** [comment]
I see then you mean something like this:
```
for method in dir(TestCase):
    if method.startswith("test"):
```

**Comment by Ichimonji10** [comment]
@lpramuk Yes, I'm trying to do something a bit like that.

I've discovered one existing solution that partially implements what I'm looking for: nose2's "collect" plugin. See: [documentation](http://nose2.readthedocs.org/en/latest/plugins/collect.html) and [source code](https://github.com/nose-devs/nose2/blob/master/nose2/plugins/collect.py). Sample usage:

```
$ nose2 --verbose --plugin nose2.plugins.collect --collect-only pulp_smash.tests
test_body (pulp_smash.tests.platform.api_v2.test_content_applicability.FailureTestCase)
Assert that the responses are JSON and appear to be call reports. ... ok
test_status_code (pulp_smash.tests.platform.api_v2.test_content_applicability.FailureTestCase)
Assert that each response has an HTTP 400 status code. ... ok
test_body (pulp_smash.tests.platform.api_v2.test_content_applicability.SuccessTestCase)
Assert that the responses are JSON and appear to be call reports. ... ok
test_status_code (pulp_smash.tests.platform.api_v2.test_content_applicability.SuccessTestCase)
Assert that the responses have HTTP 202 status codes. ... ok
test_body (pulp_smash.tests.platform.api_v2.test_login.LoginFailureTestCase)
Assert that the response is valid JSON and does not have "key" and ... ok
test_status_code (pulp_smash.tests.platform.api_v2.test_login.LoginFailureTestCase)
Assert that the response has an HTTP 401 status code. ... ok
test_body (pulp_smash.tests.platform.api_v2.test_login.LoginSuccessTestCase)
Assert that the response is valid JSON and has "key" and ... ok
test_status_code (pulp_smash.tests.platform.api_v2.test_login.LoginSuccessTestCase)
Assert that the response has an HTTP 200 status code. ... ok
test_response_0 (pulp_smash.tests.platform.api_v2.test_repository.CreateDuplicateTestCase)
Assert that the first response has an HTTP 201 status code. ... ok
test_response_1 (pulp_smash.tests.platform.api_v2.test_repository.CreateDuplicateTestCase)
Assert that the second response has an HTTP 409 status code. ... ok
test_body (pulp_smash.tests.platform.api_v2.test_repository.CreateMissingTestCase)
Assert that the response contains the correct keys. ... ok
test_body_v2 (pulp_smash.tests.platform.api_v2.test_repository.CreateMissingTestCase)
Assert that the response contains exactly the correct keys. ... ok
test_status_code (pulp_smash.tests.platform.api_v2.test_repository.CreateMissingTestCase)
Assert that the response has an HTTP 400 status code. ... ok
test_id (pulp_smash.tests.platform.api_v2.test_repository.CreateTestCase)
Assert that the repository has the requested ID. ... ok
test_status_code (pulp_smash.tests.platform.api_v2.test_repository.CreateTestCase)
Assert that the response has an HTTP 201 status code. ... ok

----------------------------------------------------------------------
Ran 15 tests in 0.002s

OK
```

It works, but:

* The output is more verbose than I'd like:
* This requires that the user install nose2 and execute a command not documented by `python -m pulp_smash`.

It may be possible to read through the source code of that plugin and adapt what's there.

**Comment by elyezer** [comment]
That is what I tried to say before, may worth picking a test runner and leverage its feature. Both nose and py.test are able to capture the tests.

Another approach would be something like we use for testimony, we are able, thru the ast module, get all test methods. We can then create a module on pulp-smash with inspect the modules and provide the tests information, this way we can even respect the organization proposed for the tests and output something that matches that.

**Comment by Ichimonji10** [comment]
Tests are being removed from Pulp Smash as per #949, making this  issue a moot point.
