### ISSUE TITLE
Test that rpms can be published to custom directory

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#300]
https://pulp.plan.io/issues/1976

Test that a separate directory can be specified where packages can be published.

Context
There was decision made in the past which led to this split (repodata and packages in separate directory) and that's why we have to keep this structure compatible. Although we have some repositories where repodata are in the same directory as packages. I don't know historical details, but as I mentioned above, fedora repositories also use this.

Acceptance Criteria
- attribute has to be optional
- attribute has to be in format that is allowed by mkdir
- if attribute is not set, packages have to be sync to relative_path of repository

**Comment by Ichimonji10** [comment]
Can I get more information about this desired test case? I've read through the following:

* https://pulp.plan.io/issues/1976
* https://github.com/pulp/pulp_rpm/pull/897

However, I'm unclear on:

* Is the new `packages_directory` yum exporter configuration option only available via the API? Or is there a new CLI option too?
* What is the intended effect of this new option? A contrast between what's placed on disk without using this option and with using this option would be great.

@midnightercz, you might be able to shed some light on this.

**Comment by midnightercz** [comment]
@Ichimonji10 sorry for late response. I think @bmbouter forced me to do also CLI option for that. 
When you set this option, your rpms should end in repo/<packages_directory> instead of /repo directory

**Comment by Ichimonji10** [comment]
I'm adding this issue to the July 15th milestone because there's been a bit of a ruckus surrounding https://pulp.plan.io/issues/1976, and having a test for that feature request will help prevent additional issues.
