### ISSUE TITLE
Test that --force_full is supported in export

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#301]
https://pulp.plan.io/issues/1938

Steps
1. Create a repository
2. Sync the repo
3. Export the repo with --force_full option

Assert
1. --force_full  can be set to true
2. --force_full can be set to false
3. --force-full option can be omitted

$ pulp-admin -vv rpm repo export run --repo-id foo --force-full

+----------------------------------------------------------------------+
                      Publishing Repository [ina]
+----------------------------------------------------------------------+

The following publish configuration options will be used:

Force Full:  True

**Comment by Ichimonji10** [comment]
We have a test for the `force_full` API v2 option in module [`pulp_smash.tests.rpm.api_v2.test_force_full`](http://pulp-smash.readthedocs.io/en/latest/api/pulp_smash.tests.rpm.api_v2.test_force_full.html). @preethit, is this existing test satisfactory?

**Comment by preethit** [comment]
@Ichimonji10 Those tests only seem to cover the --force_full option in publish.

Repo export also has the option and this issue is for that.

**Comment by Ichimonji10** [comment]
Ahh. So if [`pulp_smash.tests.rpm.api_v2.test_export`](http://pulp-smash.readthedocs.io/en/latest/api/pulp_smash.tests.rpm.api_v2.test_export.html) were expanded, then that'd fix this issue. Correct?

**Comment by preethit** [comment]
Yes. That is the one.
