### ISSUE TITLE
Docstrings point to pulp.readthedocs.io instead of new docs.pulpproject.org site

### ISSUE THREAD

**Issue by dralley** [PulpQE/pulp-smash#313]
82 matches for "http://pulp.readthedocs.io/" across 30 files

http://pulp.readthedocs.io/ is scheduled to be taken down in 6 days

**Comment by Ichimonji10** [comment]
Related: https://github.com/PulpQE/pulp-fixtures/pull/16 :wink:

**Comment by dralley** [comment]
All instances found by a simple universal search for "http://pulp.readthedocs.io/"

https://paste.fedoraproject.org/383280/66072301/

**Comment by Ichimonji10** [comment]
That doesn't work, unfortunately, b/c of:

* Links to alternate domains, like `pulp-rpm.readthedocs.io`
* Links that use `https`

Try `git grep 'http\S*readthedocs.io'`.
