### ISSUE TITLE
Rpm Plugin Repo CRUD

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#33]
- [x] Create a repo
- [x] Associate importer to the repo
- [x] List the repo
- [x] Update the repo
- [x] Delete the repo

http://pulp-dev-guide.readthedocs.org/en/pulp-2.2/integration/rest-api/
https://github.com/RedHatQE/pulp-automation/blob/master/tests/general_tests/test_02_repo_cud.py

**Comment by Ichimonji10** [comment]
I'm working with @dkliban on this right now. See: https://github.com/PulpQE/pulp-smash/compare/master...Ichimonji10:zoo_repo_sync

**Comment by preethit** [comment]
I know you are but wanted to make sure this is the kind of issues you had in mind. Let me know if you want me add any other details when writing up issues.

**Comment by Ichimonji10** [comment]
Aye, I definitely agree with that. So far, I've hard-coded that repository reference in my test module, simply because it's expedient. But I really don't like having that configuration information hard-coded! I need to brainstorm a little bit and figure out how to extract that configuration information from the test itself. The first idea that comes to mind is to add a new section to the configuration file, like so:

```json
{
  "default": {
    "base_url": "https://pulp-system.example.com",
    "auth": ["admin", "admin"],
    "verify": false
  },
  "rpm_repo_url": "http://repos.fedorapeople.org/repos/pulp/pulp/demo_repos/zoo/"
}
```

**Comment by peterlacko** [comment]
I also made some draft on importer and distributor tests so you can look at it here:
https://github.com/peterlacko/pulp-smash/blob/rpm-repo-tests/pulp_smash/tests/platform/api_v2/test_rpm_repo.py

**Comment by Ichimonji10** [comment]
The recently added [`pulp_smash.tests.rpm.api_v2.test_sync_publish`](https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/tests/rpm/api_v2/test_sync_publish.py) module covers several of the areas listed [here](#issue-115559477). However:

* No tests directly update the repository. The closest we have are calls that associate a repo with a distributor, import an RPM into a repository, and so on. None of those calls hit the `/pulp/api/v2/repositories/{id}/` path. They all hit sub-paths like `.../distributors/` and `.../actions/import_upload/`.
* No tests read a repository directly and verify its state. The closest we have is a test that reads `.../importers/`.

**Comment by dkliban** [comment]
The test does perform a query on the repository to see what units are in it.

**Comment by Ichimonji10** [comment]
Not actively working on this right now, so unassigning myself.

**Comment by asmacdo** [comment]
Add failure tests from https://github.com/RedHatQE/pulp-automation/blob/master/tests/general_tests/test_02_rpm_repo.py

**Comment by kersommoura** [comment]
There are several tests covering the aforementioned requirements.

See: [CRUD](https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/tests/rpm/api_v2/test_crud.py)
