### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by elyezer** [PulpQE/pulp-smash#332]
Python 2.7 support have been extended until 2020 but there are some people panning already to move away from Python 2 and leverage Python 3's power.

The Python 3 statement website links some resources that can explain why dropping Python 2 support is a good thing. For Pulp Smash since it is intended to be run on one machine (probably a QE or developer machine) and test a Pulp server on another we are safe to drop Python 2 support because most Linux distributions come with Python 3 as the default Python interpreter.

Also by doing that we can start thinking on how to leverage Python 3 features in order to make Pulp Smash a better testing framework for Pulp.

Also we need to have some dependencies because we are needing some features that Python 3 modules already offers, for example, mock and unittest2 packages are needed because features like mock and unittest.subTests are needed and they are Python 3 builtin.

Other requirements: packaging, plumbum, python-dateutil, pyxdg and requests already supports Python 3.

The immediate gains on dropping Python 2 are to remove the overhead on making Pulp Smash runs on both Python 2 and Python 3 which will give more time to developers to add more features and test cases and drop some compatibility and packages needed to ensure Pulp Smash working on both Python versions.

[1] https://python3statement.github.io/

**Comment by bmbouter** [comment]
:+1:

**Comment by Ichimonji10** [comment]
I'd be excited to switch to Python 3. The switch would let us drop mock, unittest2, and all cross-compatibility code. (e.g. `__future__` statements and `type(u'')` expressions) It would also let us start taking advantage of newer features, like [new function calling syntax & semantics](http://pastebin.com/vCCLQqSz) and [exception chaining](http://stackoverflow.com/a/16414892). (See [PEP 3102](https://www.python.org/dev/peps/pep-3102/) and [PEP 3134](https://www.python.org/dev/peps/pep-3134/).)

Dropping unittest2 as the reference test runner in favor of unittest would also give us an opportunity to re-evaluate the jUnit XML test report generators [unittest-xml-reporting](https://pypi.python.org/pypi/unittest-xml-reporting) and [junit-xml](https://pypi.python.org/pypi/junit-xml). (If one of them works, we could use the [`load_tests` protocol](https://docs.python.org/3.5/library/unittest.html#load-tests-protocol)!)

The obvious question to answer is "who uses Python 2?" So far, cross-compatibility has been maintained to ensure that Pulp Smash is usable by a wide audience. But who is that audience? Any semi-modern Linux distribution has access to Python 3.3 or newer. (Python 3 is the default on Arch and Fedora.) Is Python 3.3 available on Mac OS?

**Comment by Ichimonji10** [comment]
@omaciel @danuzclaudes @preethit @ipanova etc.

**Comment by BrnoPCmaniak** [comment]
What I know OS X comes preloaded with IPython 2.7. But I'm not 100% sure.

**Comment by elyezer** [comment]
Who is currently using Mac OS X to run Pulp Smash?

**Comment by Ichimonji10** [comment]
Og, possibly. And anecdotally, I've seen Mac OS be used heavily by developers.

How hard is it to install Python 3 and create a Python 3 virtualenv on Mac OS?

**Comment by BrnoPCmaniak** [comment]
If you are developer, quite easy. For ordinary user quite hard I would say (Installing Xcode/gcc).
http://docs.python-guide.org/en/latest/starting/install/osx/#doing-it-right
You have to use brew, I think. And as long as you don't want to use brew on multiple accounts, brew is just copy-paste.

**Comment by elyezer** [comment]
This can be an issue on dropping support. I will check on my Mac what is the latest Python version available if that is 2.7.10+ then we can start slowly dropping support and do a hard drop later.

**Comment by Ichimonji10** [comment]
I'd really love a chance to run through the Python 3 installation process myself on a Mac. The official [Python for Beginners](https://www.python.org/about/gettingstarted/) page gives the impression that it's easy to get python 3 installed. By the way, Python 3 ships with pip and venv in the standard library.

**Comment by elyezer** [comment]
@Ichimonji10 there are installers for Python 3, see [1]. Those pkg are very easy to install on Mac OS so I think we are safe to support only Python 3.

[1] https://www.python.org/downloads/mac-osx/

**Comment by elyezer** [comment]
I will try that myself and will report the results here.

**Comment by Ichimonji10** [comment]
@elyezer Can you make sure to create a virtualenv? It should be as simple as `python3 -m venv env`. It *should* work, but I just want to have that sanity check.

**Comment by elyezer** [comment]
I have verified that installing Python 3 is very easy. First I went to the Python's website and downloaded the latest stable Python 3 version. The image below show that the site identifies the Operating System and provide an easy download button.

![screen shot 2016-08-15 at 11 19 34 am](https://cloud.githubusercontent.com/assets/48132/17667342/ee22a10a-62da-11e6-97c8-023d83c76955.png)

Then I opened the downloaded pkg (mine was python-3.5.2-macosx10.6.pkg) file and did the normal Mac installation procedure. When the installation completed I ran the following:

```console
Elyezers-MacBook-Pro:~ elyezer$ which python3
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3
Elyezers-MacBook-Pro:~ elyezer$ python3 --version
Python 3.5.2
```

The system comes with Python 2.7 and that did not messed with it since python (without the version) continues pointing to the 2.7 python version:

```console
Elyezers-MacBook-Pro:~ elyezer$ python --version
Python 2.7.10
```

Then I checked that Python 3 comes with virtual environment built in by running the following commands:

```console
Elyezers-MacBook-Pro:~ elyezer$ python3 -m venv
usage: venv [-h] [--system-site-packages] [--symlinks | --copies] [--clear]
            [--upgrade] [--without-pip]
            ENV_DIR [ENV_DIR ...]
venv: error: the following arguments are required: ENV_DIR
Elyezers-MacBook-Pro:~ elyezer$ python3 -m venv testenv
Elyezers-MacBook-Pro:~ elyezer$ source testenv/bin/activate
(testenv) Elyezers-MacBook-Pro:~ elyezer$ which python3
/Users/elyezer/testenv/bin/python3
(testenv) Elyezers-MacBook-Pro:~ elyezer$ which python
/Users/elyezer/testenv/bin/python
(testenv) Elyezers-MacBook-Pro:~ elyezer$ python3 -m pip install requests
Collecting requests
  Downloading requests-2.11.0-py2.py3-none-any.whl (514kB)
    100% |████████████████████████████████| 522kB 535kB/s
Installing collected packages: requests
Successfully installed requests-2.11.0
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(testenv) Elyezers-MacBook-Pro:~ elyezer$ python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> exit()
```

Finally I checked that Pulp Smash actually works (you know just a sanity check):

```console
(testenv) Elyezers-MacBook-Pro:~ elyezer$ git clone https://github.com/PulpQE/pulp-smash.git
Cloning into 'pulp-smash'...
remote: Counting objects: 3273, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 3273 (delta 0), reused 0 (delta 0), pack-reused 3262
Receiving objects: 100% (3273/3273), 937.62 KiB | 436.00 KiB/s, done.
Resolving deltas: 100% (2176/2176), done.
Checking connectivity... done.
(testenv) Elyezers-MacBook-Pro:~ elyezer$ cd pulp-smash/
(testenv) Elyezers-MacBook-Pro:pulp-smash elyezer$ which pip
/Users/elyezer/testenv/bin/pip
(testenv) Elyezers-MacBook-Pro:pulp-smash elyezer$ pip install -r requirements-dev.txt
# output ommited
(testenv) Elyezers-MacBook-Pro:pulp-smash elyezer$ pip install -r requirements.txt
# output ommited
(testenv) Elyezers-MacBook-Pro:pulp-smash elyezer$ make all
coverage run --source pulp_smash.api,pulp_smash.cli,pulp_smash.config,pulp_smash.exceptions,pulp_smash.selectors,pulp_smash.utils \
       	-m unittest discover --start-directory tests --top-level-directory .
.........................................................................
----------------------------------------------------------------------
Ran 73 tests in 0.763s

OK
flake8 . --ignore D203
pylint -j 4 --reports=n --disable=I \
       		docs/conf.py \
       		setup.py \
       		tests \
       		pulp_smash/__init__.py \
       		pulp_smash/__main__.py \
       		pulp_smash/api.py \
       		pulp_smash/cli.py \
       		pulp_smash/config.py \
       		pulp_smash/constants.py \
       		pulp_smash/exceptions.py \
       		pulp_smash/selectors.py \
       		pulp_smash/utils.py
No config file found, using default configuration
pylint -j 4 --reports=n --disable=I,duplicate-code pulp_smash/tests/
No config file found, using default configuration
rm -rf _build/* api/*
rm -rf _build/* api/*
cd ..; ./scripts/gen_api_docs.sh
sphinx-build -W -b html -d _build/doctrees   . _build/html
Running Sphinx v1.4.5
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 101 source files that are out of date
updating environment: 101 added, 0 changed, 0 removed
reading sources... [100%] usage

Warning, treated as error:
/Users/elyezer/pulp-smash/docs/api.rst:11: WARNING: toctree contains reference to nonexisting document 'api/pulp_smash'

make[1]: *** [html] Error 1
make: *** [docs-html] Error 2
```

I've got a documentation error which is not related on Pulp Smash running on Python 3 on a Mac. With all that said, I think we are safe to drop Python 2 support.

**Comment by Ichimonji10** [comment]
This addresses my concern about whether Mac users will be able to use Pulp Smash.

I'm not worried about Linux users. Some folks (RHEL 5 users, and maybe RHEL 6 too?) still don't have easy access to Python 3. However, I imagine that someone using one of these older enterprise distributions is knowledgeable to either:

* Get Python 3 installed on their system, despite the higher barrier to entry, or
* just *not* run Pulp Smash on the older system. After all Pulp Smash can run on a separate system from Pulp.

**Comment by omaciel** [comment]
I have been using Python 3 and creating virtual envs with it by using `brew install python3`.

**Comment by elyezer** [comment]
It seems that we finally reached an agreement that dropping Python 2 is something that will not be something bad for the users. With that said I will close this issue and create a plan for dropping Python 2 support.
