### ISSUE TITLE
Test uploading DRPMs

### ISSUE THREAD

**Issue by BrnoPCmaniak** [PulpQE/pulp-smash#336]
Tests for Uploading DRPMs from [story 1806](https://pulp.plan.io/issues/1806).

API
===

Steps:

1. Create a repository
2. Upload DRPM

Assert:

1. DRPM is in content retrieval of the repo.
2. DRPM has a correct name

CLI
===

## Test Upload
Steps:

1. Create repository
2. Upload DRPM

Assert:

output of `pulp-admin rpm repo content drpm` matches:

```
Arch:         noarch
Checksum:     a498a1d973f6e8550cf2fb863a2640b92dc4ba3ed5fcb26e3b123ce04bd39723
Checksumtype: sha256
Epoch:        0
Filename:     drpms/yum-3.2.29-20.fc16_from_el6_3.4.3-8.fc16.noarch.drpm
Release:      8.fc16
Version:      3.4.3


```

## Test skip existing

Steps:
1. Create Repository
2. Upload DRPM
3. Upload DRPM again with flag `--skip-existing`

Assert:
`No files eligible for upload` in output of step 3

I'm trying to write a PR myself.

**Comment by elyezer** [comment]
@BrnoPCmaniak great.

A little tip, currently on https://github.com/PulpQE/pulp-fixtures we don't have any DRPM fixtures, if you need some binary files to upload the fixtures is the place.

**Comment by Ichimonji10** [comment]
https://github.com/PulpQE/pulp-fixtures/issues/11

**Comment by Ichimonji10** [comment]
Fixed by https://github.com/PulpQE/pulp-smash/pull/337
