### ISSUE TITLE
As a user, units which don't pass the signature check are not imported 

### ISSUE THREAD

**Issue by ipanova** [PulpQE/pulp-smash#347]
1)create repo with feed and specify list of allowed keys( which are different from the signing keys of synced content).
2) sync repo
3) check that none of those packages were imported into the repo
4) check the counter of not imported packages is correct

1) create repo with feed and specify list of allowed keys( which is the same as the signing keys of synced content).
2) sync repo
3) check that packages were imported into the repo

1)create repo with feed and set require-signature to True. It is better to provide a feed where there are several types of packages like [here](https://repos.fedorapeople.org/repos/pulp/pulp/demo_repos/test_drpm_repo/) DRPMs + SRPMs
2) sync repo
3) check that none of those packages were imported into the repo because they are unsigned
4) check the counter of not importer packages is correct ( sum of drpms and srpms)
5) update require-signature to False
6) sync repo again
7) check that all packages were imported into the repo

Since there are 2 config parameters `--require-signature` and `--allowed-keys` you can test different scenarios where you:

1) require packages to be signed and provide a specific list of keys
2) require packages just to be signed but you don't care with which keys( i.e allowed-keys is empty)
3) you allow unsigned packages but those which are signed should be signed with specific keys that are in the list of allowed-keys

Since signature policy is not compatible with lazy sync, confirm that:

1) during repo creation you cannot have on_demand background policy and signature policy enabled
2) during repo update you cannot switch to on_demand background policy if signature policy is enabled. ("Signature policy enabled" means you have some keys specified in the allowed-keys or require-signature is set to True.)

Keys that are provided into allowed-keys should be 8 characters long. Confirm that providing keys that has different length will raise an error.

This functionally was implemented not just for sync but for copy and upload. so you will have here a bit of work..

Some copy scenarios:

1) create repoA with on_demand policy and sync it
2) create repoB with signature policy enabled
3) copy from repoA to repoB and confirm that no packages were imported into repoB

1) create repoA  and sync it( for example sync unsigned packages)
2) create repoB with signature policy enabled( require-signature set to True)
3) copy from repoA to repoB and confirm that no packages were imported into repoB

Upload is the most simple here.

1) create repo with signature policy enabled
2) upload a concrete file  or from a directory
3) confirm package was imported or not based on yours signature policy settings.

**Comment by Ichimonji10** [comment]
Very, very good issue. Thank you, @ipanova.

**Comment by Ichimonji10** [comment]
Related: https://pulp.plan.io/issues/1991

**Comment by Ichimonji10** [comment]
A first round of tests targeting this issue have been merged. See 7779cea52adeb009b280190fd4050c6abebdb2af. The commit message is as follows:

> Test signature checks when uploading packages
>
> Add a new module,
> `pulp_smash.tests.rpm.api_v2.test_signature_checks_for_uploads`. This
> new module verifies whether RPM repository importers configured to
> perform package signature checks do so when packages are uploaded to
> repositories.
>
> The new test cases do the following:
>
> * Use an importer that allows unsigned packages and has a valid key ID.
> * Use an importer that allows unsigned packages and has an invalid key ID.
> * Use an importer that allows unsigned packages and has no key IDs.
> * Use an importer that requires signatures and has a valid key ID.
> * Use an importer that requires signatures and has an invalid key ID.
> * Use an importer that requires signatures and has no key IDs.
> * Verify pulp rejects key IDs that are not 32-bits long.
>
> See: #347

**Comment by Ichimonji10** [comment]
In my opinion, we can mark this issue closed when tests are in place showing that:

- [ ] Pulp saves package signature IDs.
- [ ] Pulp checks signature IDs for uploaded packages.
- [ ] Pulp checks signature IDs for synced packages.
- [ ] Pulp checks signature IDs for copied packages.

**Comment by Ichimonji10** [comment]
Setting this to the current milestone. (I *know* this can get done by the end of this week.)

**Comment by Ichimonji10** [comment]
A solid set of tests for this feature are in place. See [the checklist, above](https://github.com/PulpQE/pulp-smash/issues/347#issuecomment-245004718). Marking as closed.
