### ISSUE TITLE
Update ``make test-coverage`` make target

### ISSUE THREAD

**Issue by jeremycline** [PulpQE/pulp-smash#35]
``pulp_smash.utils.rand_str`` was added by https://github.com/PulpQE/pulp-smash/pull/28, but tests do not exist for the function. Furthermore, the missing coverage is not detected by the current ``make test-coverage``.

**Comment by Ichimonji10** [comment]
:+1:

**Comment by Ichimonji10** [comment]
I'd also like to rename the `pulp_smash.utils.rand_str` function to `uuid4`. The latter name more accurately reflects what the function does: it calls the `uuid4` function from the standard library and casts it to a unicode string.
