### ISSUE TITLE
Remove all Python 2 related compatibility

### ISSUE THREAD

**Issue by elyezer** [PulpQE/pulp-smash#356]
On #332 we agreed that we are able to drop Python 2 support for Pulp Smash. Here is the plan to actually get that done:

- [ ] Drop the compat module
- [ ] Update the imports to reflect the removal of the compat module
- [ ] Drop unittest2 in favor of Python 3's unitttest module and update the code
- [ ] Drop mock in favor of the builtin Python 3's mock
- [ ] Update the `setup.py` file
- [ ] Update the documentation
- [ ] Drop `__future__` imports

**Comment by Ichimonji10** [comment]
Added "Update the `setup.py` file"

**Comment by Ichimonji10** [comment]
Will we need to update the Jenkins jobs?

**Comment by elyezer** [comment]
No, Jenkins jobs are running on a Fedora 23 slave which already have Python 3 installed, it should just work.

**Comment by Ichimonji10** [comment]
Moving this back by two milestones.
