### ISSUE TITLE
Upgrade Testing for pulp

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#36]
* [x] Provision a box
* [x] Install pulp and plugins that you are upgrading from
* [x] populate pulp with all kinds of data
* [x] Update pulp
* [x] Migrate DB
* [x] Check all the service (Restart)
* [x]  Run regression tests
* [x]  Run Data Integrity test on data migrated over.

**Comment by peterlacko** [comment]
To extend this issue, I suggest data integrity testing to be included in pulp smash in separate folder, so it will not run together with other tests, ie `pulp_smash/upgrade_tests/` and would consists shell/python scripts for populating pulp server with data that would be executed before upgrading pulp and data integrity tests that would run after upgrade.

**Comment by Ichimonji10** [comment]
Good idea, @peterlacko.

**Comment by asmacdo** [comment]
There should me multiple cases. The database dump should come from each Y release of pulp that we allow migration from. 

Additionally, the data should have 2 or more of each item. There are some simple bugs that occur in migration only when there is more than one item.

**Comment by asmacdo** [comment]
@Ichimonji10, as a preliminary step I think it is super crucial to at least attempt to run migrations on a db dump from an old release. This has broken at least 3 times now, so I think this should be the highest priority new case we have. 

In fixing https://pulp.plan.io/issues/1738, I got a db dump from @preethit which I can send to you.

For instructions on how to use a mongo dump, use [this doc](https://github.com/pulp/pulp/blob/master/playpen/mongoengine/README#L26) to load the data and then run `sudo -u apache pulp-manage-db`

For now, simply asserting that the migration finish would be a significant help.

**Comment by mhrivnak** [comment]
I agree completely. This would be hugely valuable.

**Comment by Ichimonji10** [comment]
@elyezer, I believe you're working on this, so I'm assigning you.

**Comment by elyezer** [comment]
@Ichimonji10 you are completely right. I'm gonna handle this task. Thanks for assigning me.

**Comment by Ichimonji10** [comment]
See: https://github.com/pulp/pulp_packaging/pull/157

**Comment by elyezer** [comment]
I have covered most of the items on https://github.com/pulp/pulp_packaging/pull/157. What is missing is just running the regression tests.

**Comment by elyezer** [comment]
This task is completed. I've opened #266 for further improvements.
