### ISSUE TITLE
Docker repo sync works with basicauth #1291

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#368]
The idea is to sync a private docker repo from dockerhub. You will need
to create a dockerhub account, create a repo, and sync it using
--basicauth-user and --basicauth-pass from the CLI.
1. Create a private docker repo
2. Create a docker repo with the feed 
   pulp-admin docker repo create --repo-id foo r --feed --feed=https://registry-1.docker.io --basickauth-user user --basicauth-pass pass --upstream-name preethit/test_repo --enable-v1=false --enable-v2=true
3. Sync the repo

Validate
- [ ] The repo can be created with  --basickauth-user  --basicauth-pass 
- [ ] There is appropriate error messages when 
                   1.  --basickauth-pass is missing
                    2. --basicauth-pass pass is missing
- [ ] Prompts you for user and password information when you do not provide them in command line
- [ ]  The sync fails with appropriate error message when attempting syncing from private docker without user/pass info  
- [ ]   The repo can be updated to provide  user/password
- [ ]   Repo sync is successful when you provide all the required info

**Comment by omaciel** [comment]
@preethit thank you for the steps. Now, we need the expected outcome you want the automated tests to validate. for example, I can assume that you'd want the private docker repo to be successfully synchronized. Are there any other checks/validations that should be performed?

**Comment by preethit** [comment]
@omaciel updated the issue with validation info.
