### ISSUE TITLE
Test  2 concurrent repo publish using the same parent directory

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#397]
If two repos are published concurrently and share a parent directory, there is a chance they will try to create the parent directory at the same time. 
https://pulp.plan.io/issues/2047
Test Case 1
1. Create repo A with feed  which has a relative-url foo/bar/A
2. Create repo B with feed which has a relative-url foo/bar/B
3. Create a sync plan to sync both at the same time

Assert:
1. Both repos can be synced and published

Test case 2
1. Create repo A with relative-url foo/bar/A
2. Create repo B with  relative-url foo/bar/B
3. Upload/Copy content to both repos
4. Publish both repos at the same time

Assert:
1. Both repos can be published without any errors.

**Comment by Ichimonji10** [comment]
The test outlined above targets a race condition. Effectively testing this will likely require publishing a pair of repositories dozens of times in a row.

Some threading (or asyncio, etc?) on the Pulp Smash side of things may be necessary. Here's a simple example of threading: http://pastebin.com/4mripbxN

**Comment by preethit** [comment]
Yes it is a race condition, but something that I have seen reported multiple times. With us going into pulp 3.0 phase this may be a good test to have.
