### ISSUE TITLE
Test upload for srpm, comps.xml

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#402]
Taking a quick look at the existing tests and issues, seems like upload tests for srpm and comps.xml are missing.

  comps       - uploads comps.xml into a repository
  srpm        - uploads one or more SRPMs into a repository

Test case1
1. Create a repository A
2. Upload an srpm to the repository
3. Publish repository

Assert
1. The srpm can be uploaded
2. The repository with the srpm content can be published

Test case 2
1. Create a repository A
2. Upload a comps.xml to the repository
3. Publish repository

Assert
1. The comps.xml can be uploaded
2. The repository with the comps.xml content can be published

**Comment by Ichimonji10** [comment]
We upload SRPMs in `pulp_smash.tests.rpm.api_v2.test_signatures_checked_for_uploads`. That said, we can expand `pulp_smash.tests.rpm.api_v2.test_upload_publish` to better target this issue.

**Comment by preethit** [comment]
I am looking at the available options for uploads.

 pulp-admin rpm repo uploads
Usage: pulp-admin [SUB_SECTION, ..] COMMAND
Description: upload modules into a repository

Available Commands:
  cancel      - cancels an outstanding upload request
  category    - creates a new package category
  comps       - uploads comps.xml into a repository
  environment - creates a new package environment
  erratum     - creates a new erratum
  group       - creates a new package group
  langpacks   - creates a new package langpacks
  list        - lists in-progress and paused uploads
  resume      - resume a paused upload request
  rpm         - uploads one or more RPMs into a repository
  srpm        - uploads one or more SRPMs into a repository

Also for the other contents

I see these
pulp_smash.tests.rpm.api_v2.test_upload_publish
with rpm & errata
pulp_smash.tests.rpm.cli.test_upload
with drpm

**Comment by Ichimonji10** [comment]
Gotcha. Thanks!
