### ISSUE TITLE
Rename and skip python sync test for pulp_python version < 2.0

### ISSUE THREAD

**Issue by asmacdo** [PulpQE/pulp-smash#416]
Test to be renamed and skipped: 
https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/tests/python/api_v2/test_sync_publish.py#L12

It should be renamed to `PulpToPulpSyncTestCase` because it syncs from a fixture that was generated by a publish from pulp_python 2.0. Pulp to pulp sync is a new feature in 2.0.

**Comment by Ichimonji10** [comment]
What's the first version of Pulp that pulp_python 2.0 ships with?

**Comment by asmacdo** [comment]
Probably 2.11, but we haven't officially made a decision yet.

**Comment by Ichimonji10** [comment]
Thanks!
