### ISSUE TITLE
Sync distribution unit without requiring yum metadata

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#420]
Test
1. create a yum repo in pulp with a feed  such as https://ci.centos.org/artifacts/sig-atomic/centos-continuous/images-alpha/installer/latest/images/
2. sync the repo

Assert

The repo contains 1 distribution unit after the sync runs

fixtures repo may need to be extended to include repos  that has feeds such as these

https://ci.centos.org/artifacts/sig-atomic/centos-continuous/images-alpha/installer/latest/images/

**Comment by Ichimonji10** [comment]
See: https://pulp.plan.io/issues/2211
