### ISSUE TITLE
Test full sync with different scenarios- 

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#421]
https://pulp.plan.io/issues/1983
The sync should be full in case one of these answers are true:
1. Did the config change in any way since the last sync? 

Test case:1
1. Create a repo with feed
2. Sync the repo
3. Update the repo (For example add --serve-http true) to the repo
4. Run repo sync

Assert:
Check the last_updated to make sure that it's newer that what is in step #2
1. Has content been removed since the last sync?

Test case:2
1. Create a repo with feed
2. Sync the repo
3. Remove an rpm from the repo
4. Run repo sync

Assert:
Check the last_updated to make sure that it's newer that what is in step #2

Test case:3
1. Create a repo with feed
2. Sync the repo
3. Remove an rpm from the feed you are syncing from
4. Run repo sync

Assert:
Check the last_updated to make sure that it's newer that what is in step #2
1. If there was something specified in the override_config

Test Case #4 
1. Create a repo with feed
2. Sync the repo
3. Update the repo  change the override_config
4. Run repo sync

Assert:
Check the last_updated to make sure that it's newer that what is in step #2

Test Case #5
1. Force-full option was specified.
2. Create a repo with feed
3. Sync the repo
4. Update the repo to enable --force-full
5. Run repo sync

Assert:
Check the last_updated to make sure that it's newer that what is in step #2
1. Run repo sync again 

Assert:
Check the last_updated to make sure that it's newer that what is in step #4

**Comment by Ichimonji10** [comment]
What is the test that needs to be written? The numbered list above is a copy-paste from Pulp issue 1983, and it includes quite a bit of implementation detail, like database field names. More helpful would be something along the lines of "please ensure that Pulp performs a full sync when any of the following occur: ... Here's how you can be sure that a full sync occurs: ..."

**Comment by preethit** [comment]
@Ichimonji10 Yes it is a copy/paste and hence the label (Needs Work) not sure if it was the appropriate one. But a note to self to go back and clean up.

**Comment by Ichimonji10** [comment]
What we have now is usable, I think. Thanks for updating this issue!
