### ISSUE TITLE
Add ability to run automation through an authenticated Squid proxy

### ISSUE THREAD

**Issue by omaciel** [PulpQE/pulp-smash#426]
We need to be able to run our automation via a Pulp server that is sitting behind an authenticated Squid proxy

**Comment by preethit** [comment]
This is another issue that was written on this
https://github.com/PulpQE/pulp-smash/issues/285

**Comment by elyezer** [comment]
@preethit should we close this in favor of the other?

**Comment by preethit** [comment]
@elyezer I think so. Doesn't matter which one we keep. As long we have all the information needed in there.

**Comment by elyezer** [comment]
Closing this in favor of #285
