### ISSUE TITLE
Test repo docker tagging

### ISSUE THREAD

**Issue by daviddavis** [PulpQE/pulp-smash#436]
Per https://github.com/pulp/pulp_docker/pull/184 (https://pulp.plan.io/issues/2189), we added the ability to create or update docker tags in docker repositories. Suppose you have a busybox repo with a tag latest that points to manifest with digest `sha256:2824fe048727a69da66cf1be00cebd3bb9cfe1f238473693aa9358b411208527` and you wanted to point it to a manifest with digest `sha256:c152ddeda2b828fbb610cb9e4cb121e1879dd5301d336f0a6c070b2844a0f56d`, here's how you'd do that:

```
pulp-admin -v docker repo tag --repo-id busybox --tag-name latest --manifest-digest sha256:c152ddeda2b828fbb610cb9e4cb121e1879dd5301d336f0a6c070b2844a0f56d
```

You can also create new tags with the command like this would create a 'pulp' tag and point it to the same manifest:

```
pulp-admin -v docker repo tag --repo-id busybox --tag-name pulp --manifest-digest sha256:c152ddeda2b828fbb610cb9e4cb121e1879dd5301d336f0a6c070b2844a0f56d
```

Test Plan
---------
Given a docker repo, update an existing tag by pointing it to the manifest. 
- [ ] Validate that the tag was updated and is now pointing to the correct manifest.
- [ ] Check correct tag count in the repo ( should not change)

Given a docker repo, create a new tag and point it to a manifest. 
- [ ] Validate that the tag now exists and is pointing to the correct manifest.
- [ ] Check correct tag count in the repo ( should increase by 1)

Point a tag to a digest that doesn't have a manifest with the particular digest in pulp
- [ ] Check that an error is displayed to the user.

Point a tag to a manifest digest in another repo 
- [ ] Check that an error is displayed to the user

**Comment by ipanova** [comment]
Point a tag to a manifest digest that exists(but not in the repo you are pointing the tag)
- check that an error is displayed to the user

**Comment by daviddavis** [comment]
@ipanova thanks. I updated the test plan.
