### ISSUE TITLE
Test orphan remove reports the number of removed unit types

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#459]
Add tests to verify that orphan remove reports the number of units removed per unit type.
https://pulp.plan.io/issues/1268

For example

1. Create a repo with 3 rpms
2. Sync and publish the repo
3. Delete the repo
4. Assert that there are 3 rpms in the orphaned state
5. Run orphan remove
6. Assert that the report says that 3 rpm units were removed

**Comment by Ichimonji10** [comment]
Note to test implementers: I think we have a test that does steps 1 through 5 already.

**Comment by Ichimonji10** [comment]
Test ready at: https://github.com/PulpQE/pulp-smash/compare/master...Ichimonji10:orphan-counts?expand=1
