### ISSUE TITLE
Test remove_missing and retain_old_count in lazy sync (on_demand/background)

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#463]
Expand these tests to cover lazy sync repos

* https://pulp.plan.io/issues/2503
* https://pulp-smash.readthedocs.io/en/latest/api/pulp_smash.tests.rpm.api_v2.test_retain_old_count.html
* https://pulp-smash.readthedocs.io/en/latest/api/pulp_smash.tests.rpm.api_v2.test_remove_unit.html

**Comment by preethit** [comment]
@Ichimonji10 May be I was not looking at all the places,  are these tests added for tests with on_demand/background down load policy as well?

**Comment by Ichimonji10** [comment]
[Pulp #2503](https://pulp.plan.io/issues/2503) describes a situation where the on_demand and remove_missing options interact in an unexpected and bad way. If as the goal of this Pulp Smash issue is to test [Pulp #2503](https://pulp.plan.io/issues/2503), we're done. The relevant tests are here: https://pulp-smash.readthedocs.io/en/latest/api/pulp_smash.tests.rpm.api_v2.test_remove_unit.html

There's some existing tests for the retain_old_count and background options, though in other modules, and for different scenarios.

**Comment by preethit** [comment]
Thanks for pointing me to those tests. I was missing the test_04_sync_on_demand_child()
