### ISSUE TITLE
Test that when pulp syncs from pulp_distribution.xml the repodata directory is ignored

### ISSUE THREAD

**Issue by werwty** [PulpQE/pulp-smash#476]
https://pulp.plan.io/issues/1086

Test that when pulp syncs from pulp_distribution.xml the repodata directory is ignored

1. Create a repo with feed `pulp-admin rpm repo create --repo-id=test_dist_sync --feed=http://cdn.stage.redhat.com/content/dist/rhel/server/7/7.0/x86_64/kickstart`
This kickstart has the `repodata/productid` included in pulp_distribution.xml but not in `repodata/repomd.xml` 

2. sync the repo

3. validate that `repodata/productid` has not been synced

**Comment by Ichimonji10** [comment]
Whenever this issue is tackled: consider creating a corresponding [Pulp Fixtures](http://github.com/PulpQE/pulp-fixtures/) fixture.

**Comment by elyezer** [comment]
https://github.com/PulpQE/pulp-fixtures/pull/50 will add the required fixtures
