### ISSUE TITLE
Additional updateinfo.xml after second publish

### ISSUE THREAD

**Issue by omaciel** [PulpQE/pulp-smash#480]
Please see more info [here](https://pulp.plan.io/issues/2096)

**Comment by goosemania** [comment]
This issue covers only the incremental publish case.
After upgrade old updateinfo.xml are not deleted from the filesystem with the next incremental publish. Only after full re-publish there will be exactly one updateinfo.xml file.

So for the test one can:
- either do full re-publish first and then trigger the incremental one
- or expect old updateinfo.xml files to be where they were and only the latest file will be substituted with the new one with the next incremental publish.
