### ISSUE TITLE
Test that pulp to pulp sync for python packages work

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#493]
https://pulp.plan.io/issues/140

1. Create  python repoA with feed
2. Sync repoA
3. Create repoB with --feed repoA
4. Run Sync
Assert: Sync is success

1. Create  python repoA with no feed
2. Upload content to the repo
3. Publish the repo
4. Create repoB with --feed repoA
5. Run Sync
Assert: Sync is success

**Comment by Ichimonji10** [comment]
@dkliban clarified that, for this issue to be fully tested, we need to sync from one Pulp application to another completely independent Pulp application.
