### ISSUE TITLE
Test the puppet install distributor subdir option

### ISSUE THREAD

**Issue by werwty** [PulpQE/pulp-smash#495]
https://pulp.plan.io/issues/2108

Docs here: http://docs.pulpproject.org/en/nightly/plugins/pulp_puppet/tech-reference/plugin_conf.html#install-distributor
Release notes here: http://docs.pulpproject.org/en/nightly/plugins/pulp_puppet/user-guide/release-notes/2.13.x.html#pulp-puppet-2-13-0

## Validate subdir creation
1. `pulp-admin puppet repo create --repo-id=repo1`
2. `pulp-admin puppet repo uploads upload --file puppetlabs-apache-1.11.0.tar.gz --repo-id repo1`
3. `curl --user admin:admin --data '{"distributor_type_id":"puppet_install_distributor", "distributor_id":"puppet_tmp_install_distributor", "distributor_config": {"install_path":"/etc/puppet/environments/MYENV", "subdir":"modules"}}' https://dev.example.com/pulp/api/v2/repositories/repo1/distributors/`
4. `curl --user admin:admin --data '{"id": "puppet_tmp_install_distributor"}' https://dev.example.com/pulp/api/v2/repositories/repo1/actions/publish/`
5. validate that `/etc/puppet/environments/MYENV/modules` exists
6. `pulp-admin puppet repo delete --repo-id=repo1`
7. validate that `/etc/puppet/environments` has no directory MYENV in it

## Validate update existing repo with subdir
1. `pulp-admin puppet repo create --repo-id=repo2`
2. `pulp-admin puppet repo uploads upload --file puppetlabs-apache-1.11.0.tar.gz --repo-id repo2`
3. `curl --user admin:admin --data '{"distributor_type_id":"puppet_install_distributor", "distributor_id":"puppet_tmp_install_distributor", "distributor_config": {"install_path":"/etc/puppet/environments/MYENV2/modules"}}' https://dev.example.com/pulp/api/v2/repositories/repo2/distributors/`
4. `curl  -X PUT  --user admin:admin --data '{"distributor_configs": {"puppet_tmp_install_distributor": {"install_path":"/etc/puppet/environments/MYENV2", "subdir": "modules2"}}}' https://dev.example.com/pulp/api/v2/repositories/repo2/`
5. `curl --user admin:admin --data '{"id": "puppet_tmp_install_distributor"}' https://dev.example.com/pulp/api/v2/repositories/repo2/actions/publish/`
6. validate that `/etc/puppet/environments/MYENV2/modules2` exists
7. `pulp-admin puppet repo delete --repo-id=repo2`
8. validate that `/etc/puppet/environments` has no directory MYENV2 in it

**Comment by elyezer** [comment]
Move to 2.13 milestone because the related story will land on that release according to https://pulp.plan.io/issues/2108#note-22.
