### ISSUE TITLE
Expand "Destructiveness" section in documentation

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-smash#5]
The *Pulp Smash* → *About* → *Scope and Limitations* → [*Destructiveness*](http://pulp-smash.readthedocs.org/en/latest/about.html#destructiveness) section in the documentation should be expanded. That section currently states:

> Should Pulp Smash record all changes it makes to a remote system and revert them when testing is complete, or should systems be treated as throw-away? In other words, should the systems under test be treated like pets or cattle? [3] This has yet to be decided.

It would be good to decide this so that we can adapt tests from the existing Pulp Automation test suite with confidence.

<del>(I have not yet hooked Pulp Smash in to Read The Docs. In the mean time, you can generate the documentation by getting a copy of the source code, installing necessary dependencies and executing `make docs-html`.)</del>

**Comment by Ichimonji10** [comment]
Documentation is now available on Read The Docs. See [here](http://pulp-smash.readthedocs.org/en/latest/).

**Comment by elyezer** [comment]
If cleaning the environment is a must, then using a throw away approach is better. Cleaning data is not reliable as throwing the system because the clean endpoints could fail and this will bring us another point what to do when this happens?

**Comment by sthirugn** [comment]
Although this gives a clean slate for every test, IMO cleaning up the environment after each test will not more closely resemble a customer environment as it may have ton of data.

**Comment by sthirugn** [comment]
May be mix and match is an option - some tests can run clean slate (at the start of the job) and others can run without it.

**Comment by Ichimonji10** [comment]
As per this morning's meeting, we're going to aim for the following approach:

* We will perform a clean-up before each test case or test module executes. This allows each test to execute with a greater level of isolation.
* The clean-up should be performed at the database level. This approach will leave files lying around on disk, but developers (e.g. @bmbouter) already use this approach, and it works fairly well. Also, resetting the database is a more sure-fire approach than performing ad-hoc cleanup in each individual test.
* It may be possible to create a new database each time this clean-up code is called. This would allow for Pulp Smash to be run against a system without totally destroying that system. (It might also allow for test isolation *and* parallelization.)

 I'm thinking that we can make the clean-up code available via both a function and as a mixin. Having the clean-up code available as a function would allow it to be executed at any arbitrary time, and having a mixin makes it very easy to include or exclude the clean-up code as needed.

**Comment by bmbouter** [comment]
I am planning to make a class that inherits from `TestCase` and will perform the database destroying in the setUpClass method. Other test classes can inherit from this class to receive this behavior. @Ichimonji10 Does this sound right?

**Comment by Ichimonji10** [comment]
Yes, this sounds about right. I do have a couple thoughts, though.

First, it may be advantageous to write this code as a set of functions, then call them from whatever class inherits from `TestCase`. The point of isolating the code like this is to make it more easily unit tested and re-used. Here's a rough sketch:

```python
from unittest2 import TestCase
from pulp_smash.config import get_config

def reset_database(hostname, username=None):
    """Reset the Pulp database.

    :param hostname: A string. The hostname of the system running Pulp's database. For example: 'pulp-db.example.com'
    :param username: A string. This user is used when logging in to the remote system.
    """


def ResetDatabaseTestCase(TestCase):

    @classmethod
    def setUpClass(cls):
        cfg = get_config()
        # derive hostname, username from config
        reset_database(hostname, username)
```

There's quite a few nit-picks that need to be ironed out. Is the "ssh" section required? I don't imagine it needs to be. The "verify" section isn't required either, and we can provide a default value of `{}`. The `ServerConfig` class could go even further and provide default "hostname" and "username" values, though I'm not sure if that's an optimal direction to go.

Also, there's the question of how to lay out the config file. We could do something like this:

```json
{
    "default": {
        "base_url": "https://localhost",
        "ssh": {
            "hostname": "localhost",
            "username": "bmbouter"
        },
        "auth": [
            "admin",
            "admin"
        ],
        "verify": false
    }
}
```

But why do we have a `base_url` and `hostname`? They're duplicates. Yes, you can argue that the database could be on a separate system from the one pointed at by `base_url`. But in that case, shouldn't you have a new section entirely? What happens if you want SSH credentials for your base Pulp system, your database system and a third system? Something like this would work a little better:

In `settings.json` (really should be named `pulp_settings.json` or something else.)

```json
{
    "default": {
        "base_url": "https://localhost",
        "auth": [
            "admin",
            "admin"
        ],
        "verify": false
    }
}
```

In `database_settings.json`:
```json
{
    "default": {
        "hostname": "pulp-db.example.com"
        "username": "hank",
        "verify": false
    }
}
```

That would be more true to the idea that configuration files should represent facts about the real world as closely and obviously as possible.

**Comment by Ichimonji10** [comment]
IIRC, there can be only one Pulp database, right? If that's the case, then maybe something like this would be more appropriate:

```json
{
    "default": {
        "base_url": "https://localhost",
        "auth": [
            "admin",
            "admin"
        ],
        "database": {
            "hostname": "pulp-db.example.com",
            "username": "pulp-db-admin"
        },
        "verify": false
    }
}
```

And the `database` section does not need to be specified in the configuration file. In the application itself, `hostname` can be inferred from `base_url` if omitted, and `username` can be taken from the environment if omitted.

**Comment by elyezer** [comment]
I like the `ResetDatabaseTestCase`, it makes clear what we should expect for a particular TestCase.

**Comment by Ichimonji10** [comment]
The discussion in #78 is relevant.

**Comment by Ichimonji10** [comment]
I realize now that, though we have come up with a solution for this issue, we never actually edited the documentation.
