### ISSUE TITLE
RPM rsync distributor test should assert repository layout

### ISSUE THREAD

**Issue by dkliban** [PulpQE/pulp-smash#506]
The rsync distributor test should assert that the published repository on the remote server has the same layout as the repository published by the yum distributor. The repository should contain 2 directories: repodata and Packages. Packages directory should contain a directory for each letter of the alphabet for which there is a package that starts with that letter. Each letter directory should contain packages whose names start with that letter.

**Comment by kersommoura** [comment]
See also: [Test rsync distributor](https://github.com/PulpQE/pulp-smash/blob/e75e91c25398d13ba03532403de486d424598df6/pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py)
