### ISSUE TITLE
Files ending in .gz are delivered with incorrect content headers

### ISSUE THREAD

**Issue by elyezer** [PulpQE/pulp-smash#521]
Files ending in .gz served up by pulp.server.content.web.views are served with an incorrect content type and encoding.

This affects .xml.gz files generated by yum-distributor. For example:

```
$ curl -v http://192.168.121.51/pulp/repos/f04a1d5b-32d8-4a60-a580-cc158ab25004/repodata/5f90923d6f2e4b3d0f27c13e927821b9a7001b349f99222752c37496a40531d8-updateinfo.xml.gz > /dev/null
*   Trying 192.168.121.51...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 192.168.121.51 (192.168.121.51) port 80 (#0)
> GET /pulp/repos/f04a1d5b-32d8-4a60-a580-cc158ab25004/repodata/5f90923d6f2e4b3d0f27c13e927821b9a7001b349f99222752c37496a40531d8-updateinfo.xml.gz HTTP/1.1
> User-Agent: curl/7.40.0
> Host: 192.168.121.51
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Thu, 17 Mar 2016 03:24:50 GMT
< Server: Apache/2.4.18 (Fedora) OpenSSL/1.0.2g-fips mod_wsgi/4.4.8 Python/2.7.10
< Last-Modified: Thu, 17 Mar 2016 00:57:43 GMT
< ETag: "278-52e341e355108" 
< Content-Length: 632
< Content-Type: text/xml
< 
```

The server incorrectly claims that the response content is Content-Type: text/xml, with no Content-Encoding. It should be: Content-Type: text/xml, Content-Encoding: gzip.

For more information check https://pulp.plan.io/issues/1781

**Comment by preethit** [comment]
Test case- 1 Sync

1. Create and sync the yum  "rpm-signed" from fixtures
2. Curl -v GET --insecure https://localhost/pulp/repos/pulp/pulp/fixtures/rpm-signed/repodata/<name>-updateinfo.xml.gz
3. Check to see the Content-Type: is gzip
  Comment from commit: # Most OSes return the 'gzip' version, but some (el6) return 'x-gzip'. Either is fine.

Test Case2 upload

1. Create a yum repo
2. Upload content (rpm)
3. Publish the repo
4. Check the content type the updateinfo.xml.gz

**Comment by preethit** [comment]
Related issue
https://pulp.plan.io/issues/2618
