### ISSUE TITLE
RPM import traceback (non-utf-8 metadata slipping through)

### ISSUE THREAD

**Issue by elyezer** [PulpQE/pulp-smash#524]
Observation: there is logic to deal with UTF-8 characters when syncing but not when uploading a RPM.

For more information see: https://pulp.plan.io/issues/1903

**Comment by preethit** [comment]
https://pulp.plan.io/issues/2622

**Comment by Ichimonji10** [comment]
Automating this issue requires that we upload an RPM that includes non-utf8 data in its header. Creating such a package requires that a `.spec` including this kind of data file be written, and that an RPM package be created from that.

Right now, I don't know how to create RPM packages, and I've fallen back to automating this issue manually. I can automate this issue after learning more about RPM packaging. Alternately, someone else with the relevant knowledge could add the necessary RPM to Pulp Fixtures.

**Comment by elyezer** [comment]
@Ichimonji10 talked with @goosemania and she recommended this link http://www.redhat.com/archives/rpm-list/2006-April/msg00015.html

Then after creating the spec, rpmbuild should be run.
