### ISSUE TITLE
rsync distributor without force_full incorrectly skips publishing some units

### ISSUE THREAD

**Issue by elyezer** [PulpQE/pulp-smash#526]
Using a yum repo as an example, here's a sequence of events which demonstrates the problem:

1. Create a yum repository, and populate it with some content.
2. Publish the repository with a yum distributor.
3. Add additional content to the repository.
4. Publish the repository with an rsync distributor. (This publish will not include the new unit, since a yum publish hasn't happened for the unit.)
5. Publish the repository with a yum distributor.
6. Publish the repository with an rsync distributor. (This publish should include the new unit, since a yum publish has happened for the unit.)

For more information see: https://pulp.plan.io/issues/2532

**Comment by preethit** [comment]
Related issue 
https://pulp.plan.io/issues/2550#note-5
