### ISSUE TITLE
Test recent pulp syncing to SuSE repositories

### ISSUE THREAD

**Issue by elyezer** [PulpQE/pulp-smash#527]
It will likely to require a fixture that will simulate a SUSE repository.

For more information see: https://pulp.plan.io/issues/2383

**Comment by seandst** [comment]
So far, and as far as I can tell, the official SUSE repositories are normal `createrepo`(/`createrepo_c`) repos that pulp can consume without any modification.

**Comment by Ichimonji10** [comment]
Cool. If that's the case, we can just close this issue.

**Comment by elyezer** [comment]
I agree with @Ichimonji10 we can just close this issue.

**Comment by omaciel** [comment]
@Ichimonji10 @elyezer @seandst I feel that we should test this against a real SUSE repo "just in case".

**Comment by elyezer** [comment]
@omaciel I will sync on upgrade job, does that suffice?

**Comment by Ichimonji10** [comment]
FYI: https://en.opensuse.org/Package_repositories

We wouldn't want to sync an entire repo, due to size concerns.

**Comment by omaciel** [comment]
@elyezer not sure if I missed something (if I have, my apologies) but this task is not related to upgrades but to check that SUSE packages (though they are RPMs) can be properly synced?

**Comment by elyezer** [comment]
@omaciel it is related on doing that. But it is required a subscription of the SUSE enterprise linux and manual testing was done to ensure it works. We can try to sync the OpenSUSE repos but I would recommend doing that on upgrade since the repos are big and automation is meant to be faster so we can catch regression ASAP.

My proposal to do that on upgrade is because we will not do that every day (but twice a week) and will ensure we can sync the enterprise Linux packages. Also the SUSE project is using `createrepo` to generate their repositories, same way as done for the YUM repos we have on fixtures so we are already testing that on Pulp Smash via fixtures.

The difference is how to get the authentication token for the enterprise linux, for RHEL we have a certificate which can be imported into Pulp and that will allow to sync RHEL repos from CDN. On the other hand, for SUSE, we have to consult an API for an authentication token and pass that authentication token to Pulp so it can download the SUSE EL packages.

**Comment by preethit** [comment]
@omaciel I agree with the proposal from @elyezer. It make sense to test this one with upgrade for all the reasons @elyezer has mentioned. 

There has not been any specific code change needed for this. So we just need to make sure that SUSE content can be synced , just like we make sure that cdn content can be synced in upgrade.
