### ISSUE TITLE
Fast-forward yum publish skips units if previous publish was cancelled

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#536]
https://pulp.plan.io/issues/2263
More info

1. Trigger yum distributor on repo, allow it to succeed.
2. Trigger yum distributor on repo.
3. Cancel task from previous step after it starts but before it publishes the RPMs (may have to be quick)
4. Trigger yum distributor on repo, allow it to succeed.

**Comment by Ichimonji10** [comment]
@elyezer and I looked at this bug. We don't think it's a good idea to try automating it, on account of the fact that testing this issue requires very exact timing, and the time window varies based on the nature of the test environment used, especially the storage medium used. (In my case, my Pulp VMs are backed by a Samsung 850 EVO SSD, and it's capable of over 10k IOPS at a queue depth of 1.) The comments show that testing the issue involves adding some calls to `time.sleep()` into Pulp's own code.

**Comment by preethit** [comment]
@Ichimonji10 Thanks for the explanation. I will close this one.
