### ISSUE TITLE
Empty pkglist for the erratum may be generated which may cause yum not to find applicable packages

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#540]
https://pulp.plan.io/issues/2559

Look in redmine for more info. I will try to come up with steps to test this.

**Comment by preethit** [comment]
https://github.com/PulpQE/pulp-smash/commit/96dc91a6c23eb29f620bdd2bb11abb28747353ec

**Comment by Ichimonji10** [comment]
I just need to submit one more PR, and all of the errata tests should be fixed.

**Comment by Ichimonji10** [comment]
https://github.com/PulpQE/pulp-smash/commit/96dc91a6c23eb29f620bdd2bb11abb28747353ec and https://github.com/PulpQE/pulp-smash/commit/9bd4aec75a5ea9b3bb3e29489f53b1841536c097 fix this issue.
