### ISSUE TITLE
Test os-tree copy repo

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#543]
https://pulp.plan.io/issues/2544

Create as OSTree Repo
Sync the repo
Create a 2nd ostree repo
Copy repo1 to repo2 with filter

Assert that copy is done with filter

**Comment by Ichimonji10** [comment]
@kersommoura @kdelee This test case is easy. Copying data between repositories is as easy as:

```python
api.Client(cfg).post(urljoin(dest_repo['_href'], 'actions/associate/'), {
    'source_repo_id': src_repo_id
})
```

For a fuller example of how to copy data between repos, see [`pulp_smash.tests.rpm.api_v2.test_signatures_checked_for_copies`](https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/tests/rpm/api_v2/test_signatures_checked_for_copies.py).

**Comment by kersommoura** [comment]
I will work at this issue @kdelee.
