### ISSUE TITLE
Test that upload fails and error is raised with uploading invalid rpm

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#544]
https://pulp.plan.io/issues/2543
 Upload an invalid rpm
Assert that an error is raised when it fails

**Comment by preethit** [comment]
https://pulp.plan.io/issues/3090
@kersommoura  @Ichimonji10 With 2 bugzillas attached, could prioritize this for automation?

**Comment by kersommoura** [comment]
@preethit I will work on it.
