### ISSUE TITLE
Test last_unit_added is updated when units are copied over from another repo

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#550]
https://pulp.plan.io/issues/2577
See this is an extension of this 
https://github.com/PulpQE/pulp-smash/issues/461

pulp-admin rpm repo create --repo-id=test

pulp-admin rpm repo copy rpm --from-repo-id=zoo --to-repo-id=test

pulp-admin rpm repo search --str-eq "id=test

**Comment by ipanova** [comment]
Scenario1:

    Create a repository with feed and sync it
    Assert that the last_unit_added gets updated

Scenario2
    Create a repository with feed and sync it
    Create second repo
    Copy content from first repo to second repo
    Assert that the last_unit_added gets updated on the second repo

**Comment by preethit** [comment]
Related to
https://github.com/PulpQE/pulp-smash/issues/461
