### ISSUE TITLE
Verifying Pulp 2.y compatability with Celery 3.1, Kombu 3.0 AND Celery 4.0, Kombu 4.0

### ISSUE THREAD

**Issue by bmbouter** [PulpQE/pulp-smash#564]
This is a verification for [Issue 2527](https://pulp.plan.io/issues/2527). This change should allow pulp smash to show the same results in an environment like this which will come with F26:

```
amqp==2.1.4
billiard==3.5.0.2
celery==4.0.2
kombu==4.0.2+a patch to be released via RPM in Fedora
vine==1.1.3
```

Versus a typical environment today on other distros:

```
amqp==1.4.9
billiard==3.3.0.23
celery==3.1.20
kombu==3.0.33
```

To test this we use Pulp smash by running them on both environments.

Smash an F26 Environment
------------------------------------

1. On a fresh rpm installation in an F26 environment, ensure the following packages are installed via RPM and come from the Fedora base or updates repos: amqp, billiard, celery, kombu, and vine. This should deliver the "new" dependency stack.
2. Run pulp-smash and record any failures

Smash a F25 Environment
----------------------------------
1. This should have the old dependency stack with an rpm based install.
2. Run pulp-smash and record any failures.

**Comment by Ichimonji10** [comment]
To recap a few points from the linked-to issue and around the web:

* The F26 beta freeze is scheduled for 2017-04-28, and the release is scheduled for 2017-06-13.
* It's unlikely that Pulp 3 will be ready in time for the beta freeze.
* It's likely that Pulp 2 will be ready in time for the beta freeze.

The linked-to Pulp issue is really concerned with the question of "will Pulp 2 work with F26?"

**Comment by bmbouter** [comment]
Pulp3 will only support Celery4 and Kombu4 so Pulp2 is the only release stream that needs to support both. I think the linked-to issue is also concerned with regression testing to ensure "did we break anything in F25- or EL7. We get that from pulp-smash regular runs, but note, we have codepaths that are new and only triggered when the fix is present and you are running with the Celery3.1+Kombu3.0 stack so I wanted to highlight here.

**Comment by kersommoura** [comment]
Closing this issue. 

Pulp 2 is currently in version 2.16.1.

Pulp 3 is currently using RQ instead of Celery. See: https://github.com/pulp/pulp/pull/3454

In case of need, feel free to re-open it.
