### ISSUE TITLE
Search tests update

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#567]
Update search tests to include this criteria. https://pulp.plan.io/issues/2603

use the search API against a repo.

sort the results descending by the association's created field.
 call like:

```python
self._req(
    'POST',
    'repositories/%s/search/units/' %·
    repo_id,
    data={
        'criteria': {
            u'sort': {'association': [[u'created', u'descending']]},
            'limit': 1000,
            'filters': {'unit': {}},
            u'fields': {'unit': [
                u'name',
                u'pulp_user_metadata',
                u'sadName',
                u'unitName',
                u'unitType',
                u'version'
            ]},
            'type_ids': ['ddf']
        }
    },
    expected=200,
    safe_retry=True
).json()
```

**Comment by Ichimonji10** [comment]
The issue at hand is that too few content units are returned in response to a search query where:

* search results are ordered
* search results are not filtered

I've asked for an example of a search query that behaves as expected.

Beware that this issue won't be fixed until Pulp 3.
