### ISSUE TITLE
Tests to capture deprecation warning while running pulp-manage-db

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#568]
@Ichimonji10 Not sure if we have tests that capture issues during pulp-manage-db. Please update/close this if you think this is a new area we need to add.

https://pulp.plan.io/issues/2599

**Comment by elyezer** [comment]
The `pulp-manage-db` is called before running Pulp Smash (during Pulp server installation). Not sure if having a test for that and also checking for logs would be something Pulp Smash would cover.

**Comment by preethit** [comment]
@elyezer make sense, Thank you!

**Comment by Ichimonji10** [comment]
I don't understand how to reproduce the issue reported in [Pulp #2599](https://pulp.plan.io/issues/2599). Is the deprecation warning emitted every time `pulp-manage-db` is executed?

**Comment by preethit** [comment]
@Ichimonji10 yes that is my understanding. when pulp-manage-db is run, the depreciation warnings are listed.

**Comment by Ichimonji10** [comment]
Thanks for the clarification, @preethit.

We can automate this issue on our systemd platforms by executing `date` on the target system before and after executing `pulp-manage-db`, and then executing `journalctl --since=... --until=...` to get logs from that time frame. The automated tests on SysV platforms are likely to be harder to write and less robust anyway.

Despite all this, Pulp Smash doesn't currently have any automated tests that munge log files. The reason is simple: log messages are prose, and are subject to change at any time without notice. This makes it easy to write an automated test that produces false positives or false negatives. (What happens if the system locale changes?) This is a case where I think a human's ability to reason and intuit is very useful.

**Comment by preethit** [comment]
@Ichimonji10 Thanks for the explanation. I do understand why pulp smash doesn't have automated test that deal with log files and that makes complete sense to me. 

The reason for asking the question for this case was because, when I run pulp-manage-db we can watch the migration running at the CLI itself. So I assumed this case will be different than how you handle checking the log for failures. 

here is an example.
[root@mgmt4 ~]# sudo -u apache pulp-manage-db
Attempting to connect to localhost:27017
Attempting to connect to localhost:27017
Write concern for Mongo connection: {}
/usr/lib/python2.6/site-packages/pulp/server/db/connection.py:159: DeprecationWarning: add_son_manipulator is deprecated
  _DATABASE.add_son_manipulator(NamespaceInjector())
Loading content types.
Loading type descriptors []
Parsing type descriptors
Validating type descriptor syntactic integrity
Validating type descriptor semantic integrity
Loading unit model: docker_blob = pulp_docker.plugins.models:Blob
Loading unit model: docker_manifest = pulp_docker.plugins.models:Manifest
Loading unit model: docker_image = pulp_docker.plugins.models:Image
Loading unit model: docker_tag = pulp_docker.plugins.models:Tag
Loading unit model: python_package = pulp_python.plugins.models:Package
Loading unit model: puppet_module = pulp_puppet.plugins.db.models:Module
Loading unit model: erratum = pulp_rpm.plugins.db.models:Errata
Loading unit model: distribution = pulp_rpm.plugins.db.models:Distribution
Loading unit model: srpm = pulp_rpm.plugins.db.models:SRPM
Loading unit model: package_group = pulp_rpm.plugins.db.models:PackageGroup
Loading unit model: package_category = pulp_rpm.plugins.db.models:PackageCategory
Loading unit model: iso = pulp_rpm.plugins.db.models:ISO
Loading unit model: package_environment = pulp_rpm.plugins.db.models:PackageEnvironment
Loading unit model: drpm = pulp_rpm.plugins.db.models:DRPM
Loading unit model: package_langpacks = pulp_rpm.plugins.db.models:PackageLangpacks
Loading unit model: rpm = pulp_rpm.plugins.db.models:RPM
Loading unit model: yum_repo_metadata_file = pulp_rpm.plugins.db.models:YumMetadataFile
Updating the database with types []
/usr/lib/python2.6/site-packages/pulp/server/db/model/base.py:96: DeprecationWarning: ensure_index is deprecated. Use create_index instead.
  unique=unique, background=True)
Found the following type definitions that were not present in the update collection [puppet_module, drpm, package_langpacks, erratum, docker_blob, docker_manifest, yum_repo_metadata_file, package_group, package_category, iso, package_environment, docker_tag, python_package, srpm, rpm, distribution, docker_image]
Updating the database with types [puppet_module, drpm, package_langpacks, docker_manifest, docker_blob, erratum, yum_repo_metadata_file, package_group, package_category, iso, package_environment, docker_tag, python_package, distribution, rpm, srpm, docker_image]
/usr/lib/python2.6/site-packages/pulp/plugins/types/database.py:277: DeprecationWarning: save is deprecated. Use insert_one or replace_one instead
  content_type_collection.save(content_type)
Content types loaded.
Ensuring the admin role and user are in place.
Admin role and user are in place.
Beginning database migrations.
Migration package pulp.server.db.migrations is up to date at version 27
Migration package pulp_docker.plugins.migrations is up to date at version 2
Migration package pulp_puppet.plugins.migrations is up to date at version 5
Applying pulp_python.plugins.migrations version 2
/usr/lib/python2.6/site-packages/pulp_python/plugins/migrations/0002_smaller_model_for_json.py:53: DeprecationWarning: update is deprecated. Use replace_one, update_one or update_many instead.
  collection.update({"$and": [sdist_filetype, no_packagetype]}, set_sdist, multi=True)
/usr/lib/python2.6/site-packages/pulp_python/plugins/migrations/0002_smaller_model_for_json.py:27: DeprecationWarning: update is deprecated. Use replace_one, update_one or update_many instead.
  collection.update({}, {"$unset": {"home_page": True}}, multi=True)
/usr/lib/python2.6/site-packages/pulp_python/plugins/migrations/0002_smaller_model_for_json.py:28: DeprecationWarning: update is deprecated. Use replace_one, update_one or update_many instead.
  collection.update({}, {"$unset": {"platform": True}}, multi=True)
/usr/lib/python2.6/site-packages/pulp_python/plugins/migrations/0002_smaller_model_for_json.py:29: DeprecationWarning: update is deprecated. Use replace_one, update_one or update_many instead.
  collection.update({}, {"$unset": {"license": True}}, multi=True)
/usr/lib/python2.6/site-packages/pulp_python/plugins/migrations/0002_smaller_model_for_json.py:30: DeprecationWarning: update is deprecated. Use replace_one, update_one or update_many instead.
  collection.update({}, {"$unset": {"_metadata_file": True}}, multi=True)
/usr/lib/python2.6/site-packages/pulp_python/plugins/migrations/0002_smaller_model_for_json.py:31: DeprecationWarning: update is deprecated. Use replace_one, update_one or update_many instead.
  collection.update({}, {"$unset": {"description": True}}, multi=True)
/usr/lib/python2.6/site-packages/pulp_python/plugins/migrations/0002_smaller_model_for_json.py:32: DeprecationWarning: update is deprecated. Use replace_one, update_one or update_many instead.
  collection.update({}, {"$unset": {"author_email": True}}, multi=True)
/usr/lib/python2.6/site-packages/pulp_python/plugins/migrations/0002_smaller_model_for_json.py:34: DeprecationWarning: update is deprecated. Use replace_one, update_one or update_many instead.
  collection.update({}, {"$rename": {"_filename": "filename"}}, multi=True)
/usr/lib/python2.6/site-packages/mongoengine/document.py:367: DeprecationWarning: update is deprecated. Use replace_one, update_one or update_many instead.
  upsert=upsert, **write_concern)
Migration to pulp_python.plugins.migrations version 2 complete.
Applying pulp_rpm.plugins.migrations version 37
Migration to pulp_rpm.plugins.migrations version 37 complete.
Applying pulp_rpm.plugins.migrations version 38
Migration to pulp_rpm.plugins.migrations version 38 complete.
Loading unit model: docker_blob = pulp_docker.plugins.models:Blob
Loading unit model: docker_manifest = pulp_docker.plugins.models:Manifest
Loading unit model: docker_image = pulp_docker.plugins.models:Image
Loading unit model: docker_tag = pulp_docker.plugins.models:Tag
Loading unit model: python_package = pulp_python.plugins.models:Package
Loading unit model: puppet_module = pulp_puppet.plugins.db.models:Module
Loading unit model: erratum = pulp_rpm.plugins.db.models:Errata
Loading unit model: distribution = pulp_rpm.plugins.db.models:Distribution
Loading unit model: srpm = pulp_rpm.plugins.db.models:SRPM
Loading unit model: package_group = pulp_rpm.plugins.db.models:PackageGroup
Loading unit model: package_category = pulp_rpm.plugins.db.models:PackageCategory
Loading unit model: iso = pulp_rpm.plugins.db.models:ISO
Loading unit model: package_environment = pulp_rpm.plugins.db.models:PackageEnvironment
Loading unit model: drpm = pulp_rpm.plugins.db.models:DRPM
Loading unit model: package_langpacks = pulp_rpm.plugins.db.models:PackageLangpacks
Loading unit model: rpm = pulp_rpm.plugins.db.models:RPM
Loading unit model: yum_repo_metadata_file = pulp_rpm.plugins.db.models:YumMetadataFile
Database migrations complete.
[root@mgmt4 ~]#

**Comment by Ichimonji10** [comment]
Ahh, I understand now. We're not looking for a message in the logs, but a message in stdout or stderr.
