### ISSUE TITLE
Test the errata collection names are unique per-repo

### ISSUE THREAD

**Issue by seandst** [PulpQE/pulp-smash#569]
Due to how yum merges package lists in errata, we needed this: https://pulp.plan.io/issues/2560

Practically, this is what the change looks like. Given this pkglist in an errata:
```xml
    <pkglist>
      <collection short="">
        <name></name>
        <package arch="noarch" epoch="0" name="walrus" release="1" src="http://www.fedoraproject.org" version="5.21">
          <filename>walrus-5.21-1.noarch.rpm</filename>
        </package>
        <package arch="noarch" epoch="0" name="penguin" release="1" src="http://www.fedoraproject.org" version="0.9.1">
          <filename>penguin-0.9.1-1.noarch.rpm</filename>
        </package>
        <package arch="noarch" epoch="0" name="shark" release="1" src="http://www.fedoraproject.org" version="0.1">
          <filename>shark-0.1-1.noarch.rpm</filename>
        </package>
      </collection>
    </pkglist>
    <pkglist>
```

Pulp should modify it, so that the `<pkglist><collection><name>` is unique among errata with the same ID published in other repos:
```xml
    <pkglist>
      <collection short="">
        <name>unique</name>
        <package arch="noarch" epoch="0" name="walrus" release="1" src="http://www.fedoraproject.org" version="5.21">
          <filename>walrus-5.21-1.noarch.rpm</filename>
        </package>
        <package arch="noarch" epoch="0" name="penguin" release="1" src="http://www.fedoraproject.org" version="0.9.1">
          <filename>penguin-0.9.1-1.noarch.rpm</filename>
        </package>
        <package arch="noarch" epoch="0" name="shark" release="1" src="http://www.fedoraproject.org" version="0.1">
          <filename>shark-0.1-1.noarch.rpm</filename>
        </package>
      </collection>
    </pkglist>
    <pkglist>
```

The collection names do not need to all be unique, they just need to be unique when comparing the same errata in multiple repositories. So, in comparing the updateinfo published for a given errata in two or more repositories, the collection name(s) seen in any one repository's updateinfo should not be seen in any other repository's updateinfo.

**Comment by seandst** [comment]
This is a different version of #539 that does not require yum or dnf to test. I wasn't sure if I should comment on that issue or open a new one since it's quite different. Either approach is fine for proving pulp is behaving correctly, but I think this one is a little more focused. Please modify this issue however you'd like to sanely deal with the duplicate filing. :)

**Comment by Ichimonji10** [comment]
If I understand this correctly, a procedure for testing is:

1. Create a repository, and add an RPM and an errata to that repository.
2. Create a second repository, and add the same RPM and errata to that repository.
3. Publish both repositories. Fetch both of their `updateinfo.xml` files. Verify that the `<pkglist><collection><name>` elements in the two files is unique.

Not too bad. This seems different from #539, for sure.
