### ISSUE TITLE
Add tests to include repo create parameters for throttling

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#584]
https://pulp.plan.io/issues/2629
Throttling
  --max-downloads - maximum number of downloads that will run concurrently
  --max-speed     - maximum bandwidth used per download thread, in bytes/sec,
                    when synchronizing the repo

**Comment by elyezer** [comment]
Checking the speed we can ask the OS to provide that information. I am not sure though on how to check for the downloads information.
