### ISSUE TITLE
Update drpm upload tests to include --check-sum type

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#585]
Update the DRPM upload test cases for both cli & api to include --checksum-type

https://pulp.plan.io/issues/2627

We have smash tests for both CLI & API but it doesn't seem to be using the --checksum-type
pulp_smash.tests.rpm.api_v2.test_upload_publish.UploadDrpmTestCase
pulp_smash.tests.rpm.cli.test_upload.UploadDrpmTestCase.test_upload

https://github.com/PulpQE/pulp-smash/commit/7cbb369f8b89222b71d8eb81e1012e2b8b5dcabb

**Comment by preethit** [comment]
Adding this for @kersommoura @kdelee

**Comment by kdelee** [comment]
@kersommoura  FYI I'm working on this one at the moment
