### ISSUE TITLE
Testing of `console` logging option

### ISSUE THREAD

**Issue by bmbouter** [PulpQE/pulp-smash#594]
This is a test of the console logging option added to server.conf in [Story 2548](https://pulp.plan.io/issues/2548). These are not the best tests, but to really benefit from the value of this story you have to run the processes in a docker container.

Each test changes the config value `log_type` in the `[server]` section of `/etc/pulp/server.conf`.

### Test the default is `syslog`:

1. Have `log_type` commented so that the default is used.
2. Start Pulp normally and observe logs being sent to syslogd.

### Test the `console` option

This test could be better.

1. Set `log_type` to `console`
2. Start Pulp normally and observe logs going to syslog. This happens also when console is used because systemd does that when it starts processes that don't send logs to somewhere other than systemd.

Note: When I tested this in my dev environment, I added a statement that assured me the new `console` codepath was taken.

### Test an invalid value

1. Set `log_type` to `asdf`
2. While observing the logs with `sudo journalctl -f -l | grep log_type` start Pulp normally.
3. Observe the `log_type not properly set. Defaulting to syslog.` in the logs and syslog is being used.

**Comment by Ichimonji10** [comment]
I'm not sure how to distinguish between Pulp's behaviour when the `syslog` and `console` options are set, at least on systemd-based systems. It seems that messages are sent to the system log in both cases. Am I right?

**Comment by bmbouter** [comment]
Yes in both cases (due to systemd) the console and syslog options log to syslog. If you were running Pulp in a docker container though you would notice that Pulp will only log with the `console` option set.

**Comment by Ichimonji10** [comment]
Gotcha. Thanks!
