### ISSUE TITLE
Test that  last_unit_removed timestamp does not change when no units are removed

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#601]
Add tests to make sure that
disassociate_units updates last_unit_removed timestamp even if no units are removed

https://pulp.plan.io/issues/2630

Related

https://pulp-smash.readthedocs.io/en/latest/api/pulp_smash.tests.rpm.api_v2.test_unassociate.html

**Comment by Ichimonji10** [comment]
Fixed by #696.
