### ISSUE TITLE
Test docker sync with docker registry served by artifactory

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#604]
This may need new fixture repo
@ipanova could you please help write this issue? so that we can cover the following
https://pulp.plan.io/issues/2644
https://pulp.plan.io/issues/2643

**Comment by Ichimonji10** [comment]
I've manually tested https://pulp.plan.io/issues/2643. Given what I currently know, I don't think that https://pulp.plan.io/issues/2643 should be given an automated test. The issue references an internal-only host configured with an invalid SSL certificate. Testing the issue required that I create a VM on a host that has access to an internal resource, install Docker, and then configure Docker to run in an insecure non-standard way by editing its service file to include `--insecure-registry`:

```
ExecStart=/usr/bin/docker-current daemon \
          --insecure-registry=docker-registry.engineering.redhat.com \
          --exec-opt native.cgroupdriver=systemd \
          $OPTIONS \
          $DOCKER_STORAGE_OPTIONS \
          $DOCKER_NETWORK_OPTIONS \
          $INSECURE_REGISTRY
```

https://pulp.plan.io/issues/2644 may be a good candidate for automation. I haven't looked at it.

**Comment by rochacbruno** [comment]
This issue has been used to test the migration script, please ignore the comments above
