### ISSUE TITLE
OSTree plugin automation

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#61]
Pulp OSTree Plugin needs to be automated.

Importer/distributor details

Importer: ostree_web_importer
Distributor : ostree_web_distributor

http://pulp-ostree.readthedocs.org/en/latest/tech-reference/importer.html

Probably can follow the same pattern as docker plugin tests
https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/tests/docker/api_v2/test_crud.py

The feed and branches that can be used with OSTree Repo

Feed URL:  http://dl.fedoraproject.org/pub/alt/fedora-atomic/repo/
branch:  fedora-atomic/rawhide/x86_64/docker-host

More Recipes with pulp-admin is
http://pulp-ostree.readthedocs.org/en/latest/user-guide/recipes.html

**Comment by peterlacko** [comment]
First draft of tests is on [1].
Done:
* Create repo without feed
* Sync repo with invalid feed or invalid branch will fail
* Create repo with valid feed and branch, add another branch and sync
* Create and sync repo, copy its content to another repo, check their content match

TODO:
* Test updating a valid feed with an invalid branch
* Extend tests in repo branch update
* Verify published content
* Update doc strings

Sometimes 'sync' takes too long so I had to increase timeout in `poll_spawned_tasks()`. Can we test it with other -- smaller units?
What other use case we need to test here?

[1] https://github.com/peterlacko/pulp-smash/blob/ostree/pulp_smash/tests/ostree/api_v2/test_sync_publish.py

**Comment by Ichimonji10** [comment]
A first batch of tests has been merged. They were submitted for review as pull request #76 and merged as https://github.com/PulpQE/pulp-smash/commit/bc33f5a5f9f6562697219739697f2dd3bc3abaa4 and https://github.com/PulpQE/pulp-smash/commit/73239ad926b9358b01bc5e6d7cbcc627a9801857. As a result, the total number of tests is ~129 for Pulp 2.7 and a few more for Pulp 2.8.

At present, we're missing tests that publish OSTree repositories. @peterlacko, can you take the `PublishTestCase` in https://github.com/PulpQE/pulp-smash/commit/bc33f5a5f9f6562697219739697f2dd3bc3abaa4, refactor (or rewrite, if appropriate) it, and submit a pull request with the results?

**Comment by peterlacko** [comment]
Sure I can.

**Comment by asmacdo** [comment]
I am writing some tests for conflicting ostree relative path feeds (https://pulp.plan.io/issues/1106), but that will rely on a bit of a refactor of this code. Tthe tests I need to write are an extension of CRUD tests, so I plan to separate CRUD from repo_sync.

**Comment by asmacdo** [comment]
OStree is not entirely covered, but I am done with my addition.

**Comment by Ichimonji10** [comment]
Thanks for the addition, @asmacdo. :+1:

**Comment by Ichimonji10** [comment]
We have OSTree tests in the following modules:

* [`pulp_smash.tests.ostree.api_v2.test_crud`](http://pulp-smash.readthedocs.org/en/latest/api/pulp_smash.tests.ostree.api_v2.test_crud.html)
* [`pulp_smash.tests.ostree.api_v2.test_sync_publish`](http://pulp-smash.readthedocs.org/en/latest/api/pulp_smash.tests.ostree.api_v2.test_sync_publish.html)

The tests cases therein CRUD, sync and publish OSTree repositories, in both valid and invalid ways.

We certainly should have more OSTree tests, and I think the most fruitful way to go forward is to start filing more specific issues. It seems that we currently have a basic set of OSTree tests, which is what this issue is asking for.
