### ISSUE TITLE
Database Initial Connect and Reconnect Test Plan

### ISSUE THREAD

**Issue by pcreech** [PulpQE/pulp-smash#63]
Pulp offers a collection of behaviors known as "reconnect support" for the Pulp Database. Here are the expected behaviors:

If you start a Pulp service that connects to the database and the database is not running or is not network accessible for some reason, the Pulp services will wait-and-retry. It has a backoff behavior, but the important part is that it doesn't exit if it can't connect due to availability and when the availability problem is resolved it does connect.
If you have a Pulp service connected to the database and the database shuts down, the pulp services need wait-and-retry as described above. Once the database becomes available again the pulp services should reconnect.
The way this should be tested is as follows.

Test that "Pulp Wait and Retry Database Initial Connect":
1. Stop mongod, pulp_workers, pulp_celerybeat, pulp_resource_manager, and httpd
2. Start pulp_workers, pulp_celerybeat, pulp_resource_manager, and httpd.
3. Wait 30 seconds
4. Start mongod
5. Smoke test using a basic sync/publish of rpm with Pulp.

Test "Pulp database reconnect".
1. Start mongod, pulp_workers, pulp_celerybeat, pulp_resource_manager, and httpd
2. Stop mongod
3. Wait 30 seconds
4. Start mongod
5. Smoke test using a basic sync/publish of rpm with Pulp.

These are separate because it would be useful to know independently if either is working. We've had cases in the past where one was broken, or the other, or both.

**Comment by Ichimonji10** [comment]
Unassigning myself for now, as I have some bugs related to the 2.8 release that need to be verified and have higher priority.
