### ISSUE TITLE
Test rsync publish

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#637]
https://pulp.plan.io/issues/2722
1. create repo with yum and rsync dist 
2. publish with rsync --> observe skipped publish result 
3. publish with rsync again and observe the traceback

**Comment by Ichimonji10** [comment]
Among the issues in the 2.13.1 milestone, I think this one is a good candidate for easy automation: it doesn't require creating any new fixtures, and it doesn't require installing new tools on the Pulp systems.
