### ISSUE TITLE
Testing headers option for alternate content source

### ISSUE THREAD

**Issue by werwty** [PulpQE/pulp-smash#643]
https://pulp.plan.io/issues/1282

1. Create alternate content source configuration
`vi /etc/pulp/content/sources/conf.d/test.conf`
```
[content-world]
enabled: 1
priority: 0
expires: 3d
name: Content World
type: yum
base_url: http://bizhang.fedorapeople.org/
paths: zoo/ \
       test
max_concurrent: 10
max_speed: 1000
headers: X-RHUI-ID=1234 \
               X-Csrf-Token=31415926535897
```

2. Validate that headers shows up when `pulp-admin content sources list` is ran
3. run `pulp-admin content sources refresh`, monitoring the network traffic to check the HTTP headers.
I'm using tcpflow for this: `sudo tcpflow -p -c -i eth0 port 80`

4. Update test.conf with invalid headers
```
headers: X-RHUI-ID1234
```

5. run  `pulp-admin content sources refresh`  and make sure `Unparsable` is raised in the systemd logs
Note that the cli will show Task Succeeded despite nothing being downloaded. From what I can see this is because the task is running with no content sources, since the alternate content source is designed to fail over to the original source.

**Comment by Ichimonji10** [comment]
I've made a shell script that performs all of the necessary steps to reproduce this issue. I am *not* able to find any of the given headers, such as `X-RHUI-ID`. Can you give any insight into this, @werwty ?

```bash
#!/usr/bin/env bash
# coding=utf-8
#
# Run this script as root on a Pulp host. When executed, this script will verify
# https://pulp.plan.io/issues/1282.
set -euo pipefail

readonly path=/etc/pulp/content/sources/conf.d/test.conf
readonly cfg="[test-content]
enabled: 1
priority: 0
expires: 1d
name: Test Content
type: yum
base_url: http://repos.fedorapeople.org/pulp/pulp/fixtures/
paths: rpm-unsigned/
max_concurrent: 10
max_speed: 1000"

login() (
    pulp-admin login -u admin -p admin
)

# Create and use a valid configuration file. Verify that:
#
# * The word "unparseable" doesn't show up in journalctl's output.
# * The given headers show up in the output of `pulp-admin content sources
#   list`.
test_valid_headers() (
    readonly local out_dir=valid_headers
    echo "$cfg" | cat >"$path"
    cat >>"$path" <<EOF
headers: X-RHUI-ID=1234 X-CSRF-TOKEN=31415926535897
EOF
    tcpflow -p -o "$out_dir" port 80 &
    pulp-admin content sources list
    pulp-admin content sources refresh
    kill $!
    echo "Matching headers in ${out_dir}:"
    grep -RIin 'x-rhui-id\|x-csrf-token' "$out_dir" || true
)

# Create and use an invalid configuration file. Verify that:
#
# * The word "unparseable" shows up in journalctl's output.
# * The given headers show up in the output of `pulp-admin content sources
#   list`?
test_invalid_headers() (
    readonly local out_dir=invalid_headers
    echo "$cfg" | cat >"$path"
    cat >>"$path" <<EOF
headers: X-RHUI-ID1234 X-CSRF-TOKEN=31415926535897
EOF
    tcpflow -p -o "$out_dir" port 80 &
    pulp-admin content sources list
    pulp-admin content sources refresh
    kill $!
    echo "Matching headers in ${out_dir}:"
    grep -RIin 'x-rhui-id\|x-csrf-token' "$out_dir" || true
)

cleanup() (
    rm -rf "$path" *_headers
)

login
test_valid_headers
test_invalid_headers
cleanup
```

**Comment by Ichimonji10** [comment]
At this point, I'm unsure whether it's a good idea to make a complete automated test case from this issue. At the very least, though, we now have a script for quickly manually testing this issue.

**Comment by Ichimonji10** [comment]
I think the automated test added by #687 does a reasonable job of addressing this issue. It's not as in-depth as what's done by the bash script listed earlier in this thread, but I suspect that making Pulp Smash do the same things as that bash script will require quite a bit of effort and produce a fragile test.

Closing. @werwty, if you think that more automation should be added, please re-open this issue and explain what improvements are desirable.
