### ISSUE TITLE
Test syncing errata with large package lists

### ISSUE THREAD

**Issue by dkliban** [PulpQE/pulp-smash#656]
1. Create an RPM repository Foo with feed URL of https://repos.fedorapeople.org/pulp/pulp/demo_repos/large_errata/zoo/.
2. Create an RPM repository Bar with the same feed URL of https://repos.fedorapeople.org/pulp/pulp/demo_repos/large_errata/zoo/.
3. Sync repository Foo.
4. Sync repository Bar.
5. Assert that sync from step 4 finished successfully without error.

**Comment by kersommoura** [comment]
@dkliban, can you clarify what do you mean by large errata? Is it the size of rpm package in bytes or the number of rpm packages per errata?

**Comment by kersommoura** [comment]
Related redmine issue:

https://pulp.plan.io/issues/2681
