### ISSUE TITLE
Update the retain old count test to include Issue#2785

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#662]
https://pulp.plan.io/issues/2785
Check test_retain_old_count test and update if needed
pulp_smash.tests.rpm.api_v2.test_retain_old_count

**Comment by Ichimonji10** [comment]
#666 and #668 verify that `--retain-old-count` works correctly when set to zero. To fully close out this issue, we need tests to verify that `--retain-old-count` works when set to a non-zero value.
