### ISSUE TITLE
Test upload rpms have metadata information

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#667]
https://pulp.plan.io/issues/2754

Test upload and assert that the uploaded rpms have the metadata information

1. wget https://repos.fedorapeople.org/repos/pulp/pulp/demo_repos/zoo/kangaroo-0.2-1.noarch.rpm
2. pulp-admin rpm repo uploads rpm --file kangaroo-0.2-1.noarch.rpm --repo-id zoo
3. phttp https://localhost/pulp/api/v2/repositories/zoo/search/units/ criteria:='{"fields": {"unit": ["name", "summary", "size", "group", "sourcerpm"]}, "type_ids": ["rpm"], "filters": {"unit": {"name": "kangaroo"}}}'

**Comment by kdelee** [comment]
Can you elaborate about this third step? I'm not clear on where I can get this `phttp` command or if I can rely that it will be present on testing machines. Is there a more standard alternative?

**Comment by Ichimonji10** [comment]
Use the API client. It isn't important to use `phttp` specifically.

**Comment by kdelee** [comment]
@Ichimonji10 
Great thanks
