### ISSUE TITLE
Centralize Custom Exceptions

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-smash#68]
Pulp Smash defines a variety of custom exceptions. This is appropriate: if a standard exception does not fit a situation well, one should define a new exception and raise it instead of executing `raise Exception`. The problem is that those custom exceptions are scattered throughout the codebase. Let's do the following:

1. Define a new module, `pulp_smash.exceptions`.
2. Move all custom exceptions into this module, and adjust references to those exceptions as necessary.
3. Ensure the various make recipes reference this new module. This means at least `make docs-html` and `make lint-pylint`.

**Comment by Ichimonji10** [comment]
@bmbouter FYI

**Comment by bmbouter** [comment]
@Ichimonji10 :+1: :palm_tree:

**Comment by elyezer** [comment]
:+1:
