### ISSUE TITLE
Test that the vendor field is available for uploaded and synced rpms

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#680]
https://pulp.plan.io/issues/2781
1. Create a repo with synced and uploaded content
2. Compare the rpm (search) to see that vendor field is populated in both

**Comment by preethit** [comment]
@kdelee this may be an extension of https://github.com/PulpQE/pulp-smash/issues/667 that you are working on.

**Comment by kdelee** [comment]
I have looked through current pulp-fixtures RPMs and can't find one with vendor data. I will make an issue on pulp-fixtures.

**Comment by kdelee** [comment]
Blocked until [pulp-fixtures issue #54](https://github.com/PulpQE/pulp-fixtures/issues/54) is closed.

**Comment by Ichimonji10** [comment]
Unblocked.
