### ISSUE TITLE
Add  tests to verify Puppet Install Distributor raises exceptions when required information is missing

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#686]
Puppet Install Distributor does not raise exception when non-optional install_path is missing
https://pulp.plan.io/issues/1237

**Comment by Ichimonji10** [comment]
@kersommoura @kdelee This issue is *very* easy to automate. Consider picking it up.

**Comment by preethit** [comment]
Assigning to both @kersommoura and @kdelee
