### ISSUE TITLE
Test Tasks stuck in waiting after restart of pulp services issue#2835

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#694]
https://pulp.plan.io/issues/2835

**Comment by preethit** [comment]
@Ichimonji10 is this something that can be worked on soon?

**Comment by Ichimonji10** [comment]
Sure.

**Comment by Ichimonji10** [comment]
Upon looking into it, the developers have found that there are three issues at play:

- [ ] [Pulp #2861](https://pulp.plan.io/issues/2861) (Issue A)
- [ ] [Pulp #2835](https://pulp.plan.io/issues/2835) (Issue B)
- [ ] [Pulp #2837](https://pulp.plan.io/issues/2837) (Issue C)
