### ISSUE TITLE
Pulp 2 tests should skip if untestable in version >= 3

### ISSUE THREAD

**Issue by kdelee** [PulpQE/pulp-smash#703]
Need to inject some logic to skip tests for pulp 2 issues/api/cli components that are not testable for pulp versions >= 3.

**Comment by kdelee** [comment]
Perhaps this could be in [selectors.bug_is_testable(bug_id, pulp_version)](https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/selectors.py#L137) or perhaps it should be a entirely separate method that the test developer invokes explicitly.

@Ichimonji10 @preethit @kersommoura Any thoughts?

I would be willing to work on this once an approach is agreed on.

**Comment by Ichimonji10** [comment]
`selectors.bug_is_testable` is focused on whether or not an issue has been fixed yet, not on whether an issue has been obsoleted by a new version of Pulp. That behaviour is a reflection of the Pulp issue tracker itself. The issue tracker contains information stating in which version of Pulp an issue was first noticed and in which version of Pulp an issue was fixed, but the issue tracker doesn't track when an issue has been obsoleted. That makes me wary of using `selectors.bug_is_testable`.

We could place Pulp 2 and 3 tests in separate packages. For example, one could:

1. Create package `pulp_smash.tests.pulp2`, and move all existing tests into it.
2. Modify `pulp_smash.tests.pulp2.*.utils.set_up_module`. Let the set up functions `raise unittest.SkipTest` if Pulp 3 is under test.
3. Create package `pulp_smash.tests.pulp3`.
4. As a first test, create module `pulp_smash.tests.pulp3.platform.api.test_login`, and import `pulp_smash.tests.pulp2.platform.api_v2.test_login.LoginTestCase`.

This would:

* Allow us to re-use individual test cases.
* Allow some of us to continue using Pulp Smash in the same way: `python -m unittest discover pulp_smash.tests`.
* Ensure that Pulp 3 tests never leak into the Pulp 2 test suite.

Of course, that's a drastic step. We *already* let Pulp tests run on inappropriate versions of Pulp. Tests written today regularly don't include safeguards that ensure that they're skipped on Pulp 2.11 or earlier. And if the majority of tests continue working with Pulp 3, then having to import numerous Pulp 2 tests into the Pulp 3 namespace will be a giant PITA, *especially* in cases where `setUpModule` and the like are used.

I don't think we can make a good decision about how to approach this until we have Pulp 3 builds ready to test.

**Comment by kdelee** [comment]
👍

**Comment by Ichimonji10** [comment]
Thoughts from today's meeting:

I think a good approach is for us to continue using the same Pulp Smash Python package. This will make the workflow for our users, Jenkins jobs, etc easier. It will also allow us to re-use some tooling. For example, pulp_smash.{config,selectors,api,cli} can all largely be re-used.

Most or all of our tests for Pulp 2 will no longer work with Pulp 3. Given this, I think a good approach is for us to create new (namespace) packages within Pulp Smash, like `pulp_smash.tests.*.api_v3`, and to place new tests there. That way, entire packages of code can be run or skipped, which is fairly easy to understand and implement.

Tangent: I'd like to pull constants related to Pulp Fixtures out of Pulp Smash and into a separate (installable) package - preferably, right in the source code with Pulp Fixtures. This would let Pulp Smash be more focused, and it would let others re-use Pulp Fixtures if they so desired.

**Comment by kersommoura** [comment]
See also: [791](https://github.com/PulpQE/pulp-smash/issues/791)

**Comment by Ichimonji10** [comment]
Fixed by #794
