### ISSUE TITLE
Automate Lazy sync  - background

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#72]
Background policy skip downloading files during sync, but once the sync is completed it will dispatch a task to download the file
Case 2
1. Create a repo with background download policy
pulp-admin rpm repo create --repo-id zoo --feed https://repos.fedorapeople.org/repos/pulp/pulp/demo_repos/zoo/  --download-policy background
2. Run repo Sync
 pulp-admin rpm repo sync run --repo-id zoo
3. Assert that there is a pulp task for downloading files
  pulp-admin tasks list

**Comment by jeremycline** [comment]
I can't assign this to myself, but I'm going to work on this.

**Comment by Ichimonji10** [comment]
Fixed by 12bb39ee7eb959c252d4217b0d70b3338833f182
