### ISSUE TITLE
As a user, I can use JWT tokens for authenticaton

### ISSUE THREAD

**Issue by kersommoura** [PulpQE/pulp-smash#725]
Related issue:
https://pulp.plan.io/issues/2359

One should be able to:

- [ ] a JWT after some other initial authentication (e.g. basic auth)
- [ ] use JWT for further authentication
- [ ] invalidate JWT

  by request
  
  - [ ] on user logout
  - [ ] on user delete
  - [ ] when password-like credentials used in the initial authentication were changed

  - [ ]  configure expiration time for the JWT token (the default value - 1 week? 3 weeks?)

[Extra Info about Pulp3 Authentication](https://www.redhat.com/archives/pulp-dev/2016-September/msg00049.html)

**Comment by asmacdo** [comment]
I recommend that we close this issue, we have removed this feature from the Pulp 3 MVP

**Comment by Ichimonji10** [comment]
Sounds good to me. Note that we have non-exhaustive JWT tests in place, and they will be re-enabled if [Pulp #3248](https://pulp.plan.io/issues/3248) is fixed.
