### ISSUE TITLE
Automate Lazy sync - on_demand

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#73]
API info
https://github.com/pulp/pulp/blob/master/docs/dev-guide/integration/rest-api/repo/sync.rst#download-a-repository

1. Create a repo with on_demand download policy
pulp-admin rpm repo create --repo-id zoo --feed https://repos.fedorapeople.org/repos/pulp/pulp/demo_repos/zoo/  --download-policy on_demand
2. Run repo Sync
3. The repo is synced  (check /var/lib/pulp/content )
4. Register a consumer and bind the repo
5. Install a package on the consumer 
6. Make sure that the package is downloaded and installed
7. Make sure that only the package requested is downloaded

**Comment by preethit** [comment]
This is from jcline- 

class SyncOnDemandTestCase(SyncValidFeedTestCase):
    """Assert that Yum supports on-demand syncing."""

    @classmethod
    def setUpClass(cls):
        """Create an RPM repository with a valid feed and sync it."""
        super(SyncOnDemandTestCase, cls).setUpClass()
        cls.post_sync_repo = handle_response(requests.get(
                cls.cfg.base_url + cls.attrs_iter[0]['_href'] + '?details=true',
                **cls.cfg.get_requests_kwargs()
            )
        )

    def test_no_local_units(self):
        """Assert no content units were downloaded."""
        self.assertEqual(0, self.post_sync_repo['locally_stored_units'])

    def test_repository_units(self):
        """Assert there are some content units in the repository."""
        self.assertGreater(0, self.post_sync_repo['total_repository_units'])

**Comment by Ichimonji10** [comment]
Here's a revision of the sample code above:

```python
class SyncOnDemandTestCase(SyncValidFeedTestCase):
    """Assert Yum supports on-demand syncing."""

    @classmethod
    def setUpClass(cls):
         """Create an RPM repository with a valid feed and sync it."""
        super(SyncOnDemandTestCase, cls).setUpClass()
        # Parent class creates an RPM repository with a valid feed and syncs
        # it.
        cls.repo_info = client.get(cls.repo['_href'], params={'details': True})

    def test_no_local_units(self):
        """Assert no content units were downloaded."""
        self.assertEqual(self.repo_info['locally_stored_units'], 0)

    def test_repository_units(self):
        """Assert there is at least one content unit in the repository."""
        self.assertGreater(self.repo_info['total_repository_units'], 0)
```

It could be advantageous to take the process of creating an RPM repository with a valid feed and syncing it and placing that process into a stand-alone function, perhaps in `pulp_smash.utils`.
