### ISSUE TITLE
As an API user, a call to update an Publisher generates a Task

### ISSUE THREAD

**Issue by kersommoura** [PulpQE/pulp-smash#734]
Related issue:
https://pulp.plan.io/issues/2409

**Comment by asmacdo** [comment]
Should return a 202 with a task. 
Publisher should be updated after task is complete

**Comment by kersommoura** [comment]
There are tests for update publishers, using PATCH and PUT methods. Both methods return a 202.
There is no assertion about 202 in the test cases itself, since the [api.json_handler](https://github.com/PulpQE/pulp-smash/blob/ff5b85c675dfcf8997776ee2f9d8a1e7153d6240/pulp_smash/api.py#L128) is in use, and it does handle 202.

See: [Update Publishers](https://github.com/PulpQE/pulp-smash/blob/ff5b85c675dfcf8997776ee2f9d8a1e7153d6240/pulp_smash/tests/pulp3/file/api_v3/test_crud_publishers.py#L63)
