### ISSUE TITLE
As an un-authenticated user I can 

### ISSUE THREAD

**Issue by kersommoura** [PulpQE/pulp-smash#749]
[MVP Authentication](https://pulp.plan.io/projects/pulp/wiki/Pulp_3_Minimum_Viable_Product#Authentication)

~~-  Obtain a JWT token by using a username and password.~~

**At the time of creating this issue, these taxed items were not confirmed in the MVP document.**

**Comment by asmacdo** [comment]
@kersommoura, I'm closing because it appears to be a dupe of #751, please reopen if you had another intention for this issue.

**Comment by kersommoura** [comment]
@asmacdo, thanks.
