### ISSUE TITLE
Repo and orphan delete can be executed cleanly after Lazy sync

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#75]
1. Create a repository with on_demand sync plan
   
    pulp-admin rpm repo create --repo-id foo --feed https://repos.fedorapeople.org/repos/pulp/pulp/demo_repos/zoo/  --download-policy on_demand
   
   Assert
   1. Repo create successful
   2. It has Download Policy: on_demand
2. Synchronize the repository
    pulp-admin rpm repo sync run --repo-id foo
   
   Assert
   1. Sync succesful
   2. Repository has all the content
3. Delete the repo
   pulp-admin rpm repo delete --repo-id foo
   
   Assert
   1. Any consumer that has been bound to the repository has been unbound
   2. Repository delete is successful
   3. Any content that is part of the repository is an orphan state
      < pulp-admin orphan list>
4. Remove Orphans
   pulp-admin orphan remove --all
   
   Assert
   1. Orphan removal task successful
   2. All the orphaned content has been removed

**Comment by omaciel** [comment]
@preethit I'd recommend a more verbose test case. For example:

1. Create a new repository (use random values for its name and a valid `feed` url) with a `on_demand` sync plan
    * Assert that the repository was created and has the correct values assigned during creation
1. Synchronize the new repository
    * Assert that the sync process is successful and that the repository contains data (packages)
1. Delete the repository
    * Assert that the delete process is successful and that its content is removed from the system
1. Remove orphans
    * Assert that...

This example shows all the things you want the developer to incorporate into your test case.

**Comment by Ichimonji10** [comment]
We have tests for all of the behaviours listed in this issue.
