### ISSUE TITLE
As an API user, I will be able to 

### ISSUE THREAD

**Issue by kersommoura** [PulpQE/pulp-smash#750]
[MVP Authentication ](https://pulp.plan.io/projects/pulp/wiki/Pulp_3_Minimum_Viable_Product#Authentication)
~~-  Authenticate any API call (except to request a JWT) with a JWT.~~
~~-  Invalidate all existing JWT tokens for a given user.~~

**At the time of creating this issue, these taxed items were not confirmed in the MVP document.**

**Comment by asmacdo** [comment]
@kersommoura, I'm closing because it appears to be a dupe of https://github.com/PulpQE/pulp-smash/issues/751, please reopen if you had another intention for this issue.

**Comment by kersommoura** [comment]
@asmacdo, thanks.
