### ISSUE TITLE
View Status view REST API

### ISSUE THREAD

**Issue by kersommoura** [PulpQE/pulp-smash#755]
[MVP Status](https://pulp.plan.io/projects/pulp/wiki/Pulp_3_Minimum_Viable_Product#Status)

- View the status of Pulp workers and resource managers.

- View the status of httpd's connection to the database and message broker.

~~- As an administrator, the WSGI app will not start if all migrations have not been applied~~

**At the time of creating this issue, this taxed item was not confirmed in the MVP document.**

**Comment by asmacdo** [comment]
"As an administrator, the WSGI app will not start if all migrations have not been applied" doesn't really belong in the section. (red sections in the MVP are not settled)

**Comment by asmacdo** [comment]
There is another field, (which I will add to the MVP) for pulpcore version.

**Comment by daviddavis** [comment]
Relevant redmine issue: https://pulp.plan.io/issues/2867

**Comment by asmacdo** [comment]
Other relevant redmine issue: https://pulp.plan.io/issues/2804

**Comment by daviddavis** [comment]
Also, test that an unauthenticated user can access this status API.
