### ISSUE TITLE
Test that when installing errata only the latest version gets installed

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#760]
1. Create a repo a repo with errata and have multiple versions of the same rpm
2. Attempt to install the errata
3. Assert that install only installed the latest rpm

**Comment by Ichimonji10** [comment]
I'm a bit confused here. Should step 2 read "attempt to install the RPM?" Or, if errata are necessary, how does it fit into this procedure?

**Comment by preethit** [comment]
@Ichimonji10 I am trying to get the test case from the bugzilla. Will try to get this to a more clearer state. We used to have a repo that had erratum with multiple versions of rpm. I will play with that to see how I can get to this.

**Comment by Ichimonji10** [comment]
Sounds good. We *might* have a test case that does this or something similar. I'll check tomorrow.

**Comment by Ichimonji10** [comment]
Pulp Fixtures' [rpm-unsigned repository](https://repos.fedorapeople.org/pulp/pulp/fixtures/rpm-unsigned/) has two RPMs with the same name and different versions:

* walrus-0.71-1.noarch.rpm
* walrus-5.21-1.noarch.rpm

updateinfo.xml lists several errata, and the "Sea_Erratum" references walrus:

```xml
<update from="errata@redhat.com" status="stable" type="security" version="1">
  <id>RHEA-2012:0055</id>
  <title>Sea_Erratum</title>
  <release>1</release>
  <issued date="2012-01-27 16:08:06"/>
  <updated date="2012-01-27 16:08:06"/>
  <description>Sea_Erratum</description>
  <pkglist>
    <collection short="">
      <name>1</name>
      <package arch="noarch" name="walrus" release="1" src="http://www.fedoraproject.org" version="5.21">
        <filename>walrus-5.21-1.noarch.rpm</filename>
      </package>
      <package arch="noarch" name="penguin" release="1" src="http://www.fedoraproject.org" version="0.9.1">
        <filename>penguin-0.9.1-1.noarch.rpm</filename>
      </package>
      <package arch="noarch" name="shark" release="1" src="http://www.fedoraproject.org" version="0.1">
        <filename>shark-0.1-1.noarch.rpm</filename>
      </package>
    </collection>
  </pkglist>
</update>
```

We have several tests that touch on these facts. Two are especially relevant.

The first is [PkglistsTestCase](http://pulp-smash.readthedocs.io/en/latest/api/pulp_smash.tests.rpm.api_v2.test_updateinfo.html#pulp_smash.tests.rpm.api_v2.test_updateinfo.PkglistsTestCase). It verifies that, when Pulp syncs and publishes this repository, the published repository's `updateinfo.xml` file references the correct RPM.

The second is [UpdateRpmTestCase](http://pulp-smash.readthedocs.io/en/latest/api/pulp_smash.tests.rpm.cli.test_copy_units.html#pulp_smash.tests.rpm.cli.test_copy_units.UpdateRpmTestCase). The "RPM with at least two versions" mentioned by its docstring is the "walrus" RPM, which is mentioned by the erratum.

**Comment by preethit** [comment]
Looking at it a bit more here is my understanding.
This has to do with applicability.

1. Sync a repo with errata which has multiple versions of the same rpm
2. On a consumer apply the errata.
3. Make sure that only the latest rpm on the errata is installed. ( Not all the versions of the errata)
