### ISSUE TITLE
Replace parent class BaseAPITestCase by unittest.TestCase

### ISSUE THREAD

**Issue by kersommoura** [PulpQE/pulp-smash#763]
Few tests fail due to time-out that happening during the execution of tear down.
To reduce the number of calls to `client.delete(ORPHANS_PATH)`, and try to reduce the number of failures. Replace the BaseAPITestCase by unittest.TestCase. 
```
    @classmethod
    def tearDownClass(cls):
        """Delete all resources named by ``resources``."""
        client = api.Client(cls.cfg)
        for resource in cls.resources:
            client.delete(resource)
        client.delete(ORPHANS_PATH)
```

Basically, it will be necessary pass class by class, replace the parent class and do the necessary re-factors.

See also: [#762](https://github.com/PulpQE/pulp-smash/issues/762)

**Comment by Ichimonji10** [comment]
https://github.com/PulpQE/pulp-smash/pull/1025 deprecated `BaseAPITestCase`.
