### ISSUE TITLE
pulp-smash is not compatible with pytest

### ISSUE THREAD

**Issue by dkliban** [PulpQE/pulp-smash#78]
I've noticed that our Jenkins is getting 10 failures due to a 404 from Pulp Puppet Forge API. However, I don't see the same failures on my development environment. I have determined that the difference is in the test runner that is being used. Here are the results I got:

`py.test pulp_smash/tests/puppet/`

`HTTPError: 404 Client Error: NOT FOUND for url: https://dev.example.com/api/v1/releases.json?module=pulp%2Fpulp`

`11 passed, 10 error in 70.47 seconds `

-----------------------------------------------------------------------------

`python -m unittest2 discover pulp_smash.tests.puppet`

`Ran 21 tests in 70.650s`
`OK`

**Comment by Ichimonji10** [comment]
The test runner is not at issue here. I can reproduce that 404 with unittest2. In my case, the difference lies in which version of Pulp is being tested. Pulp 2.7 does not suffer from that bug, but Pulp master does. See attached screenshot for demonstration. This is a bug in Pulp.

![Uploading Screenshot_2016-02-02_09-21-45.png…]()

**Comment by dkliban** [comment]
I don't think that the difference is in the version being tested. I think that you are seeing the failure because you ran the test twice without resetting the database.

**Comment by Ichimonji10** [comment]
I ran these tests against separate systems that I already abused yesterday.

**Comment by Ichimonji10** [comment]
@dkliban, you mentioned that you only see this test failure when running Pulp
Smash multiple times. I can confirm, and I can reiterate that the likely culprit
is a bug in Pulp 2.8. Here's test results from a freshly provisioned Pulp 2.7
system, for which no other test have been run:

```
(pulp-smash2)[ichimonji10@beech:pulp-smash]$ PULP_SMASH_CONFIG_FILE=${PULP}.json python -m unittest2 discover pulp_smash.tests
s..ss...s...sssss.s.........ssss..........................................................s...................s....
----------------------------------------------------------------------
Ran 111 tests in 329.165s

OK (skipped=16)
(pulp-smash2)[ichimonji10@beech:pulp-smash]$ !!
PULP_SMASH_CONFIG_FILE=${PULP}.json python -m unittest2 discover pulp_smash.tests
s..ss...s...sssss.s.........ssss..........................................................s...................s....
----------------------------------------------------------------------
Ran 111 tests in 320.899s

OK (skipped=16)
```

And here's test results from a freshly provisioned Pulp master (2.8) system, for
which no other tests have been run:

```
(pulp-smash3)[ichimonji10@beech:pulp-smash]$ PULP_SMASH_CONFIG_FILE=${PULP}.json python -m unittest2 discover pulp_smash.tests
...........s....ssss...........ssss..............................................................................s....
----------------------------------------------------------------------
Ran 115 tests in 368.665s

OK (skipped=10)
(pulp-smash3)[ichimonji10@beech:pulp-smash]$ !!
PULP_SMASH_CONFIG_FILE=${PULP}.json python -m unittest2 discover pulp_smash.tests
...........s....ssss...........ssss...............................E.....................................s....
======================================================================
ERROR: setUpClass (pulp_smash.tests.puppet.api_v2.test_sync_publish.PublishTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ichimonji10/code/pulp-smash/pulp_smash/tests/puppet/api_v2/test_sync_publish.py", line 336, in setUpClass
    auth=('.', repo['id']),
  File "/home/ichimonji10/code/pulp-smash/pulp_smash/api.py", line 203, in get
    return self.request('GET', url, **kwargs)
  File "/home/ichimonji10/code/pulp-smash/pulp_smash/api.py", line 251, in request
    requests.request(method, **request_kwargs),
  File "/home/ichimonji10/code/pulp-smash/pulp_smash/api.py", line 66, in safe_handler
    response.raise_for_status()
  File "/home/ichimonji10/.virtualenvs/pulp-smash3/lib/python3.5/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://192.168.121.53/api/v1/releases.json?module=pulp%2Fpulp

----------------------------------------------------------------------
Ran 105 tests in 352.923s

FAILED (errors=1, skipped=10)
```

**Comment by dkliban** [comment]
When I run `py.test pulp_smash/tests/puppet/api_v2/test_sync_publish.py::PublishTestCase` the test always passes (if the database is cleaned up after each run). However, running `py.test pulp_smash/tests/puppet/api_v2/test_sync_publish.py` always causes failures. 

Perhaps the first test in the `test_sync_publish.py` is not doing something right.

**Comment by Ichimonji10** [comment]
How can one clean the database?

**Comment by dkliban** [comment]
`mongo pulp_database`
`> db.dropDatabase()`
`ctrl + d`
`sudo -u apache pulp-manage-db`

And I also like to clean up /var/lib/pulp

`sudo rm -rf /var/lib/pulp/published/*`
`sudo rm -rf /var/lib/pulp/content/*`

**Comment by dkliban** [comment]
This sequence causes the failure:

`py.test pulp_smash/tests/puppet/api_v2/test_sync_publish.py::SyncValidFeedTestCase`
`py.test pulp_smash/tests/puppet/api_v2/test_sync_publish.py::PublishTestCase`

**Comment by dkliban** [comment]
Sorry about all the headache. This is a bug with pulp.

**Comment by Ichimonji10** [comment]
Got it. Good, concise summary.
