### ISSUE TITLE
Change Pulp-Smash Code layout to fit Pulp2 and Pulp3 needs.

### ISSUE THREAD

**Issue by kersommoura** [PulpQE/pulp-smash#791]
Code related to Pulp3 will be added to Pulp-Smash soon.

Based on that it does make sense to modify pulp-smash current layout to fit this need. Below, a draft version of future layout .

```
pulp_smash/
├── constants.py
├── pulp2
│   ├── constants.py
│   └── tests
└── pulp3
    ├── constants.py
    └── tests
```

Every project will have its own dir, and it is related files. All the other files there a common for both projects will be in a level above.  For instance, the constant files for Pulp3 will have all related constants of Pulp3. Constants shared by both projects, like pulp-fixtures ones, will be in another constant file a level above.

**This change in layout possibly will impact imports in different parts of the code, and how certain Jenkins Jobs are currently set.**

**Comment by Ichimonji10** [comment]
We chatted about this face-to-face yesterday, and I think this is a good solution for us to adopt. It should solve #703, as a user could run Pulp 3 tests by executing:

    python -m unittest discover pulp_smash.pulp3.tests

In the immediate future, a user could continue running Pulp 2 tests in the same way as they have been doing:

    python -m unittest discover pulp_smash.tests

And we could eventually make the layout more regular:

    python -m unittest discover pulp_smash.pulp2.tests

**Comment by kersommoura** [comment]
@Ichimonji10, thanks for your comment.

**Comment by kersommoura** [comment]
Besides the files mentioned before this change will affect the Makefile and generation of documentation.

**Comment by Ichimonji10** [comment]
As per a discussion we had today, let's place Pulp 2 tests in `pulp_smash.tests.pulp2` and Pulp 3 tests in `pulp_smash.tests.pulp3`.

**Comment by kersommoura** [comment]
See also:  Commit [6bc45e7](https://github.com/PulpQE/pulp-smash/commit/6bc45e788d83714e1effdbacb2d0253e36c9fd25)

As stated by @Ichimonji10 in the previous commit message.

> 
> This organization has several advantages:
> 
> * No backward compatibilities are introduced.
> * Version information stays DRY. If tests were in module
>   `pulp_smash.pulp3.tests`, then a user would need to specify Pulp's
>   version in the Pulp Smash configuration file *and* run the correct
>   package of tests. With the current organization, the user need only to
>   specify Pulp's version in the Pulp Smash configuration file.
> * Test runner invocation is more concise and logically simpler.

**Comment by kersommoura** [comment]
@Ichimonji10 , do you agree to close this issue?

**Comment by Ichimonji10** [comment]
Yes.
