### ISSUE TITLE
Adjust response_handlers for Pulp3 needs.

### ISSUE THREAD

**Issue by kersommoura** [PulpQE/pulp-smash#795]
As part of changes required to adjust Pulp-Smash to fit Pulp3 needs, it will be necessary to adjust the callback function, `response_handler`. These functions are used together with `api.Client` mainly.

Pulp2 and Pulp3 differ in the way the responses for certain actions are sent back. 

In Pulp3 the update of a data in a certain repository will generate the follow **202** response.

```json
{
    "_href": "http://pulp3.dev:8000/api/v3/tasks/4fc2e1fe-2564-4818-9b0d-4116a32ec2d0/",
    "task_id": "4fc2e1fe-2564-4818-9b0d-4116a32ec2d0"
}
```

Using the` api.json_handler` as response_handler to handle the previous response, it will generate an error, since it is not ready to parse this pattern of response. 

Error will occur in the function [poll_spawned_tasks](https://github.com/PulpQE/pulp-smash/blob/394d3510d052660d8ed378cc919861a18e2f7400/pulp_smash/api.py#L346), and [poll_task](https://github.com/PulpQE/pulp-smash/blob/394d3510d052660d8ed378cc919861a18e2f7400/pulp_smash/api.py#L371)

There are basically 2 choices, create other functions to handle Pulp3 response, or adapt the current ones to verify what version of Pulp is under test and perform different steps as needed.

Possibly changes to CLI Client`s callbacks will be required as well, but not identified at the moment.

Example Pulp 2 task:

```json
{
 "_href": "/pulp/api/v2/tasks/0fe4fcab-a040-11e1-a71c-00508d977dff/",
 "state": "running",
 "worker_name": "reserved_resource_worker-0@your.domain.com",
 "task_id": "0fe4fcab-a040-11e1-a71c-00508d977dff",
 "task_type": "pulp.server.tasks.repository.sync_with_auto_publish",
 "progress_report": {"contents vary": "depending on operation"},
 "result": null,
 "start_time": "2012-05-17T16:48:00Z",
 "finish_time": null,
 "exception": null,
 "traceback": null,
 "tags": [
   "pulp:repository:f16",
   "pulp:action:sync"
 ],
 "spawned_tasks": [{"href": "/pulp/api/v2/tasks/7744e2df-39b9-46f0-bb10-feffa2f7014b/",
                    "task_id": "7744e2df-39b9-46f0-bb10-feffa2f7014b" }],
 "error": null
}
```

Example Pulp 3 task:

```json
"results": [{
  "_href": "http://pulp3.dev:8000/api/v3/tasks/e99435f5-0ba4-4ccf-bb66-60a1bd120ae1/",
  "group": null,
  "state": "completed",
  "started_at": "2017-10-20T18:37:47.630237Z",
  "finished_at": "2017-10-20T18:37:47.684939Z",
  "non_fatal_errors": [],
  "error": null,
  "worker": "http://pulp3.dev:8000/api/v3/workers/reserved_resource_worker_2@pulp3.dev/",
  "parent": null,
  "tags": [],
  "progress_reports": []
}]
```

**Comment by Ichimonji10** [comment]
Fixed by https://github.com/PulpQE/pulp-smash/pull/833.
