### ISSUE TITLE
Separate constants per project and global ones.

### ISSUE THREAD

**Issue by kersommoura** [PulpQE/pulp-smash#799]
As per issue: [791](https://github.com/PulpQE/pulp-smash/issues/791).

> Pulp-Smash will contain specific packages for each project Pulp2 and Pulp3. 

Based on that, it is a good approach to move constants related to Pulp2 to a constants file in the Pulp2 package, and the same for Pulp3. Shared constants will live in a level above, an example of shared constants are all related to pulp-fixtures.

**Comment by kersommoura** [comment]
Specific utility functions will have to be ported to specific projects as well. Keeping different name-spaces clean.

**Comment by Ichimonji10** [comment]
I think this is done. See #809. @kersommoura, can you close this if you agree?

**Comment by kersommoura** [comment]
@Ichimonji10, done. Utilities related to Pulp2 can be moved as needed.
