### ISSUE TITLE
checking for presence of 'service' on EL6 fails 

### ISSUE THREAD

**Issue by dkliban** [PulpQE/pulp-smash#86]
NoKnownServiceManagerError exception is raised while running pulp-smash against an EL6 machine.

https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/cli.py#L292

**Comment by Ichimonji10** [comment]
What service manager is used by RHEL 6? Is it a SysV-style init manager, or systemd, or OpenRC, or something else? Assuming it's a SysV-style init manager, is the `service` utility installed on the system? Assuming `service` is installed, why is it not available to the user Pulp Smash logs in as? Is it because `$PATH` excludes `service` for certain users?

**Comment by Ichimonji10** [comment]
Also, is this a consistent issue, or is this a one-off error? I ask because our Jenkins instance has been (and still is) successfully running the test suite against Pulp on RHEL 6.

**Comment by dkliban** [comment]
'which' alias and binary are available on the RHEL 6 box. When I login as user jenkins to the box, I am able to run 'which service'. However, when pulp-smash runs the command remotely, the 'service' binary cannot be located for some reason. I did not investigate for long before I switched Jenkins at my branch of pulp-smash. Here[0] is what I did to get it working last night. Before I did that, pulp-smash was experiencing failures on all tests that requires remote execution on RHEL 6. 

[0] https://github.com/dkliban/pulp-smash/commit/8526e6a63690639c19fac59ba8b9cfbefaa65e5a

**Comment by Ichimonji10** [comment]
@dkliban When executing commands remotely via `ssh hostname some_command`, you're not given an interactive shell. That's likely the root of the issue.

**Comment by Ichimonji10** [comment]
@dkliban Take a look at `/etc/profile` on the target system.

**Comment by Ichimonji10** [comment]
From the bash man page:

> When  bash is invoked as an interactive login shell, or as a non-interactive shell with the --login option, it first reads and executes commands from the file /etc/profile, if that file exists.  After reading that file, it looks for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and executes commands from the first one that exists and is readable.  The  --noprofile  option may be used when the shell is started to inhibit this behavior.
