### ISSUE TITLE
As an authenticated user, I can delete any repository version.

### ISSUE THREAD

**Issue by kersommoura** [PulpQE/pulp-smash#871]
Add tests to explore functionality to delete any repository version - Pulp3.

See issue: [3219](https://pulp.plan.io/issues/3219)

This issue will be update with more details

It was suggested by @dkliban to use a large number of files, at least 10 files, and create a repo version for each file that was added to the repo.

**Comment by daviddavis** [comment]
A couple things to check for:

1. Deleting a version (e.g. 1) doesn't affect the content of successive versions (e.g. 2, 3, ...)
2. The last version can be deleted
3. If I delete the last version (e.g. 3) and then create a new version, it should not have the previously deleted version # (e.g. 3). It should be 4.
4. If I delete a version and it has a publication, the publication should be removed too.
