### ISSUE TITLE
As a User I would like Pulp3 to not show me offline workers in the status api

### ISSUE THREAD

**Issue by daviddavis** [PulpQE/pulp-smash#877]
Steps:

1. Kill a worker in Pulp 3
2. Wait until the worker missed its heartbeat check in
3. Query the status endpoint and confirm that the worker is not listed.

I think you can also query the worker endpoint to see if the worker is there but not online.

https://pulp.plan.io/issues/2659

**Comment by kersommoura** [comment]
Verify that:
 >As a user, I can filter offline workers to know if a worker has unexpectedly gone offline.

**Comment by kersommoura** [comment]
Using the workers endponint. Assert that:
> As a user, I can view all workers including offline workers. (status api only shows online workers)
