### ISSUE TITLE
As a user, I can view content for a repository version

### ISSUE THREAD

**Issue by daviddavis** [PulpQE/pulp-smash#878]
1. Create a repo and importer
2. Sync repo
3. Look at the 'content_summary' field of the repo version and confirm it's correct
4. Query `/api/v3/repositories/<repo id>/versions/<version #>/content/` and `/api/v3/repositories/<repo id>/versions/<version #>/added_content/` confirm they have the correct info.

https://pulp.plan.io/issues/3059

**Comment by kersommoura** [comment]
Read `added_content `instead of `add_content.`

**Comment by Ichimonji10** [comment]
I've updated the issue as per @kersommoura comment.
