### ISSUE TITLE
Test that Docker images can be synced from the v2 registry

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#88]
1. Use `registry-1.docker.io` as your feed url.
2. "Upstream name" must be in the format <namespace>/<reponame>. For repos that do not have a namespace, use "library". See: https://pulp.plan.io/issues/1404

Steps

1. Create a docker repo with feed registry-1.docker.io

    pulp-admin docker repo create --repo-id=synctest --feed=https://registry-1.docker.io --upstream-    name=library/busybox

    Assert:  Repository create is successful

2. Synchronize the repository

    pulp-admin docker repo sync run --repo-id synctest

    Assert: Docker images are synced

**Comment by omaciel** [comment]
@preethit great! How about filing separate issues to get other actions implemented as well? Publish, Edit? Delete? Copy? Let's get 100% coverage here
