### ISSUE TITLE
As a user, I get user-friendly error messages

### ISSUE THREAD

**Issue by daviddavis** [PulpQE/pulp-smash#882]
Some things to test:

* Duplicate repo names
* Dupe publisher names
* Dupe importer names
* Username only contains letters, numbers, and @/./+/-/_
* Username is more than 150 chars

You'll want to ensure that for each error, you get:

* A 400 response code
* A human readable/user friendly message (e.g. "name: 'This field must be unique.'")

https://pulp.plan.io/issues/2984

**Comment by kersommoura** [comment]
All those scenarios were already covered.  Closing this issue. Feel free to re-open in case of need.
