### ISSUE TITLE
As a user, I can auto-distribute publications

### ISSUE THREAD

**Issue by daviddavis** [PulpQE/pulp-smash#883]
### Failed Create 

1. Create a distribution without publisher but with repo
2. Confirm 400 response with error message "Repository must be set if publisher is set."

### Successful Create but Failed Update

1. Create a distribution with publisher and repo
2. Confirm 200
3. Update repository to Null
4. Confirm 400 with message "Publisher must be set if repository is set."

## Auto-distributing

1. With publisher and repo set on a distribution, publish a new publication
2. Confirm that publication on your distribution matches the new publication
3. (Optional) At this point, you could try to download a file or content item from your publication

https://pulp.plan.io/issues/3394

**Comment by kersommoura** [comment]
See also: https://pulp.plan.io/issues/3671
