### ISSUE TITLE
Trailing slash in distribution base_url - distributions.

### ISSUE THREAD

**Issue by kersommoura** [PulpQE/pulp-smash#888]
Track the discussion of [3412](https://pulp.plan.io/issues/3412), related to the use of trailing slash in distribution `base_url` field, and based on the final decision update the gen_distribution function.

See also: [886](https://github.com/PulpQE/pulp-smash/pull/886)

**Comment by Ichimonji10** [comment]
The `gen_distribution` function can append a trailing slash if `selectors.bug_is_testable(3142, cfg.pulp_version)`. Is that a reasonable solution?

**Comment by Ichimonji10** [comment]
Good point. Perhaps something like this could be placed into the method?

```python
if selectors.bug_is_testable(3412, config.get_config().pulp_version):
    warnings.warn('The base_url field may be malformed. See: https://pulp.plan.io/issues/3412')
```

And yes, I understand that plumbum emits gobs of warnings, and that they can drown out a warning like this. But in a technical sense, this seems correct. And I'd like to drop plumbum anyway.

I'm dropping the "plan" tag in favor of the "discussion" tag, as there's not yet a plan of action that has been settled on.

**Comment by kersommoura** [comment]
I like this idea, then when the status of 3142 changes, this will work as a reminder.
Perhaps this approach may be used for other important issues that we want to monitor.

**Comment by Ichimonji10** [comment]
Sounds like a plan to me. :tongue:
