### ISSUE TITLE
As an authenticated user, I can access auto generated docs.

### ISSUE THREAD

**Issue by kersommoura** [PulpQE/pulp-smash#893]
As an authenticated user, I can access `api/v3/docs` and have access to the auto generated docs.

This require the installation of drf_openapi. See: [drf_open_api](https://docs.pulpproject.org/en/3.0/nightly/integration_guide/rest_api/index.html#pulpcore-rest-api)

**Comment by daviddavis** [comment]
👍 

It might be nice to have two tests here. One against pulpcore and one against pulp_file (making sure that pulp_file routes show up when pulp_file is installed.)

**Comment by kersommoura** [comment]
See  also: https://pulp.plan.io/issues/3539
