### ISSUE TITLE
Repository create and sync with --remove-missing 

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#90]
Test to verify that repositories can be created and synced when using --remove-missing. Assert that the --remove-missing is functioning as expected
https://pulp.plan.io/issues/1621

------
Will come back and add steps

**Comment by preethit** [comment]
I see 2 options ( There may be 1 more) how we can go
Option 1
1. Create a repo  foowith a feed to a repo  bar on another pulp-server 
pulp-admin rpm repo create --repo-id foo --feed http://pulp-server1/bar --remove-missing true
Assert
 The repo create is successful with the options

2. Synchronize the repo
pulp-admin rpm repo sync run --repo-id foo

3. On  remove an rpm from the bar repo
pulp-admin rpm repo remove rpm --repo-id bar  --str-eq="name=dog"
Assert: rpm dog is removed from the repo 

4. Publish repo "bar"
pulp-admin rpm repo publish run --repo-id bar

5. Synchronise the foo repo
Assert
 1. Sync is successful
 2.The rpm that is removed from the parent repo is removed from the local repo as well

**Comment by peterlacko** [comment]
@preethit @Ichimonji10, is there something more that needs to be tested? comment please. To PR I'll add also conditional execution of tests on 2.8, as they are failing currently.

**Comment by Ichimonji10** [comment]
@peterlacko, there's no need to conditionally execute tests on Pulp 2.8. See:

* https://github.com/PulpQE/pulp-smash/pull/97
* https://github.com/PulpQE/pulp-smash/commit/77f50a400c690d0eef594b3346816fecb1311413

**Comment by Ichimonji10** [comment]
> is there something more that needs to be tested? comment please.

There are not any tests that make use of the `--remove-missing` pulp-admin flag or its equivalent in the API. That's a good place to start.

**Comment by omaciel** [comment]
@peterlacko hi there, what's the status for this issue?

**Comment by Ichimonji10** [comment]
This is tested by module `pulp_smash.tests.rpm.api_v2.test_remove_unit`.
