### ISSUE TITLE
As a user, I can import RPM package which has rich dependencies in *Requires*

### ISSUE THREAD

**Issue by dparalen** [PulpQE/pulp-smash#901]
### Description

RPM content can have [rich/boolean dependencies](http://rpm.org/user_doc/boolean_dependencies.html) specified in e.g the `Requires` field.
 The following use cases should nevertheless be all possible with [such content](https://github.com/PulpQE/pulp-fixtures/pull/78):

- [x] a repository can be synchronized with a rich dependency content feed
- [x] rich dependency content can be uploaded into a repository 
- [x] `pulp-admin` shows the `Requires` field for both the simple- and rich-dependency content
- [x] a repository containing rich dependency content can be copied :pear:
- [x] a repository containing rich dependency content can be published
- [ ] a consumer can be fed from a Pulp repository containing rich dependency content
- [x] a consumer, such as `dnf`, can process rich dependencies expressed in the content

### Notes

:beetle: ~~https://pulp.plan.io/issues/3339~~
:beetle: https://pulp.plan.io/issues/3715

:pear: Pulp not processing rich dependencies, [recursive content copies](https://docs.pulpproject.org/dev-guide/integration/rest-api/content/associate.html?highlight=recursive#copying-units-between-repositories) won't work properly until https://github.com/pulp/pulp_rpm/pull/1122 gets merged.

**Comment by rochacbruno** [comment]
`a consumer can be fed from a Pulp repository containing rich dependency content`

We are testing the installation of packages from a Pulp repository having rick/weak dependencies, is that meeting the requirement? can we consider this issue closed?
