### ISSUE TITLE
when broker reconnect test fails, all following tests fail

### ISSUE THREAD

**Issue by dkliban** [PulpQE/pulp-smash#91]
The broker reconnect test should restart all the services after it is done running.

**Comment by Ichimonji10** [comment]
That should be happening now.

```python
    def tearDown(self):
        """Ensure Pulp services are running."""
        for service in self.services + (self.broker,):
            service.start()
```

Please give more information.

**Comment by Ichimonji10** [comment]
The broker reconnect tests work well for me locally.

**Comment by dkliban** [comment]
They need to be stopped first. Then started again.

**Comment by dkliban** [comment]
I filed an issue[0] with Pulp yesterday afternoon. Pulp-smash currently fails a bunch of other tests also because Pulp is rendered useless when it fails to reconnect to the broker.

[0] https://pulp.plan.io/issues/1635

**Comment by Ichimonji10** [comment]
Ahhhh, now I understand. Thanks for giving the "why".

**Comment by Ichimonji10** [comment]
@dliban Does that bug imply that the services should be restarted in a certain order?

**Comment by dkliban** [comment]
@Ichimonji10 I don't think it matters in what order they are restarted.
