### ISSUE TITLE
As a user, I can automatically update my distribution

### ISSUE THREAD

**Issue by asmacdo** [PulpQE/pulp-smash#917]
This feature was added without an issue, but it is related to
https://pulp.plan.io/issues/3295

It is documented by this issue:
https://pulp.plan.io/issues/3392

A Distribution has 2 fields that specify auto-distribution:

- publisher
- repository

Either both of these are set or neither are set. I think this is already tested, but not sure. Assuming they are both set, whenever the Distribution.publisher creates a new Publication of the Distribution.repository, this Distribution will automatically be updated to the new Publication.

Simple case
1. Create a Distribution with publisher and repository attrs.
2. Publish using the Publisher and Repository
3. Make sure Distribution points to new Publication.

Overwrite case
1. Create a Distribution with publisher and repository attrs.
2. Associate the Distribution to a Publication
2. Publish using the Publisher and Repository
3. Make sure Distribution points to new Publication.

Unset case
(continued from either)
1. Update the Distribution, removing publisher and repository 
2. Publish the repo
3. Make the Distribution does not point to the new Publication.

**Comment by Ichimonji10** [comment]
Closed by #1012
