### ISSUE TITLE
Test sync with repo that has directory structure

### ISSUE THREAD

**Issue by asmacdo** [PulpQE/pulp-smash#93]
This https://github.com/pulp/pulp_rpm/pull/787 fixed an issue that was apparent when syncing from the CDN, but not when syncing from zoo. The reason for this is that the CDN's packages were in a `Packages/` dir, but zoo has a flat structure.

**Comment by Ichimonji10** [comment]
Where can I find a repository with a non-flat directory structure?

**Comment by asmacdo** [comment]
I have created a task for us to create a demo repo in pulp. https://pulp.plan.io/issues/1668

**Comment by Ichimonji10** [comment]
:+1: Woot!
