### ISSUE TITLE
Test auto distribution of a repository

### ISSUE THREAD

**Issue by dkliban** [PulpQE/pulp-smash#947]
1. Create repository 'foo'
2. Create version 1 of repository 'foo'
3. Create a File publisher named 'bar'
4. Create distribution 'zip' and set the 'repository' to repository 'foo'.
5. Create a publication of 'foo' repository version 1 
6. Check that distribution 'zip' now has publication set to the publication created in step 5.
7. Create 'foo' repository version 2 by adding some content.
8. Create a publication using 'foo' repository version 2
9. Check that distribution 'zip' now has publication set to the publication created in step 8.
10. Check that content add in step 7 is now available to download from distribution 'zip'.

**Comment by kersommoura** [comment]
There is no http://pulp.plan.io/issues/ associated with, but this issue is part of the MVP document.

As per MVP:
> As a user, I want a newly created publication to be automatically served by the content as defined by distributions.

**Comment by jlsherrill** [comment]
> 4)  Create distribution 'zip' and set the 'repository' to repository 'foo'.  
should be
> 4) Create distribution 'zip' and set the 'repository' to repository 'foo' and a 'publisher' to publisher 'bar'

**Comment by kersommoura** [comment]
See also: #917 and #883
