### ISSUE TITLE
Repository create and sync with --retain-old-count

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#95]
https://pulp.plan.io/issues/1624

I need to clean this up with clearer steps.

Create a repo foo with a feed to a repo bar on another pulp-server

```sh
pulp-admin rpm repo create \
    --repo-id foo \
    --feed http://pulp-server1/bar \
    --retain-old count 2
```

Assert the repo create is successful with the options

Synchronize the repo

```sh
pulp-admin rpm repo sync run --repo-id foo
```

**Comment by Ichimonji10** [comment]
Hmm. This requires multiple Pulp servers. I'm going to have to think on how to implement this one.

**Comment by preethit** [comment]
It may not require multiple pulp servers
One option would be using a directory with multiple versions of the rpm and running createrepo. And using that  directory for feed  {--feed file:///repo-directory}
