### ISSUE TITLE
Add test to cancel a task.

### ISSUE THREAD

**Issue by kersommoura** [PulpQE/pulp-smash#976]
Related  to: #754 

Create a task that takes a **long** time to complete.  Long meaning several seconds or longer.

Possible solutions to achieve such:

1. Using file plugin. Add a fixture that has files with GB of data.
2. Using another plugin. Use third party repos such as: Python or Suse  to sync large content from those sources.

There are other factors that can influence this sync time, such as networking latency.

Assure that the task is in one the following states ('waiting', 'running'), then cancel it.

**Comment by Ichimonji10** [comment]
As far as I know, there are no tasks which deterministically take a long time to complete. As a result, the second-best thing we can do is to launch a task which saturates some systm resource, such as CPU time or network bandwidth, and try to make a test that completes quickly enough.

I strongly caution against writing a test that saturates available network bandwidth, especially if targeting a resource that's freely made available to the public (like `repos.fedorapeople.org`) for public benefit.

A task which saturates some other resource could be much better. As an example, when Pulp 2 parses the metadata in a large OpenSUSE repository, it takes tens of minutes to complete, even on modern hardware. If the Pulp 3 plugin improves enough, perhaps a similar approach could be taken for this test.
