### ISSUE TITLE
get_content_unit_paths() is located in a generic utils, but uses a field only present on the File plugin

### ISSUE THREAD

**Issue by dralley** [PulpQE/pulp-smash#979]
https://github.com/PulpQE/pulp-smash/blob/master/pulp_smash/tests/pulp3/utils.py#L250

```relative_path``` only exists on the FileContentUnit type.

**Comment by Ichimonji10** [comment]
This is great to know. A reasonable solution is to move this function into `pulp_smash.tests.pulp3.file.api_v3.utils`.
