### ISSUE TITLE
 Repo copy of docker 2.0 repo 

### ISSUE THREAD

**Issue by preethit** [PulpQE/pulp-smash#98]
1. Create a docker repo with feed of v2 

      Assert: Repo is created

2. Sync the repo

    Assert: Repo sync successful

3. Create a docker repo with no feed
     Assert:No feed repo created

4. Run repo copy from synced repo  to the destination repo

    Assert: Repo copy successful

5. Run repo list

    Assert: Lists repo 
             Repo content in the destination same as the source.

**Comment by rbarlow** [comment]
@Ichimonji10 I'll take this one if you want to assign it to me.
