### ISSUE TITLE
psmash in the Pulp development environment is failing due to a lint error

### ISSUE THREAD

**Issue by rbarlow** [PulpQE/pulp-smash#99]
In the Pulp development environment, psmash fails due to a linter error:

```
$ time psmash                                                                                 
~ ~/devel/pulp-smash ~/devel/pulp
flake8 . --ignore D203
pylint -j 4 --reports=n --ignore-imports=y --disable=I \
        docs/conf.py \
        setup.py \
        tests \
        pulp_smash/__init__.py \
        pulp_smash/__main__.py \
        pulp_smash/api.py \
        pulp_smash/cli.py \
        pulp_smash/config.py \
        pulp_smash/constants.py \
        pulp_smash/exceptions.py \
        pulp_smash/selectors.py \
        pulp_smash/utils.py
No config file found, using default configuration
************* Module tests.test_selectors
C:  8, 0: standard import "import requests" comes before "import mock" (wrong-import-order)
Makefile:27: recipe for target 'lint-pylint' failed
make: *** [lint-pylint] Error 16
~/devel/pulp-smash ~/devel/pulp

real    0m13.982s
user    0m16.824s
sys     0m0.899s
```

**Comment by Ichimonji10** [comment]
This is the first ten lines of `pulp_smash.selectors`:

```python
# coding=utf-8
"""Unit tests for :mod:`pulp_smash.selectors`."""
from __future__ import unicode_literals

import random

import mock
import requests
import unittest2

from pulp_smash import exceptions, selectors
```

`import requests` comes after `import mock`, but the error message describes the opposite. @rbarlow, what is the output of `git status`? Is the Pulp Smash repository in a sane state?

**Comment by rbarlow** [comment]
Hmm, that doesn't seem to be current master. When I browse github to current master, I see this:

https://github.com/PulpQE/pulp-smash/blob/abb104fc9c54ae99192f8d05e416e4ecbdf8dc8d/pulp_smash/selectors.py#L1-L11

**Comment by Ichimonji10** [comment]
Look at that URL...

**Comment by Ichimonji10** [comment]
@rbarlow You're linking to `pulp_smash.selectors`, not `tests.pulp_smash.selectors`.

**Comment by rbarlow** [comment]
Ah yes, I see that now. So now I am puzzled because I still get that error on my Vagrant box, but the code isn't the way that pylint is complaining (i.e., the code is the way you are saying it is.) I mean, this seems crazy, right?

```
(pulp-smash)[vagrant@dev pulp-smash]$ pylint -j 4 --reports=n --ignore-imports=y --disable=I tests/test_selectors.py
No config file found, using default configuration
************* Module tests.test_selectors
C:  8, 0: standard import "import requests" comes before "import mock" (wrong-import-order)
(pulp-smash)[vagrant@dev pulp-smash]$ head tests/test_selectors.py
# coding=utf-8
"""Unit tests for :mod:`pulp_smash.selectors`."""
from __future__ import unicode_literals

import random

import mock
import requests
import unittest2
```

This must be a pylint bug? Can you not reproduce this? Looks like I've got pylint==1.5.4.

**Comment by Ichimonji10** [comment]
I cannot reproduce this. What modules are being linted by Pylint? That is, which modules are bing imported by the Python interpreter? I strongly suspect that the code you're looking at is not the code that's being used.

**Comment by rbarlow** [comment]
@Ichimonji10 if you look at the CLI I pasted above, it's only linting this one module (last arg).

Does this not happen when you run it in the Pulp Vagrant environment?

**Comment by Ichimonji10** [comment]
@rbarlow I don't run Pulp Smash within the Vagrant environment. I'm ignorant of how Pulp Smash has been integrated into Vagrant.

**Comment by Ichimonji10** [comment]
To give some context: I typically have a single clone of the Pulp Smash repository cloned onto my host development system, and I do development in this one repository and test Vagrant systems from it. (There's typically two or four Vagrant systems running at once). In other words, I run Pulp Smash outside of Vagrant, not inside. A screenshot might help.

![screenshot_2016-02-11_12-12-44](https://cloud.githubusercontent.com/assets/1012989/12983856/2e9cc83c-d0b9-11e5-9113-64fb4525fabe.png)

Anyway, I don't mean to discount the validity of what you're saying. I'm pointing out the differences between our environments.

**Comment by rbarlow** [comment]
If you want to try to reproduce what I'm seeing, if you have pulp-smash checked out alongside pulp and friends during vagrant up, all you need to do is run ```psmash``` after you vagrant ssh.

I haven't been able to figure out what is wrong, but I agree that the code it is complaining about is not wrong so it's got to be either environmental or a pylint bug.

What version of pylint are you using?

**Comment by Ichimonji10** [comment]
> If you want to try to reproduce what I'm seeing, if you have pulp-smash checked out alongside pulp and friends during vagrant up, all you need to do is run psmash after you vagrant ssh.

Cool. I'll try that! Thank you. :smile:

> What version of pylint are you using?

pylint 1.5.4, astroid 1.4.4
